### ISSUE TITLE
Add Travis and Code-Checks 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#1]
Add travis and other code-checks to repo.

**Comment by nanspro** [comment]
@mariobehling  I  would like to work on this issue

**Comment by nanspro** [comment]
.travis.yml file is already present
Can you specify what do you mean by Code-Checks

**Comment by jajodiaraghav** [comment]
Hi @nanspro I think Mario is referring to adding tests to the repository so that we can prevent introduction of bugs in the project.

**Comment by niccokunzmann** [comment]
Ideas for tests:

- [ ] check that the input is in the SVG file
- [ ] check that the image is in the SVG file
- [ ] test that the uploaded image and configuration is used to build the result

These are very easy tests but useful bacause they introduce a restructuring which allows testing before more features are added and adding tests implies more rewriting without knowing whether it breaks a feature.

**Comment by jajodiaraghav** [comment]
Can I work on this?

**Comment by niccokunzmann** [comment]
@jajodiaraghav Sure, you can create a PR and share the progress.

**Comment by niccokunzmann** [comment]
If someone like to dig into how to test user interfaces of websites and flows, they can have a look at selenium. I would help to do the introduction. This is really something many projects need: How to test the UI flow.

**Comment by jajodiaraghav** [comment]
Hi everyone, I was checking out a few testing packages and I couldn't figure out which one to use (CasperJS?). I do not have experience writing tests.
Also, most testing packages require npm. Is it fine to integrate npm to our repository and add the package.json file?

**Comment by niccokunzmann** [comment]
So, the JS packages are for nodejs. They can not be used here. UI testing is different from testing serverside Javascript. Please follow this tutorial to set up one initial test: https://engineering.aweber.com/getting-started-with-ui-automated-tests-using-selenium-python/

**Comment by jajodiaraghav** [comment]
@niccokunzmann Thanks a lot. This has clarified my doubts :)
I will create a PR soon and update my progress so that others can join in.

**Comment by niccokunzmann** [comment]
#87 added the basic test. I will create more issues...

**Comment by niccokunzmann** [comment]
#89 #90 #91 should cover this now. Thanks @jajodiaraghav! We can create more issues...
