### ISSUE TITLE
Use version pinning

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#10]
We want this app to work for a long time. Versions of modules change, please pin the version of the used python packages in the requirements.txt file. ([Reasoning](https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/56))

You can use pip-tools for this: `pip install pip-tools`.

**Comment by jajodiaraghav** [comment]
Can I take this? Will submit a PR soon

**Comment by niccokunzmann** [comment]
Sure, please let us know about your progress here.

**Comment by jajodiaraghav** [comment]
@niccokunzmann I used pip-tools. Have a look :)
