### ISSUE TITLE
Add Hound CLI

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#105]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

This would help new contributors provide good pull request

**Comment by niccokunzmann** [comment]
Sorry @S2606, I can not understand which problem you solve by adding hound cli. Could you explain this?
