### ISSUE TITLE
Add Admin route to frontend

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#1061]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

Adding a frontend route for admin functionalities.
**I am working on this and will send a PR for the same**

**Comment by yashLadha** [comment]
It is already initiated in https://github.com/fossasia/badgeyay/issues/1052 . Can you please iterate over it

**Comment by gabru-md** [comment]
oh yes! I forgot to close this issue
