### ISSUE TITLE
Overlapping of footer with the main container

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#110]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
footer overlaps the main container

**Expected behavior:**
its should stick to the bottom

**Steps to reproduce:**
1. Resize window to `1366x768` or less
2. Scroll to reproduce issue

 **Screenshots**
![image](https://user-images.githubusercontent.com/8705386/30544037-b13c05cc-9c74-11e7-9c9f-f5ac8d96244e.png)

**I am interested in working on this issue**

**Comment by S2606** [comment]
@vaibhavsingh97 It looks like you havent updated your forked development branch as this issue is already being solved. Please update it.

**Comment by vaibhavsingh97** [comment]
@S2606 Yeh! it's resolved. 😄 
Sorry!! I forgot to update. Since it's resolved so closing this issue :)
