### ISSUE TITLE
No warning/error when not filling the required field

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#112]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
No warning/error message when we don't upload csv file (Required field)

**Expected behavior:**
It should give warning/error to user

**Steps to reproduce:**
1. Open `http://127.0.0.1:5000/` locally
2. Select the download type
3. Enter data (Caution: Don't upload any csv file)
4. Enter Eventyay url
5. Click on upload

**Yes, I want to work on this issue**

**Comment by gabru-md** [comment]
@vaibhavsingh97 this issue seems a bit dizzy, can you please clarify what is the issue ?

**Comment by vaibhavsingh97** [comment]
@gabru-md I updated the issue 😅

**Comment by gabru-md** [comment]
@vaibhavsingh97 

> After we choose download type, enter data and enter eventyay URL and we upload the data and we get option to download pdf.

well If you upload data by entering it in the field then it *will* produce the pdf/zip file.
You can either upload a CSV or enter data manually. So entering either will produce the pdf/zip.


the `steps to reproduce` is the column to specify *how would you solve the issue? ( if you can )*
It is not about how to *see* the issue.
please note this next time.

**Comment by gabru-md** [comment]
@vaibhavsingh97 
am i clear? or am i still wrongly interpreting your issue ?

**Comment by gabru-md** [comment]
PS : @jajodiaraghav @S2606

**Comment by vaibhavsingh97** [comment]
@gabru-md Understood 👍 
Still we get internal server error if we left Eventyay Url blank 😅

**Comment by jajodiaraghav** [comment]
Is anyone working on this issue, or is it open for claiming?

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav I am working on it. Please give me sometime

**Comment by jajodiaraghav** [comment]
@vaibhavsingh97 Should I claim this since you haven't made any update for last 20 days,
@fossasia/badgeyay-admin

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav I this issue, as this is not an issue. It's mine misunderstanding the working of badgeyay
