### ISSUE TITLE
Page refresh gives  404 on deployment

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#1125]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

On refreshing any page except of index page, gives 404

**Expected behaviour:**

This should not happen as it provided non uniform user experience

__Yes__ working on it

**Comment by yashLadha** [comment]
https://stackoverflow.com/questions/28617907/ember-cli-browser-refresh-production-404 According to this workaround either we have to append hash at the end of the url to make it work on gh-page, but it will not look consistent. Or we have to go for our server or other cloud providers for deployment. 
Views @gabru-md @ParthS007 @djmgit @niranjan94 

As the url like http://badgeyay.com/#/create-badges
http://badgeyay.com/#/user/<id> is not a good user experience

**Comment by ParthS007** [comment]
https://discuss.emberjs.com/t/how-to-serve-all-routes-on-a-production-server-exactly/6372
