### ISSUE TITLE
Email Verification link not working

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#1126]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Email verification link not working due to an error in decryption.

**Expected behavior:**
It should work and email should be verified.

**Yes**, I am working on it.

**Comment by yashLadha** [comment]
Can I work on the same. @ParthS007

**Comment by ParthS007** [comment]
ok. go ahead @yashLadha  :+1:
