### ISSUE TITLE
Adding mail statistics in Badgeyay

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#1136]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

There is no mail statistics shown in the admin index page.

**Expected behaviour:**

There should be mail statistics shown in the mail index page

There are two ways to tackle it:
* Using the firebase realtime database and as soon as a successful mail is sent it can add an entry with the date in it. This will also help to tackle the case for non successful emails sent, but in the admin we have to create the logic to parse the firebase realtime database objects to get the desired results and in this way we are more closely attaching to firebase as there is a limit on the usage of firebase realtime database (Storage limit).
* Sending an API Request to our backend API and updating the entry in our database. This way we do not have to rely on the firebase services, but in the firebase free plan we cannot send an external request to an API except google own API's.

Views @djmgit @ParthS007 @gabru-md @abhi40308

**Comment by mariobehling** [comment]
@yashLadha I am not sure what is the best way, but we can wait for others. It looks like both ways depend on Firebase. So, I tend to the "free plan" implementation.
