### ISSUE TITLE
Make travis run the UI tests

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#119]
This is an issue for people who would like to learn basic quality assurance using tests for web applications.
**I'm submitting a ...**
- [X] bug report

**Current behavior:**

Currently, travis does not run the UI tests.
These are tests that click on the webpage of the application and make sure, certain uer/stories and work flows stay while we develop.

**Expected behavior:**

I would liketravis to run those tests.

- [ ] add the tests to travis
- [ ] see that they fail in your pull-request because firefox can not start because travis has no GUI
- [ ] install phantomJS, a browser for such purposes without GUI and create a central place to change the "driver" (see source code)

**Steps to reproduce:**

https://travis-ci.org/fossasia/badgeyay/builds/277071140#L563
Related: a discussion in #116

**Comment by S2606** [comment]
@niccokunzmann i would like to work on this

**Comment by vaibhavsingh97** [comment]
@S2606 can we collaborate? I also want to work on this issue.

**Comment by gabru-md** [comment]
@niccokunzmann I can add the phantomJS installation code to .travis.yml .
I've done it before. 
And then we can work on tests as well.

**Comment by niccokunzmann** [comment]
travis still does not show output from the tests:
https://travis-ci.org/fossasia/badgeyay/builds/278113797#L567

Is there output to be expected`?

**Comment by S2606** [comment]
@niccokunzmann maybe this lnk can help
https://ilovesymposia.com/2014/10/15/continuous-integration-in-python-5-report-test-coverage-using-coveralls/

**Comment by jajodiaraghav** [comment]
The output is expected in case the tests fails.
