### ISSUE TITLE
Write Selenium tests for the app

### ISSUE THREAD

**Issue by mish24** [fossasia/badgeyay#122]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

This is a feature request for adding selenium tests for the app. Currently it'll test the following:
* Test the online presence of the heading/titles etc.
* Correct message is shown when fields are left blank.
* UI tests for placements of buttons etc

**Comment by mish24** [comment]
I'm claiming this :D

**Comment by niccokunzmann** [comment]
@mish24 Great! If you can create a pull-request as soon as you have a test, others can collaborate with you.

**Comment by pushkalkatara** [comment]
@mish24 Are you working on this issue?

**Comment by mish24** [comment]
@pushkalkatara Yes! I'm sorry I thought we're supposed to send a PR when we've done considerable work. I'll add the tests I've written so far, so that others can build on it.

**Comment by gabru-md** [comment]
@mish24 any progress?

**Comment by apsknight** [comment]
Is this issue still open, I would like to work on this.

**Comment by niccokunzmann** [comment]
Sure, welcome! Please go ahead.
There is also an issue on how to get the tests run on travis, which is 
related to this.

**Comment by mariobehling** [comment]
As the UI is changing a lot still, we will come back to UI tests later. Closing it now.
