### ISSUE TITLE
merge_badges.py not working

### ISSUE THREAD

**Issue by parth-p** [fossasia/badgeyay#125]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
False False
/usr/bin/rsvg-convert
/usr/bin/python3
/usr/bin/pdftk
Traceback (most recent call last):
  File "merge_badges.py", line 27, in <module>
    input_folders = [file for file in os.listdir(BADGES_FOLDER)
FileNotFoundError: [Errno 2] No such file or directory: 'static/badges'

**Steps to reproduce:**
python3 merge_badges.py

**Comment by parth-p** [comment]
I would like to work on this.

**Comment by S2606** [comment]
@parth-p Sure go ahead and send PR

**Comment by gabru-md** [comment]
@parth-p what is the error exactly ? because I am not getting any error on my localhost

**Comment by sayak119** [comment]
@gabru-md I think he is saying that there is no folder named badges in static. badges folder is in app

**Comment by gabru-md** [comment]
The folder 'static/badges' is created by the `main.py` file with the following code
```python
def empty_directory():
	# Creates 'badges' directory if not exists
	if not os.path.exists(BADGES_FOLDER):
		os.mkdir(BADGES_FOLDER)

	# emptying previous files and ....
```
I believe that @parth-p tried to run `python merge_badges.py` and since `main.py` was not started , therefore no folder as 'static/badges' was created. 
To clear up things : `merge_badges.py` is made to work with `main.py` and not as a single script.
Running it as a script on terminal will not provide any results.

**Comment by jajodiaraghav** [comment]
This is incorrect! @parth-p Why do you want to run "python3 merge_badges.py"?
I think you are not aware of what the merge_badges.py is doing.
The app is run using `python3 app/main.py`

**Comment by gabru-md** [comment]
@jajodiaraghav I believe we can close this and the PR as well?

**Comment by jajodiaraghav** [comment]
@parth-p Can you please close the issue as well as the PR.
I also hope that this is not too discouraging to you. We would love it if you could claim some other issue and send a PR :)

**Comment by parth-p** [comment]
Ok I got it. i am closing it.
