### ISSUE TITLE
Pdf not generated when we run main.py from directories other than app like python3 app/main.py.

### ISSUE THREAD

**Issue by nanspro** [fossasia/badgeyay#126]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
![workspace 1_019](https://user-images.githubusercontent.com/24641089/30601926-bd36d0fc-9d80-11e7-8a41-b94154f3e95e.png)

**Expected behavior:**
File should execute no matter what our current directory is.

**Comment by gabru-md** [comment]
Please describe the bug in the issue body rather than the issue head!
kindly make the necessary changes so that it can be looked upon :)

**Comment by nanspro** [comment]
although this is not a bug but i think we should do something about this
or atleast update  README  that we should go to app in order to run the file.

**Comment by nanspro** [comment]
@gabru-md  accidentally created issue without main body 
Now it is updated.

**Comment by gabru-md** [comment]
@nanspro can you please explain what is the bug exactly ?
Or what steps did you carry that led to the bug ? so that we can help :D

**Comment by nanspro** [comment]
when i am present in badgeyay folder i run python3 app/main.py
then it showed error can't open merge_badges.py no such file or directory as shown in attached picture.

**Comment by gabru-md** [comment]
the above message was sent before you posted the image. now the issue is clear.
:+1:

**Comment by nanspro** [comment]
@gabru-md   i want to work on this.
Can you tell me is this a issue for which i should change code files or just update README with running instructions mentioning especially to move to app folder before running main.py

**Comment by gabru-md** [comment]
Please have a look at the following commands 
```python
def generate_badges(_zip=False,_pdf=False):
	if _zip == True and _pdf == True:
		os.system('python merge_badges.py -z -p')
	elif _zip == True and _pdf == False:
		os.system('python merge_badges.py -z')
	else:
		os.system('python merge_badges.py -p')
```
These commands do require one to be in the `app` folder . Yes! Readme can be updated in this case.
Thanks for pointing that out. :+1:

**Comment by gabru-md** [comment]
@nanspro 
- It would be great if you could try changing the code to make it work like you said.
- But if not then i would suggest you can change the readme.

Thanks!

**Comment by nanspro** [comment]
Or we can find the directory in which main.py is present and then we will find merge_badges.py there instead of present directory
Anyway i would like to work on this.

**Comment by nanspro** [comment]
ok @gabru-md  i am working on this then.

**Comment by jajodiaraghav** [comment]
@nanspro I still do not think this is a bug. If you still think you can fix this, send a PR!

**Comment by nanspro** [comment]
ok i will try

**Comment by nanspro** [comment]
Flask debugger is causing issues ,i am not able to resolve.
Shall i close this or let someone else try?

**Comment by nanspro** [comment]
@jajodiaraghav  @gabru-md

**Comment by gabru-md** [comment]
Can you give us the issue being caused ?

**Comment by nanspro** [comment]
![workspace 1_021](https://user-images.githubusercontent.com/24641089/30610788-f330310a-9d9c-11e7-81cb-828ee3bc67ec.png)

**Comment by nanspro** [comment]
![workspace 1_020](https://user-images.githubusercontent.com/24641089/30610794-f825125c-9d9c-11e7-9b08-9beeac2209fa.png)

**Comment by nanspro** [comment]
Expected output
![workspace 1_022](https://user-images.githubusercontent.com/24641089/30610851-2d602c72-9d9d-11e7-9158-ce9e162f9bd9.png)
Debugger is not becoming active i think it's inbuilt property of flask.

**Comment by nanspro** [comment]
@gabru-md

**Comment by gabru-md** [comment]
The debugger seems to be running anyway.
But i would suggest you to propose a change in README stating that `python main.py` must be executed from the `app` folder within.
Work upon the readme @nanspro !
