### ISSUE TITLE
UnboundLocalError : 'filename' referenced before assignment

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#127]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

When we enter data rather than uploading a csv we get this error.
![er](https://user-images.githubusercontent.com/25414121/30602002-3f2462b2-9d5b-11e7-931a-87b54a337f3c.png)

**Expected behavior:**

The process should carry out like always

**Steps to reproduce:**

**Comment by S2606** [comment]
@gabru-md Can you please tell me when this is happening??

**Comment by gabru-md** [comment]
@S2606 
I tried to enter random data into the textbox and clicked upload. And this caused the error.
The actual text i entered was "asdf" :P

I just checked and it does cause an INTERNAL SERVER ERROR on herokuapp as well.
Screenshot below :

![we](https://user-images.githubusercontent.com/25414121/30602671-2f164190-9d5d-11e7-8813-5eed1e1749c7.png)

**Comment by gabru-md** [comment]
@S2606 I've found a fix for this I'll be sending the PR soon.
Meanwhile this can be labeled as BUG.
