### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by sounak98** [fossasia/badgeyay#133]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

It is tryinng to find the file *.png.csv which doesn't exist.
![screenshot from 2017-09-20 12-26-46](https://user-images.githubusercontent.com/22390515/30630713-5bac1714-9dff-11e7-9392-a55b2f8c8d5d.png)

**Expected behavior:**

Should try to find the file *.

Would fix this.

**Comment by jajodiaraghav** [comment]
Hi @sounak98 
I think this issue has been fixed. Can you please check?
In case this isn't fixed, please send a PR.

**Comment by gabru-md** [comment]
This issue can be closed then ? @jajodiaraghav
