### ISSUE TITLE
Improve User Panel in Admin

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#1357]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce:**
Working on it.

**Comment by yashLadha** [comment]
Can I take up this issue @ParthS007 ?

**Comment by ParthS007** [comment]
Ok @yashLadha , Go ahead :+1:
