### ISSUE TITLE
left aligning create-badges component

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#1369]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

Aligning the create-badges component on the left side.
Leaving the right side space for the preview section.

**I am working on this**

**Comment by ParthS007** [comment]
@gabru-md There is already #1351 open for this.

**Comment by gabru-md** [comment]
It is not mentioned as to what will you be simplifying? Wasn't that issue created to make ithe component look simple.

I thought it had nothing to do with the left-aligning part :sweat_smile:
