### ISSUE TITLE
No error shown when only png file is uploaded.

### ISSUE THREAD

**Issue by nanspro** [fossasia/badgeyay#137]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
![workspace 1_027](https://user-images.githubusercontent.com/24641089/30653842-d5dca66c-9e49-11e7-8cda-a1f41016092e.png)
![workspace 1_024](https://user-images.githubusercontent.com/24641089/30653848-d9ee3612-9e49-11e7-8ca3-684080214089.png)

**Expected behavior:**
It should give an error like "No csv file found."

**Comment by gabru-md** [comment]
Will work on this

**Comment by nanspro** [comment]
i want to work on #137 and #138 if possible 
else i want to work on #137.

**Comment by gabru-md** [comment]
@nanspro It does show an error on my localhost.
Can you make sure that your local fork is in sync with the `fossasia:development`
![231](https://user-images.githubusercontent.com/25414121/30655469-e0abc6ca-9e28-11e7-9602-10f3cf384e7e.png)

I tried it without 
- no csv and no png
- png without csv

and it all seems fine.

**Comment by nanspro** [comment]
@gabru-md  try this:
- no csv and choose a png from dropdown

**Comment by gabru-md** [comment]
yes that does produce an error but that error is completely different from this one.
We want to remove that error and i've created another issue regarding it.
We want that badges should be generated and if only png is selected then throw error.

Have a look at : https://github.com/fossasia/badgeyay/issues/139

All the conditions will be taken care of within this issue . Seems good to you @nanspro ?

**Comment by nanspro** [comment]
ya #139  seems fine @gabru-md

**Comment by nanspro** [comment]
i am closing this then
