### ISSUE TITLE
No error shown when only csv file is uploaded

### ISSUE THREAD

**Issue by nanspro** [fossasia/badgeyay#138]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
![workspace 1_023](https://user-images.githubusercontent.com/24641089/30654162-c3764fae-9e4a-11e7-9960-f7e23ce1dd58.png)
![workspace 1_024](https://user-images.githubusercontent.com/24641089/30654169-c7309b5e-9e4a-11e7-9676-12d9f6b4bd15.png)

**Expected behavior:**
It should give an error like no png file found.

**Comment by nanspro** [comment]
also when camera.png.csv is uploaded it returns pdf with camera.png as background image and csv file on it

**Comment by nanspro** [comment]
![workspace 1_025](https://user-images.githubusercontent.com/24641089/30653977-3e25256e-9e4a-11e7-9f7d-38c7a11d57a9.png)

**Comment by nanspro** [comment]
![workspace 1_026](https://user-images.githubusercontent.com/24641089/30653986-47519244-9e4a-11e7-94b5-2ecc1ab4148f.png)

**Comment by gabru-md** [comment]
How is this a bug ? I mean Why should the webpage return an error when only CSV is entered?
It should produce a bug/error when CSV is not entered.
@nanspro Am i getting your issue right ?

**Comment by jajodiaraghav** [comment]
@nanspro 
In case the user uploads a file whose PNG is not present in the uploads folder (Default PNGs) we can just show an error that related PNG file is not found. That would fix this

**Comment by nanspro** [comment]
@gabru-md  i have mentioned two issues here actually
-When we upload x.csv it doesn't give an error which it should because how can a badge be created without background png file but instead it returns  badge successfuly made.
-When we upload camera.png.csv only it doesn't give an error and produced an pdf with camera.png as background image. I don't know whether this is a issue or not but i think it should give error as if i upload home.png.csv then it will not be able to produce a badge.

**Comment by nanspro** [comment]
@jajodiaraghav  what if we upload home.csv ?
What should we return as error in this case 
-"Wrong Format of csv it should be *.png.csv"
-"Couldn't find home.png"
-"Please upload a png file"

**Comment by nanspro** [comment]
@jajodiaraghav  are you saying we should always upload *.png.csv file and if it's png is not present in sample we should give an error?

**Comment by jajodiaraghav** [comment]
If PNG is uploaded along with the CSV:
- Generate badges
If PNG is not uploaded along with the CSV (check in following order):
- Show error if name of csv not in right format [something.png.csv]
- Show error if relevant png not found

**Comment by nanspro** [comment]
if camera.png.csv and guest.png is uploaded should i give a error
@jajodiaraghav  @gabru-md

**Comment by jajodiaraghav** [comment]
No. Then we want the badges to be generated!
In case this is not occurring, we can open another issue which you can work on once you are done with this issue.
