### ISSUE TITLE
Implement different Font Size for different line.

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#1407]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

![image](https://user-images.githubusercontent.com/24358501/43018125-35fbd30e-8c76-11e8-9387-9dc6f5842173.png)

Below I am attaching what we have discussed in last meeting.

![image](https://user-images.githubusercontent.com/24358501/43043407-d417fa3c-8db0-11e8-9231-af169dcfb11b.png)

**I am working on it**

This is a Parent Issue.

**Comment by mariobehling** [comment]
I think following the Eventbrite outline more closely makes sense. The only feature that we need on top of this is "adjust content".

**Comment by sk9331657** [comment]
@ParthS007 This issue can be closed.
