### ISSUE TITLE
implementing badge size

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#1408]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

Implementing badge sizes for badge generation.

**Comment by yashLadha** [comment]
Can I take this forward? @gabru-md

**Comment by yashLadha** [comment]
According to the standard conference badge sizes : [Link](http://www.mybadges.com/conference-id/name-badge-holders-name-tags/conference-name-badges-standard/) , the badge size that are standard are:
* 4″ x 3″ 
* 4-1/8″ x 4″
* 4-1/4″ x 3-5/8″
* A5

However paper size can be:
* A2
* A3
* A4
* A5

So are these should be the dimensions of the badge sizes and paper sizes for the system. Created a demo video showing the badge generated using badge-size : 4"x3" and paper-size: A4

**Comment by gabru-md** [comment]
sure please go ahead!
