### ISSUE TITLE
Ember-notify displaying multiple notifications

### ISSUE THREAD

**Issue by abhi40308** [fossasia/badgeyay#1412]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
Ember notify displays multiple notifications on clicking, and there seems no way provided to remove that (actually the pr in ember-notify repo to tackle this issue is stalled from a long time : https://github.com/aexmachina/ember-notify/pull/105) .

Preview: 
![screen shot 2018-07-21 at 3 12 16 am](https://user-images.githubusercontent.com/26903230/43026572-e8c90c28-8c93-11e8-9a7a-ac6588e627b0.png)

**Expected behaviour:**
 I think we can use this instead: ember-cli-flash : https://www.emberobserver.com/addons/ember-cli-flash . This has far more active contributors and is updated continuously.

**Steps to reproduce:**

 I would like to work on this.

**Comment by abhi40308** [comment]
@ParthS007 @gabru-md @yashLadha Please give your views on this.

**Comment by yashLadha** [comment]
Can you send us the demo video or sceenscast in action. Looks promising. :+1:

**Comment by ParthS007** [comment]
Yes, Please send us a demo then we can decide :+1:

**Comment by abhi40308** [comment]
Sure i will create a demo soon :)

**Comment by ParthS007** [comment]
@abhi40308  Any updates?

**Comment by abhi40308** [comment]
I am trying to find a new notification package which can be used with semantic, also i commented on ember-notify issue to merge the stalled pr. I will try it again in 2-3 days. If I am not able to solve this, I will let you know within 2-3 days.
