### ISSUE TITLE
Integrate Badgeyay into open-event-server

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#143]
**I'm submitting a ...**
- [X] feature request

**Current behavior:**

Currently, badgeyay is a standalone website.
I would like to have a one-click solution from eventyay to generate badges.

**Expected behavior:**

Please add a button to the [open-event-orga-server](https://github.com/fossasia/open-event-orga-server) to generate a badge for the list of speakers.

**Steps to reproduce:**

1. I go to an example event.
1. I go to the edit page of the event
1. I view the list of speakers
1. I click on generate badges
1. I am redirected to the [badgeyay website](https://github.com/fossasia/badgeyay) in an other tab (fields are prefilled)
1. I can choose the png file (speaker is preselected)
1. I click on generate badges
1. I download the pdf file

(This is a proposed workflow. If it does not work, please propose another. for closing the issue one agreed workflow must stand)

Hints: 
- Please make yourself familiar with eventyay.
- This issue is crossposted: https://github.com/fossasia/open-event-orga-server/issues/4475

**Comment by vaibhavsingh97** [comment]
@niccokunzmann Can i work on this issue?

**Comment by gabru-md** [comment]
sure go ahead. 
Just keep us posted about it. And incase you need any help just comment below. 
:)

**Comment by pushkalkatara** [comment]
Suggestion: Do we need the redirect? Directly printing speakers from the button on open-event-orga-server and all these steps in the background? @gabru-md @niccokunzmann

**Comment by niccokunzmann** [comment]
Mario Behling suggested to wait and put the effort into refactoring. [source](https://github.com/fossasia/open-event-orga-server/issues/4475#issuecomment-331208493) Thus, we can not integrate it into badgeyay now. To me, this does not mean we should not investigate on how to do that.

**Comment by niccokunzmann** [comment]
@pushkalkatara There are some settings like background image, paper size and download format. Somehow they need to be set. I think, the proposed way adds minimal changes to eventyay while using much of what is present in badgeyay.

In general, what do we all think about which changed need to be made?

**Comment by vaibhavsingh97** [comment]
@niccokunzmann what i think atleast that we can add just button and pass all the information of speakers to badgeyay and then user can choose the preferred type and background and can generate badge. But this solution will be inconsistent as UI of both eventyay and badgeya differ.
Another soution is that collect some in formation in eventyay only and instead od redirecting we can make use of API and directly generate badge in eventyay.
@pushkalkatara What are your opinion on this?

**Comment by niccokunzmann** [comment]
I think, both is fine. Both require a predefined API which must be described and is binding. What we can not do is the following:
- implement an API without documentation
- use that API from eventyay
This has the folowing problems in the future:
then, when we change the API in badgeyay
- eventyay does not know that and breaks
- it is unclear which versions are compatible in case we would like to recover
- it is unclear, how to add new options in eventyay if you did not develop the new feature in badgeyay

Thus, I propose to do a documentation driven development of the badgeyay API:
- describe which interface we want to use
  - decide where we want to be flexible = not part of the API
  - decide where we make assurances which must not be broken, unflexible = part of the API
- implement this interface

[Inspiration](http://hintjens.com/blog:85)

**Comment by pushkalkatara** [comment]
I would like to collaborate with @vaibhavsingh97 to work on this issue. We would discuss and find a workaround for the above-mentioned issue.

**Comment by pushkalkatara** [comment]
One approach may be : 
1. Fetch required fields from badgeyay and display the fields on the eventyay web page. Like when user clicks on print badge button, all the feilds to be filled by ther user are fetched from badyay on the eventyay [Maybe a dialog box types].
Fetching would make it modular i think, as if badgeyay's fields are changed, automatically it would be fetched to the evenyay without changes.
2. The user selects the details for which badge is to be generated, selects the background etc.
3. this input is fed to the badgeyay's API (yet to be developed) and the API returns the pdf or zip, as selected by the user.

**Comment by vaibhavsingh97** [comment]
@niccokunzmann We can go with @pushkalkatara Approach 😄

**Comment by pushkalkatara** [comment]
@niccokunzmann @gabru-md Can we proceed with the above approach?

**Comment by niccokunzmann** [comment]
Yes, I think, this can work. You do not have to wait for me if you like to try something out.

**Comment by gabru-md** [comment]
Yes it is great! And i definitely believe in what @niccokunzmann said. 
:+1:

**Comment by vaibhavsingh97** [comment]
@niccokunzmann @gabru-md Thanks, we are going by this approach 👍

**Comment by jajodiaraghav** [comment]
Integrating badgeyay with eventyay was the primary goal of this project. This is a priority issue and it would be great if we could resolve this soon :)

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav This is on hault right now. Please see https://github.com/fossasia/open-event-orga-server/issues/4475

**Comment by S2606** [comment]
@vaibhavsingh97 The given issue is in halt for integrating, not for process of creating API. It was halted because then the functionalities were not ok. But now i think we checked all the boxes that are needed for this.

**Comment by kushthedude** [comment]
Out of scope currently, 
see https://github.com/fossasia/open-event-server/issues/4475#issuecomment-499329965
