### ISSUE TITLE
Implement default backgrounds as gallery view and add more choices

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#1467]
Please improve the default backgrounds as follows:
* Take out the white area and FOSSASIA logo. The white area should be implemented separately if needed. Also the standard backgrounds need to be adapted to different image sizes. So, this first version with the white and red logo is no longer suitable
* Instead of a drop down please show a gallery of images on default. Implement this as an expanded area, where the user can switch between list and gallery view.
* Please add more freely licensed backgrounds in good quality to the available choices 

![screenshot from 2018-07-24 19-16-43](https://user-images.githubusercontent.com/1583873/43155069-a569f6d2-8f76-11e8-940c-120aaeb84536.png)

**Comment by abhi40308** [comment]
@mariobehling  I am working on the gallery view

**Comment by ParthS007** [comment]
Looking into it :+1:
