### ISSUE TITLE
User image not stored and shown as expected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#1480]
If a user photo is added it would be expected that is shows up in a circle just like the example. Instead the shape is changed. Reloading the settings page does not show the user photo anymore. It seems it is lost.

![screenshot from 2018-07-24 22-57-14](https://user-images.githubusercontent.com/1583873/43165781-124f20ce-8f95-11e8-87c0-7de0dfbb1d5e.png)

**Comment by abhi40308** [comment]
I am working on this.

**Comment by abhi40308** [comment]
I couldn't seem to find a workaround, so the issue is still open to be claimed. According to my research, image data is being stored in localstorage with the user log in, which needs to be manipulated to store the new user photo so that hitting 'refresh' button doesn't change the image.

**Comment by ParthS007** [comment]
Ping @yashLadha

**Comment by sk9331657** [comment]
@yashLadha  In this issue, actually the problem is that image is not stored but is loaded from Gmail account if user signup using Gmail account, so we need to store the image either in firebase or pg db. I want to solve this issue. Please suggest the changes in approach.

**Comment by sk9331657** [comment]
@mariobehling @ParthS007   Can I work on this ??

**Comment by yashLadha** [comment]
Ember fire is fetching the image from Gmail account but sometimes it is not
getting reflected from firebase, but why to increase the networking latency
when can be done locally

**Comment by sk9331657** [comment]
@yashLadha So like we can store images in local db so that it can be fetched and updated similar to gmail .

**Comment by sk9331657** [comment]
@yashLadha  We can set a default image which can updated as user can sign in using simple email too.

**Comment by rajvaibhavdubey** [comment]
@sk9331657 The image does get stored I checked it but soon after it is updated with the google image, so all we have to do is to remove the google image fetching process coz it fetches image every time we refresh the image instead, it should fetch from the database.
