### ISSUE TITLE
Fix left side design in settings tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#1481]
The settings tab lines in the left sidebar have a number of issues:
* The tab is wider than the image area above
* The lines are very close to the above area in a non-standard way
* Please simplify the area and implement more standard like standard tabs
![screenshot from 2018-07-24 22-57-14](https://user-images.githubusercontent.com/1583873/43165855-3ea75ede-8f95-11e8-8adb-61d159ed3aee.png)

**Comment by ParthS007** [comment]
I am looking into it.
