### ISSUE TITLE
Add radio buttons for "Or" areas/options and only show details once button is chosen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#1484]
In order to simplify the UI, please offer radio buttons for "Or" areas/options and only show details once button is chosen:
* in front of Upload CSV or Enter Details (only show the sections below this once the user has chosen the option)
* in front of Select from default backgrounds or Select from a custom color or Upload Background Image

![screenshot from 2018-07-25 10-35-28](https://user-images.githubusercontent.com/1583873/43189367-b13d6450-8ff6-11e8-9a5d-70a0654d8719.png)

**Comment by ParthS007** [comment]
I am working on this.

**Comment by ParthS007** [comment]
I am working on other Issue so this Issue is open to claim by others :+1:

**Comment by rossoskull** [comment]
I would like to work on this, please assign this to me.

**Comment by rajvaibhavdubey** [comment]
@mariobehling @ParthS007 I am working on this.
