### ISSUE TITLE
Remove Sign In with Facebook from Login options

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#1489]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Facebook has blocked our Badgeyay Developer app due to certain issues.

**Expected behavior:**
Remove the Facebook button from Login Options so that User's time will not be wasted while logging In with the help of Facebook.

**Comment by nishankbhati** [comment]
I want to work on this.

**Comment by ParthS007** [comment]
Yes @nishankbhati, Please go ahead :+1:
