### ISSUE TITLE
Fix Travis tests

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#149]
**I'm submitting a ...**
- [X] bug report

**Current behavior:**

Currently, travis is failing.
https://travis-ci.org/fossasia/badgeyay/builds/278248341?utm_source=github_status&utm_medium=notification

**Expected behavior:**

Travis should run all the tests #147 and succeed.

**Steps to reproduce:**

Please create a pull request to work on this issue and submit commits which fix the errors.

**Comment by gabru-md** [comment]
I can try doing this!

**Comment by vaibhavsingh97** [comment]
@gabru-md Are you still working on this issue? Can i fix it 😄

**Comment by niccokunzmann** [comment]
@vaibhavsingh97 You can work on it, too. Seems like @gabru-md does not share the progress so you can not collaborate.

**Comment by gabru-md** [comment]
@niccokunzmann I could not find a fix for this.
I would love to take @vaibhavsingh97 's help on this matter

**Comment by vaibhavsingh97** [comment]
@niccokunzmann Update: There are some issues with test written for desktop mode. I will fix and send PR and according to @gabru-md travis failing because of phantomJS. We are debugging, we will send another PR fixing the same 😄

**Comment by niccokunzmann** [comment]
Cool. I regard tests as very important so that we do not destroy the work of others and have a hint at what the code does even after many weeks.

**Comment by vaibhavsingh97** [comment]
@S2606 Reopening as it's not completely fixed 😄
