### ISSUE TITLE
Use phantomjs only on travis

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#150]
**I'm submitting a ...**
- [X] feature request

**Current behavior:**

Currently, the phantomjs webdriver is used.
https://github.com/fossasia/badgeyay/blob/development/app/tests/test.py#L10

**Expected behavior:**

- Please add an if based on a useful environment variable to use
  - phantomjs in case of travis
  - firefox/... in case of desktop usage
- add documentation to teh Test Section in the documentation how to use this environment variable
- add the environment variable to travis

You can work on this step by step and create several pull requests if oyu like.

**Comment by vaibhavsingh97** [comment]
@niccokunzmann can i work on it ?

**Comment by niccokunzmann** [comment]
@vaibhavsingh97 sure, you can.

**Comment by vaibhavsingh97** [comment]
@niccokunzmann Can you guide me how can i fix point 2 and point 3 😄

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav Can you please guide me how to fix last two points? I don't think we need to add any environment variable in Travis

**Comment by jajodiaraghav** [comment]
> add documentation to teh Test Section in the documentation how to use this environment variable

Just mention in the /docs that the user will have to setup a file something.env with TRAVIS=True

> add the environment variable to travis

No need. You have handled this well in code!

**Comment by jajodiaraghav** [comment]
@vaibhavsingh97 I think we did a little mistake. The if else statements should be reversed.
A better way to fix this is:
```
if 'LOCAL' in os.environ:
     cls.driver = webdriver.Firefox()
else:
     cls.driver = webdriver.PhantomJS()
````

What do you think?

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav I think the either way is correct. I am detecting the travis environment and you are detecting the local environment. If you want i can go with your solution

**Comment by jajodiaraghav** [comment]
The .env file is not pushed to github, how will travis detect a .env if if there isn't any. I am not sure if the current code will work, I am also not much experienced with Travis.
If you think this will work, do not change it :)
Just add documentation so that the issue can be closed

**Comment by S2606** [comment]
@jajodiaraghav  you are right about it.In next PR .env file should be pushed

**Comment by vaibhavsingh97** [comment]
yeah, My next PR will add `.env` file and documentation
