### ISSUE TITLE
Provide different badge backgrounds for different ticket types

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#153]
Implement the following use case:
1. Use an eventyay file with the list of participants holding different tickets.
2. Import the file and show a list of different ticket types, e.g. Speaker ticket, daily ticket etc.
3. Offer the possibility to upload a different background image for each ticket type (e.g. different colors for the badge) and a tick box "use the standard image"
4. Add a box to name the badge according to the ticket, e.g. the badge should display "Speaker" for all "Speaker Tickets". The users should be able to enter this manually.

**Comment by rupav** [comment]
@mariobehling  
I would like to do this please.

**Comment by gabru-md** [comment]
@rupav go ahead.
just keep us posted

**Comment by pushkalkatara** [comment]
@mariobehling @gabru-md Please provide sample ticket data, types of tickets etc.

**Comment by mariobehling** [comment]
@pushkalkatara @rupav Please check the open event server and create sample data using Open Event: https://github.com/fossasia/open-event-orga-server

It would also be great, if this would work with an exported CVS of Attendees of Eventbrite.

**Comment by abishekvashok** [comment]
@mariobehling can u pls see if we require this?

**Comment by YogeshSharma0201** [comment]
Working on this.
