### ISSUE TITLE
Improve the Permissions Panel in Admin Section

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#1554]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Currently, The permission tab is like this:

![image](https://user-images.githubusercontent.com/24358501/45214360-e6753380-b2b7-11e8-8a2b-81e34047c513.png)

It should be like this:

![image](https://user-images.githubusercontent.com/24358501/45214279-a3b35b80-b2b7-11e8-89a6-9731e749a97c.png)

1. Please request for Admin credentials if you are interested to work on this Issue.

**Comment by sk9331657** [comment]
@ParthS007  I want to work on this issue.

**Comment by sk9331657** [comment]
@gabru-md  Can I work on this??

**Comment by sk9331657** [comment]
@ParthS007  I am working on it .:smile
