### ISSUE TITLE
Custom Color background Issue

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#1561]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

The custom color for background just changes the color of user-defined SVG and then makes the badges. But for the preview of the badge we are showing the color as the badge background. 
This is wrong.

**I am working on this**

@djmgit should we remove the previous changes brought by the PR?
@ParthS007 @yashLadha views? because the current functionality if completely wrong.

**Comment by gabru-md** [comment]
[This is the change](https://github.com/fossasia/badgeyay/pull/1546) that I'm talking about.

**Comment by ParthS007** [comment]
@gabru-md  You can iterate on the Improvement of the feature and make a PR. I hope you understand what I am trying to say.  :+1:

**Comment by gabru-md** [comment]
I am sending a PR removing this feature as of now. since thie is not the way the feature is to be implemented. I will try to experiment on this and will send a PR as soon as I find a way of doing this. In the meanwhile I'm sending a PR removing the customcolor preview for now.
