### ISSUE TITLE
Deploy frontend to surge.sh via travis in each PR

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#1572]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Prs have to pulled and then tested on local environments and then reviewed.

**Expected behaviour:**

Front end can deployed to surge.sh for each PRs and thus testing would be super easy.

Ref: https://guides.emberjs.com/v2.6.0/tutorial/deploying/#toc_deploying-to-surgesh

**Comment by yashLadha** [comment]
This is disabled because surge not allows post request and the landing page sends a request to Heroku. This makes the deployment link not of important as we will not be able to see the changes. 
cc @ParthS007 @gabru-md

**Comment by ParthS007** [comment]
@abishekvashok  We already have deployment script but It doesn't work due to above-mentioned reason. :+1: 
Closing this.
