### ISSUE TITLE
Indicate the Total no of Pages in Pagination

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#1602]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

- Currently, the total no. of pages are not shown in the pagination.

- Please Indicate the Total no of Pages in Pagination

**Comment by YashRE42** [comment]
Hi, I'm new to open source, can I take this issue?

**Comment by rupav** [comment]
Would like to work on this.

**Comment by gabru-md** [comment]
yes sure please go ahead! :D

**Comment by sk9331657** [comment]
@rupav  Are u working on it??  :smile:

**Comment by sk9331657** [comment]
@rupav  Are u still working on it ?? Can I take up this issue??

**Comment by sk9331657** [comment]
@rupav  Ok Thanks
