### ISSUE TITLE
Api secure key in code

### ISSUE THREAD

**Issue by srungta** [fossasia/badgeyay#161]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
The Travis.yml build script has a secret key checked in in code.

**Expected behavior:**
No secrets should be a part of the checked in code.

**Steps to reproduce:**
NA

**Comment by gabru-md** [comment]
What do you propose we can do ?  @srungta

**Comment by srungta** [comment]
@gabru-md We can use an encrypted value as per guidelines here 
https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables 
Filed the bug to ensure this was being followed.
I might have been too hasty to file it without checking with the contributors.
Will close if it is already done.

**Comment by gabru-md** [comment]
Thanks for the link.
Will have a look and let you know

**Comment by vaibhavsingh97** [comment]
@gabru-md @srungta I don't find a need of encrypting the environment-variables. As we don't have anything secret in environment variable that doesn't mean to release in public so we can close this issue.

**Comment by meets2tarun** [comment]
https://github.com/fossasia/badgeyay/blob/development/.travis.yml#L16
This line contains the encrypted code.

@srungta It is necessary to put the encrypted key here to ensure a successful GitHub release.
Yes, one can even do [this](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) but it must be the unencrypted API key of the Admin of the repository and should be unsecured version as of [this](https://github.com/fossasia/badgeyay/blob/development/.travis.yml#L16).
@vaibhavsingh97 
> I don't find a need of encrypting the environment-variables. As we don't have anything secret in environment variable that doesn't mean to release in public so we can close this issue.

The API key is already encrypted and it is needed to encrypted so everyone can't make a Github Release.
For more info: https://blog.fossasia.org/setting-environment-variables-up-in-travis-and-heroku-for-meilix-and-meilix-generator/

**Comment by meets2tarun** [comment]
Feeling of no need, so closing !!
