### ISSUE TITLE
disabling fields after "apply-to-all"

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#1630]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

After apply-to-all is checked, the fields must be disabled.
**I am working on this**

**Comment by sk9331657** [comment]
@gabru-md  Can I proceed with this issue ??  :smile:

**Comment by gabru-md** [comment]
oh yes! sure. It is open for anyone to claim. please do it :)
