### ISSUE TITLE
Have a seperate directory for requirements

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#166]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
We have two text-files requirements.txt and test-requirements.txt. Some packages like gunicorn are only used for production purpose and not dev purpose

**Expected behavior:**
have a seperate directory containing dependencies for dev,prod,test seperately

**Comment by S2606** [comment]
@niccokunzmann @jajodiaraghav @gabru-md Please give your opinion

**Comment by gabru-md** [comment]
Sure go ahead!
:+1:

**Comment by jajodiaraghav** [comment]
Please send a PR 👍

**Comment by gabru-md** [comment]
Closed by #171
