### ISSUE TITLE
Implement Edit badge Functionality

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#1665]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Edit badge Functionality is not present in Backend and Frontend

**Expected behavior:**
The user should be able to edit the badge.

1. Please **open separate Issue** for respective Backend and Frontend Issue.
2. Please Provide the approach for the respective feature in the Issue.

**Comment by gabru-md** [comment]
This issue is up for Codeheat candidates. Claim this issue incase you want to work on this. :D

**Comment by sk9331657** [comment]
@gabru-md What type of edit badge functionality is needed??

**Comment by sk9331657** [comment]
@ParthS007 @gabru-md I am working on it.

**Comment by gabru-md** [comment]
sure please go ahead!

**Comment by rajvaibhavdubey** [comment]
@sk9331657 Are you still working on this ?

**Comment by sk9331657** [comment]
@rajvaibhavdubey  I will start working on it from today . Was busy solving other issues .  :smile: .

**Comment by rajvaibhavdubey** [comment]
Claiming this due to inactivity will send PR within 2 days.
ThankYou :smile:

**Comment by sk9331657** [comment]
@rajvaibhavdubey  If you don't mind can I take up this issue?

**Comment by YogeshSharma0201** [comment]
Working on this due to inactivity.

**Comment by YogeshSharma0201** [comment]
Update: Almost done, will send a pr soon.
