### ISSUE TITLE
Update Installation Docs For Heroku 

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1672]
**I'm submitting a ...**
- [x] feature request

**Current behaviour:**

Outdated installation docs

**Expected behaviour:**

Up-to date docs

**Comment by sk9331657** [comment]
@ParthS007  Can I work on this issue??

**Comment by ParthS007** [comment]
Yes @sk9331657 , Please go ahead :+1:

**Comment by Ananthavijay** [comment]
https://github.com/fossasia/badgeyay/pull/1682
https://github.com/fossasia/badgeyay/pull/1683

updated install instructions for Heroku.
@ParthS007 check it.
Thanks,
Anantha Vijay.M
