### ISSUE TITLE
Add Screenshots in Installation docs for linux/unix using Virtualenv

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1679]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce:**

**Comment by rajvaibhavdubey** [comment]
I'm working on this

**Comment by ParthS007** [comment]
@rajvaibhavdubey  What's the status of this Issue?

**Comment by rajvaibhavdubey** [comment]
@ParthS007 I'm working on this issue.

**Comment by sk9331657** [comment]
@gabru-md  @ParthS007  I am now working on it.

**Comment by rajvaibhavdubey** [comment]
@sk9331657 Bro I'm already working on this, i've been busy due to my exams.
Thankyou 😄

**Comment by sk9331657** [comment]
@rajvaibhavdubey  Ok Bro. :smile:

**Comment by ParthS007** [comment]
Closing this . Not needed as Video is added for this :+1:
