### ISSUE TITLE
Login using Google and Twitter not working because Auth callback is not set to localhost in Firebase console

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1689]
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

Login is not possible as localhost is not present in auth callback .

**Expected behaviour:**

Login should be working 
@ParthS007  @gabru-md  Url needs to be added in fire base console else we can only test application using general login in local setup.

**Comment by ParthS007** [comment]
@sk9331657 Localhost is already present in Authorised Domains in Firebase console.
Closing this :+1:
