### ISSUE TITLE
Accepting only csv files as input

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1690]
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

Earlier user was able to select any type of file but user should only add csv file . 
![screenshot from 2018-09-14 08-16-36](https://user-images.githubusercontent.com/17084322/45527034-5a9f6200-b7f7-11e8-9dfc-6c8c19ce64c0.png)

**Expected behaviour:**

Now Only CSV files are accepted. 

![screenshot from 2018-09-14 08-20-23](https://user-images.githubusercontent.com/17084322/45527073-799df400-b7f7-11e8-8102-df86f4869883.png)

**Comment by rajvaibhavdubey** [comment]
@phoenixking25 there is already an opened PR for this issue.
Thanks :smile:
