### ISSUE TITLE
Improving Toggling Button  for Card

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1692]
**I'm submitting a ...**
- [x] feature request

**Comment by abishekvashok** [comment]
Can you explain more about the issue pls?

**Comment by sk9331657** [comment]
@abishekvashok  @gabru-md  @ParthS007  Have a look at new toggler.
![ezgif com-optimize](https://user-images.githubusercontent.com/17084322/45563438-f918db00-b86a-11e8-9722-ee3583a21246.gif)

**Comment by rajvaibhavdubey** [comment]
@sk9331657 the left component moves a bit up on toggling the button, there's an issue created for the same try and see if u can fix the same .
