### ISSUE TITLE
Add none option for Background

### ISSUE THREAD

**Issue by avsingh999** [fossasia/badgeyay#1697]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
There should be an none option for background, beacuse when we select default backgound anyone, but when I want to set image background then in default background or custom color should be an none option

**Expected behaviour:**

**Steps to reproduce:**

**Comment by rajvaibhavdubey** [comment]
@avsingh999 are you working on this, Or can I take this up?

**Comment by avsingh999** [comment]
yes  you can @rajvaibhavdubey

**Comment by ParthS007** [comment]
Not relevant as of now. Closing this :+1:
