### ISSUE TITLE
Profile pic not show with username

### ISSUE THREAD

**Issue by avsingh999** [fossasia/badgeyay#1700]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
Profile pic  not show with username 
![badgeprofile](https://user-images.githubusercontent.com/25536022/45558033-8a348580-b85c-11e8-8d96-ba6e7360e2d0.PNG)

**Expected behaviour:**
should b show profile pic with my username 

**Steps to reproduce:**

**Comment by sk9331657** [comment]
@avsingh999  It is happening because you have used email and not Gmail or twitter login system to login .

**Comment by avsingh999** [comment]
@sk9331657  I have used gmail

**Comment by avsingh999** [comment]
@sk9331657 can you post  a screenshot

**Comment by ParthS007** [comment]
@avsingh999 It takes time to show the Profile pic and is fetched with the help of Firebase. Please try to log in again and the image will be shown.

Closing this :+1:
