### ISSUE TITLE
On clicking 'User Input Guide', it should open a new tab.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#1703]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Currently if I have filled some details, say `Badge name`, and then clicked `User Input Guide` icon, I am directed to the page on the same tab. And returning back leads to lost info - previously entered `Badge name`. 
**Expected behaviour:**

On clicking `User input guide`, a new tab should be opened instead.

---
Someone else can take this up issue.

**Comment by Ananthavijay** [comment]
@rupav made a pr here : https://github.com/fossasia/badgeyay/pull/1705

**Comment by Ananthavijay** [comment]
@abishekvashok The issue isnt complete yet I think.
Because it again opens in the same tab
