### ISSUE TITLE
Fixing the Preview Badge Position for Desktops,Pc

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1704]
**I'm submitting a ...**
- [x] Feature request 

**Current behaviour:**

Currently  Badge is fixed to left 
![screenshot from 2018-09-14 21-43-44](https://user-images.githubusercontent.com/17084322/45584146-7df80900-b8ec-11e8-947d-2d813e91cd0f.png)

So when  user scrolls he doesn't come to know about changes in badge , user as to go up to see changes,  instead if position remains fixed for card then user  can view changes.

Currently :
![screenshot from 2018-09-15 00-14-26](https://user-images.githubusercontent.com/17084322/45584181-e3e49080-b8ec-11e8-83b6-5880da192c49.png)

**Expected behaviour:**

Similar to  right div which will provide preview:

![image9](https://user-images.githubusercontent.com/17084322/45584256-ec899680-b8ed-11e8-9341-a6cf4e1e9c9b.gif)

**Comment by ParthS007** [comment]
Yes @sk9331657 , It seems good and You can go ahead and make a PR for it :+1:

**Comment by sk9331657** [comment]
![ezgif com-optimize 1](https://user-images.githubusercontent.com/17084322/45596189-ba536400-b9d5-11e8-90f3-334940f9d3ab.gif)

@ParthS007  @mariobehling @gabru-md  How is it?? Any improvements in it??

**Comment by sk9331657** [comment]
@ParthS007 @gabru-md   Can I use ember component listeners for this ??

**Comment by sk9331657** [comment]
@ParthS007 I have almost implemented, I will be creating PR by tomorrow.
