### ISSUE TITLE
collapse select field in Customize Badge Layout

### ISSUE THREAD

**Issue by avsingh999** [fossasia/badgeyay#1709]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
![badgecollapse](https://user-images.githubusercontent.com/25536022/45606338-fb915580-ba61-11e8-938c-cdd7c69f3012.png)

**Expected behaviour:**

**Steps to reproduce:**

**Comment by avsingh999** [comment]
I want to work on it

**Comment by sk9331657** [comment]
@avsingh999  What improvements are u thinking to implement??

**Comment by rajvaibhavdubey** [comment]
@avsingh999 Explain the issue a bit more, like what problem is caused by this bug?
