### ISSUE TITLE
Create Badges stuck at 40%

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1718]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
When we create the badges the progress bar gets stuck at 40%
**Expected behaviour:**

The badges would be created successfully
**Steps to reproduce:**
Go to [http://badgeyay.com/create-badges](http://badgeyay.com/create-badges) 
Fill in the details
Create badge
See the bug
![40](https://user-images.githubusercontent.com/33062425/45757395-df97da80-bc40-11e8-8620-1dc2c078b1ca.png)
Discussion needed @ParthS007 @gabru-md @yashLadha @sk9331657

**Comment by samagragupta** [comment]
Can you share the console log ?? @rajvaibhavdubey

**Comment by rajvaibhavdubey** [comment]
@samagragupta 
![40console](https://user-images.githubusercontent.com/33062425/45841442-7e066780-bd37-11e8-967d-cefba30e4b3a.png)

**Comment by sk9331657** [comment]
@rajvaibhavdubey  Are you still facing this issue??

**Comment by ParthS007** [comment]
@rajvaibhavdubey @sk9331657 This needs to be fixed asap.
