### ISSUE TITLE
Accessing private endpoints should redirect to home page.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#1719]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Accessing endpoints like `http://badgeyay.com/my-badges`, if one is not logged in, shows loading and then a blank page. 
**Expected behaviour:**

Instead we should redirect the user to home page.
**Steps to reproduce:**
Go to [badgeyay](http://badgeyay.com/), and logout if you are currently logged in and then go to [my-badges](http://badgeyay.com/my-badges) page.

---
_Working on it_

**Comment by ParthS007** [comment]
@rupav Please update the status of the Issue. :+1:
