### ISSUE TITLE
Radio buttons merge into drop down menus when screen width is reduced while create badges

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/badgeyay#1720]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Radio buttons merge into drop down menus when screen width is reduced while create badges.

**Expected behaviour:**
They should remain separate

**Steps to reproduce:**
Open create badges section and reseize the screen

**Screenshot**
![screen shot 2018-09-19 at 8 06 41 pm](https://user-images.githubusercontent.com/31539812/45760590-0e657f00-bc48-11e8-9a0f-3e14d114a009.png)

**Comment by samagragupta** [comment]
At what resolution are you opening the site? @neeraj3029

**Comment by rajvaibhavdubey** [comment]
@neeraj3029 Are you working on this?

**Comment by ParthS007** [comment]
@rajvaibhavdubey You can work on it :+1:
