### ISSUE TITLE
frontend local setup not working.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#1721]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Not able to see the website. Blank page after loading.
![screenshot from 2018-09-19 20-52-29](https://user-images.githubusercontent.com/20624380/45763769-d01f8e00-bc4e-11e8-9eb2-04a65df98fae.png)

**Expected behaviour:**

Should start, after `ember serve`
**Steps to reproduce:**
Follow instructions for frontend setup, then run `ember serve`, and head to `localhost:4200`

**Comment by sk9331657** [comment]
@rupav  Try in incognito mode and make sure that back-end server is working.

**Comment by rupav** [comment]
thanks, its solved ✌

**Comment by prashant1093** [comment]
<img width="904" alt="Screenshot 2019-05-10 at 7 15 21 PM" src="https://user-images.githubusercontent.com/43171891/57532038-7cd28b00-7358-11e9-870f-f745508dd327.png">

I trie in incognito mode as well that does not work.

**Comment by rajvaibhavdubey** [comment]
Show the console output please @prashant1093

**Comment by prashant1093** [comment]
@rajvaibhavdubey 
<img width="1680" alt="Screenshot 2019-05-11 at 10 39 17 AM" src="https://user-images.githubusercontent.com/43171891/57565305-1477be00-73d9-11e9-921d-389082f9d654.png">

**Comment by rajvaibhavdubey** [comment]
@prashant1093 I meant the browser console, also it's working fine for me.

**Comment by prashant1093** [comment]
@rajvaibhavdubey sorry for delayed response. This might be some easy error
<img width="554" alt="Screenshot 2019-05-15 at 3 15 19 PM" src="https://user-images.githubusercontent.com/43171891/57766188-8ecf7780-7724-11e9-8e2b-3e6a4af11138.png">
 (I don't understand front end side of things much.)
