### ISSUE TITLE
Deploying badgeyay to AWS-EC2

### ISSUE THREAD

**Issue by prabhupant** [fossasia/badgeyay#1725]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce:**
I'd like to work on this feature and deploy badgeyay on AWS, and make the required changes or additions to the installation docs as well

**Comment by samagragupta** [comment]
There is already a docker image i guess for the google app engine, so we can pull the same image in the ec2 instance as well. Do you have any other ideas, in the implementing the same though?
