### ISSUE TITLE
Return key should be able to submit the new password set form.

### ISSUE THREAD

**Issue by phoenixking25** [fossasia/badgeyay#1728]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Nothing happens on pressing return key on the new password set form.

**Expected behaviour:**

Pressing the return key should be able to submit the form by default and arrow keys should help to navigate between submit and cancel button.

**Steps to reproduce:**
New User Sign up

**Comment by sk9331657** [comment]
@phoenixking25  Are u solving this issue??

**Comment by phoenixking25** [comment]
No i created it for others!

**Comment by sk9331657** [comment]
@phoenixking25 So I shall I work on it because you claimed it??

**Comment by ParthS007** [comment]
Closing this. Not required as of now :+1:
