### ISSUE TITLE
Scaling up

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#173]
**Current behavior:**

For some time now, the progress on badgeyay is going on.
New maintainers were added: S2606,  jajodiaraghav, gabru-md

**Expected behavior:**

For the Community to scale up, I can not really add new maintainers as I do not know who else has contributed.
@S2606,  @jajodiaraghav, @gabru-md and @meets2tarun who else has contributed to this repository and should be named a maintainer according to [the Maintainers Section](https://github.com/fossasia/badgeyay#maintainers)?
Could each of you name at least one person to add as a maintainer?

**Steps to reproduce:**

**Comment by jajodiaraghav** [comment]
Hi Nicco

I think @djmgit @vaibhavsingh97 and @pushkalkatara have shown good work recently :)

**Comment by S2606** [comment]
@nanspro @vaibhavsingh97 @pushkalkatara ....

**Comment by gabru-md** [comment]
@nanspro @vaibhavsingh97 @djmgit :+1:

**Comment by niccokunzmann** [comment]
Thanks, you can view the new list here: @fossasia/badgeyay-admin

**Comment by niccokunzmann** [comment]
Hi @nanspro, @vaibhavsingh97, @pushkalkatara and @djmgit,

you now have the rights to merge other peoples' pull requests. If you like to take on the role of a maintainer, please read the [Maintainers Section](https://github.com/fossasia/badgeyay#maintainers). It can be edited if you find out new things to keep the project alive and welcoming for new and old contributors.

**Comment by pushkalkatara** [comment]
Thank you @niccokunzmann @jajodiaraghav @S2606 @gabru-md. :D Loving open source

**Comment by niccokunzmann** [comment]
Closing this. Nominations of maintainers are always open. Please use this right to give others the opportunity who do not know about it.
