### ISSUE TITLE
Add user login via facebook

### ISSUE THREAD

**Issue by prabhupant** [fossasia/badgeyay#1734]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

no user login option via Facebook

**Expected behaviour:**

**Steps to reproduce:**
I'd like to work on this. It might take some time though :sweat_smile:

**Comment by moulikcipherX** [comment]
@prabhupant If you are are not doing then I can work on this issue??

**Comment by ParthS007** [comment]
@prabhupant Closing this Issue as It is not relevant to the present stage. We can add this at a later stage. Please have a look at already open Issues.
