### ISSUE TITLE
Unnecessary Redirecting of Requirement File 

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/badgeyay#174]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

There are lots of unnecessary redirecting of [requirement](https://github.com/fossasia/badgeyay/blob/development/requirements.txt) file which is needed to fulfill the requirement to run the app.

**Expected behavior:**

Requirement file should be a single file.
Look into the links to check out how to proceed further to solve the issue:
https://blog.fossasia.org/generate-requirement-file-for-python-app-for-meilix-generator/
https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/56

**Steps to reproduce:**
NA

**Comment by S2606** [comment]
@meets2tarun There is a reason for this. We had two requirements.txt file,one for production and other for testing.Now in development packages like gunicorn are of no use. So i found this solution of having these requirements directed as they help in tracking dependency packages easily. Also projects in FOSSAsia like open-event-orga-server are using the same ideology
