### ISSUE TITLE
Making Top Navigation Bar Fixed in case of scroll down

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1746]
**I'm submitting a ...**
- [x] feature request

**Current behaviour:**

![screenshot from 2018-10-02 11-04-28](https://user-images.githubusercontent.com/17084322/46332885-c9741c00-c63b-11e8-8053-8f3c7b856bf5.png)
Currently , the top navigation bar remains on the top of page . We can make it fixed similar to badge.

**Expected behaviour:**

![screenshot from 2018-10-02 11-04-28](http://cdn2.hubspot.net/hub/327485/file-2557417613-gif/Designers-Hubspot-v2/Blog_Images/2015/hatfield-animated-header.gif?t=1460761493037&width=1000)

I want to work on this issue.
@ParthS007  @gabru-md What are you suggestions??

**Comment by ParthS007** [comment]
Not needed. Closing this.
