### ISSUE TITLE
Readme Improvement

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/badgeyay#175]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

A minor fix in the [README.md](https://github.com/fossasia/badgeyay/blob/development/README.md) 

**Expected behavior:**

- [x] Branches are very important for a repository. Need of a section with an anchor link which describes the branch-policy. [link](https://github.com/fossasia/open-event-webapp#issue-and-branch-policy)
- [x] A section of describing the license of use-case of the repository under FOSSASIA. (link)(https://github.com/fossasia/open-event-webapp#license)
- [x] The technologies you are using in the repository and how it works [link](https://github.com/fossasia/meilix-generator#technologies-used).
- [x] Few people have slow internet connection so a gif include in the README.md is not a bad idea.
- [ ] A rule which includes updating the progress, so if the assignee is not updating the progress, other can carry out the job.

Look into the repository of which is the links are attached and further you can give your own idea and contribute.

**Steps to reproduce:**
NA

**Comment by vaibhavsingh97** [comment]
@meets2tarun Can we break this into small sub-issues for point 3 and 4 for `new-comers`?

**Comment by meets2tarun** [comment]
@vaibhavsingh97 Go for it!

**Comment by vaibhavsingh97** [comment]
@meets2tarun Readme now alreday have link to Youtube video, we still need point 4?

**Comment by ParthS007** [comment]
@meets2tarun we can have a rule such that any assignee will have to update the progress in  every 2 days , if he is facing problem then others can work on it . Your views ?

**Comment by ParthS007** [comment]
@meets2tarun what should be in gif ?

**Comment by gabru-md** [comment]
Gif must be a walkthrough of the application.

**Comment by ParthS007** [comment]
Means it will have what we have in YouTube video.Right ?

**Comment by meets2tarun** [comment]
As I mentioned that everyone doesn't have a fast internet connection, so basically gif is for those people only.

**Comment by meets2tarun** [comment]
@ParthS007 
I mean to state that if he is facing difficulty or not able to proceed further or not working on the task although the task has been assigned to him, then a rule that after a certain interval of time that person will dissociate from the task or something like that.

**Comment by ParthS007** [comment]
Yes, agreed.I am saying the same thing but time interval given depends on issue' complexity which we will have to discuss.Your views @gabru-md @vaibhavsingh97

**Comment by ParthS007** [comment]
I am working on gif part @meets2tarun.

**Comment by meets2tarun** [comment]
We need to solve the rest of the checkpoint.

**Comment by rupav** [comment]
@meets2tarun @vaibhavsingh97  I would like to add license of use-case of the repository under FOSSASIA in the readme by editing this https://github.com/fossasia/open-event-webapp#license as mentioned.
