### ISSUE TITLE
PDF file generated not correct

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1756]
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

After you successfully create the badge, download the pdf .

**Expected behaviour:**

The PDF should be proper, the bottom sections get repeated.
Normally no section should get repeated and a single badge should be available

**Steps to reproduce:**
- Create the badge.
- Download the badge
- Observe the badge
![pdf](https://user-images.githubusercontent.com/33062425/46442260-a1450400-c786-11e8-96e1-bf3982c1701d.png)

@ParthS007 @gabru-md @yashLadha How does the pdf making process work exactly, If you could guide me a little bit, it would be great.

**Comment by rajvaibhavdubey** [comment]
@ParthS007 @yashLadha @gabru-md I need help with this, I've got the exact working of the process but cannot seem to notice the bug.
Thankyou :sweat:

**Comment by yashLadha** [comment]
The logic to remove this bug is to stop the iteration of the loop when the data is completely parsed. @rajvaibhavdubey  and send no text in remaining. This will remove the default text from the SVG template. @rajvaibhavdubey

**Comment by rupav** [comment]
@yashLadha @rajvaibhavdubey can I give it a try, if you are not doing this anymore ?

**Comment by rajvaibhavdubey** [comment]
@rupav Yeah sure :smile:

**Comment by rupav** [comment]
@rajvaibhavdubey please review the attached PR. Thanks :)
