### ISSUE TITLE
Adding Default Picture for User Incase Signup is done using email instead of Gmail or twitter

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1759]
**I'm submitting a ...**

- [x] feature request

**Current behaviour:**

![screenshot from 2018-10-04 23-27-52](https://user-images.githubusercontent.com/17084322/46493136-271b8a80-c82d-11e8-98fc-ac737d324c97.png)

**Expected behaviour:**

**Steps to reproduce:**
Signup Using Email and go to my settings

Will Work on it:
Yes

**Comment by ParthS007** [comment]
@sk9331657 Please update the status :+1:

**Comment by ParthS007** [comment]
@sk9331657 Update Please.

**Comment by sk9331657** [comment]
Closing Since Images is working currently .
