### ISSUE TITLE
Update icon of Badgeyay

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1763]
**I'm submitting a ...**
- [x] feature request

**Current behaviour:**

Badgeyay is currently using the icon of loklak

**Expected behaviour:**

It should have an icon of its own.

**Comment by ParthS007** [comment]
@rajvaibhavdubey Update Please.

**Comment by ParthS007** [comment]
@rajvaibhavdubey  Update Please.
