### ISSUE TITLE
BUG : signup issue for new members

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#1765]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

When I run the project locally and try to sign up for an email address, if the user is not yet registered on the system then the system correctly signs him/her up for the same but it produces two warnings, 
"User with the email already exists"
"Signup successful"

Expected results should be: If the signup is successful then there should be no "User already exists warning". 

This issue is free to be claimed by anyone who wants. 
In case you need any help please drop a comment below in this thread.

**Comment by gabru-md** [comment]
![badgeyaybug](https://user-images.githubusercontent.com/25414121/46595278-2fa5e680-caf5-11e8-8b9b-ae8d9250ba25.png)

here is the screenshot of the same where the server responds with a "user already exists", but the signup still shows successful.

This seems to be a frontend issue, but in case of any server-side issue, we can discuss and then resolve this.

cc : @rupav  @prabhupant @ParthS007 @yashLadha

**Comment by rupav** [comment]
I would like to claim this.

**Comment by gabru-md** [comment]
cool, please go ahead with this task, and keep us posted in case you need any help or would like to discuss about it.
thanks

**Comment by pandyamarut** [comment]
@gabru-md By any chance if this issue is still there to be work upon. 
Please assign it to me.

**Comment by rupav** [comment]
Working on it, will submit a PR positively by Sunday.

**Comment by pandyamarut** [comment]
@rupav 
Sounds great.

**Comment by rupav** [comment]
This issue is not reproducible anymore @gabru-md .

**Comment by sk9331657** [comment]
@ParthS007  @gabru-md  This one is fixed, so can be closed.
