### ISSUE TITLE
Badge editing not working

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1767]
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

On the my-badges page, if a user tries to edit his existing badges, it doesn't work.

**Expected behaviour:**

People would get to easily edit their existing badges

**Steps to reproduce:**
- Create a badge
- Go to my-badges
- Edit a badge
- See the bug

**Comment by ParthS007** [comment]
@rajvaibhavdubey  There is #1665 already open for the same.
