### ISSUE TITLE
Change icon for crop image

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1771]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Icon for crop image is same as image deletion.

**Expected behaviour:**

![crop](https://user-images.githubusercontent.com/33062425/46672598-7bd85000-cbf5-11e8-9cf0-634258c5ebff.png)

**Steps to reproduce:**
- Go to create badges.
- Upload a custom image. 
- See the bug

**Comment by ujjwal-madan** [comment]
@rajvaibhavdubey I would like to work on this.

**Comment by ujjwal-madan** [comment]
@rajvaibhavdubey It was not mentioned earlier and I thought it was open for everyone.
I have changed the crop icon image if you are okay with it should I submit the PR.
