### ISSUE TITLE
Add  technologies to README file 

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#178]
**I'm submitting a ...**
- [x] feature request

**Current behavior:**
There is no technology section in the Readme

**Expected behavior:**
Readme should have  technologies we are using in the repository and how it work.

**Steps to reproduce:**
- Edit the README file
- Add technology information just like [this](https://github.com/fossasia/meilix-generator#technologies-used).

**Comment by ParthS007** [comment]
Working on this @vaibhavsingh97 .

**Comment by vaibhavsingh97** [comment]
@ParthS007 This is issue is for first timers who are new to open source 😄

**Comment by ParthS007** [comment]
ohkk, but I have talked with @gabru-md regarding this.

**Comment by ParthS007** [comment]
@vaibhavsingh97 can I proceed ?

**Comment by vaibhavsingh97** [comment]
@ParthS007 As dicussed in #175 , this issue is for first timer only. You can pickup any issue from there and solve except this 😄 . We want that more people join onboard 👍

**Comment by kvaluruk** [comment]
Is this still open? Can I work on it?
