### ISSUE TITLE
Logged In user when routes to '/login' makes them logout and cannot Login back.

### ISSUE THREAD

**Issue by satyasashi** [fossasia/badgeyay#1791]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
When a user logged in, and hits back button or routes to 'localhost:4200/login', they get logged out.

**Expected behaviour:**
When a user logged in and authenticated, and tries to route to 'localhost:4200/login' they must be redirected to home page which was supposed to be visible as soon as they login.
Instead it makes them Logout and they cannot Log back in. It gives Error: "Log In Failed ! Please try again"

**Steps to reproduce:**
1. Go to '/login'
2. Pass Credentials
3. Now go back to login page or '/login'
4. Now you are logged out.
5. Try 'Login'

**Comment by ujjwal-madan** [comment]
@satyasashi 
It seems to work fine, going back to login page is redirecting to homepage only.

**Comment by satyasashi** [comment]
@ujjwal-madan Oh! But it was not working for me and I tried it twice. I'll make sure once again and I'll close this issue.

**Comment by satyasashi** [comment]
@ujjwal-madan Yes it is working now. It's funny why that happened yesterday. Closing this issue.
