### ISSUE TITLE
New Password placeholder empty in Change Password Form

### ISSUE THREAD

**Issue by ujjwal-madan** [fossasia/badgeyay#1795]
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

![screen shot 2018-10-13 at 9 53 14 pm](https://user-images.githubusercontent.com/26686257/46907707-4bb1e980-cf34-11e8-97af-4033bd7591ae.png)

**Expected behaviour:**

New Password should also have a place holder like Verify Password

**I am working on this**

**Comment by amrs-tech** [comment]
Can you please assign it to me, for me to try?
Because I want to contribute to this issue. And can you please tell me how to find the file because I find only the form validation not it's html content ?
