### ISSUE TITLE
Block Sign Up button, until atleast 6 characters password is entered.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#1797]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Currently, on clicking `Sign Up`, a request is send to the backend, even if we have a less than 6 characters password. 

![image](https://user-images.githubusercontent.com/20624380/46916624-ba498280-cfda-11e8-94dd-be7573bd35d4.png)

**Expected behaviour:**

We should disable the form, and gives user an info while typing the password about the limit.
**Steps to reproduce:**
Go to http://badgeyay.com/signup, and register with password less than 6 characters.

_I am working on it_

**Comment by rupav** [comment]
I am working on it :)

**Comment by sk9331657** [comment]
Ok

**Comment by sk9331657** [comment]
I will create new issue.

**Comment by ParthS007** [comment]
@rupav Update Please.

**Comment by rupav** [comment]
Implemented this, just waiting for #1817 to be merged, so that I can test.
