### ISSUE TITLE
Include 'Would you like to work on this issue?' in issue template.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#1798]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

It's not included currently like in other fossasia projects.

**Expected behaviour:**

This line should be included as the last statement in the issue template.
Refer other fossasia projects (like susi_chromebot) templates for reference.

Any newcomer/beginner can claim it.

**Comment by ujjwal-madan** [comment]
@rupav I would like to work on it

**Comment by rupav** [comment]
sure, go ahead 👍
