### ISSUE TITLE
set cursor value to pointer in settings section.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#1799]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Currently cursor is not set set to `pointer` while hovering over `Account` or `Password` link.
It should be instead, as they are links to new sections.
![image](https://user-images.githubusercontent.com/20624380/46916874-41e4c080-cfde-11e8-9eba-6675e308ea4a.png)

**Expected behaviour:**

In my opinion it should be set to `pointer` value on these buttons.

**Steps to reproduce:**
Login and then go to
http://badgeyay.com/settings .
Then try hovering over `Acoounts` or `Password` areas.

I am not working on it. Anyone can claim it. @ujjwal-madan @sk9331657

**Comment by abishekvashok** [comment]
Still not fixed

**Comment by abishekvashok** [comment]
Flagging as first-timers-only

**Comment by raufabr** [comment]
Is this open? I would like to have a go if it is open.

**Comment by rajvaibhavdubey** [comment]
@raufabr Sure :+1: , Good Luck

**Comment by BhuwanChandra** [comment]
Is this still open? I would like to work on it.

**Comment by masterchef2209** [comment]
I would like to have a try on this issue

**Comment by kushthedude** [comment]
> I would like to have a try on this issue

Go on @masterchef2209
