### ISSUE TITLE
PDF file generated doesn't have the applied font color.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#1801]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

PDF file generated doesn't have the applied font color.

**Expected behaviour:**

The generated PDF should be same as the preview.

**Steps to reproduce:**
After you successfully create the badge (make sure you change the font color), download the pdf .

_I am working on it._

**Comment by rupav** [comment]
#1756 is correlated to this issue - as it too deals with the wrong PDF generation. I will work on the font correction part only. cc @rajvaibhavdubey

**Comment by ParthS007** [comment]
@rupav Update Please.

**Comment by yashLadha** [comment]
Can you please share the badge link or a screencast showing the bug.

**Comment by ParthS007** [comment]
@rupav Update Please.

**Comment by rupav** [comment]
@ParthS007 please see the PR attatched.
