### ISSUE TITLE
Some of the site map options are not visible upon login

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1806]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Screenshots**
Before Login
![screenshot from 2018-10-15 18-04-21](https://user-images.githubusercontent.com/33062425/46951318-41632d00-d0a5-11e8-96b5-09c29ce52811.png)

After Login
![screenshot from 2018-10-15 18-04-54](https://user-images.githubusercontent.com/33062425/46951333-49bb6800-d0a5-11e8-8f50-bc0beea7af63.png)

**Steps to reproduce:**
- Logout
- Go to sitemap
- Login
- Go to sitemap
- Notice the difference

**Comment by rajvaibhavdubey** [comment]
I'm working on this.

**Comment by ParthS007** [comment]
@rajvaibhavdubey Update Please.

**Comment by ParthS007** [comment]
@rajvaibhavdubey Update Please.
