### ISSUE TITLE
use envparse or other utility like in open-event instead of harcoded variables.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#1810]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Currently before sending a PR, I have to switch back to `ENV=PROD` from `LOCAL`, making it hard for the development process. This can be cumbersome, if other variables are too set this way for my local setup, and needs to be reverted back to original for sending the PR.

**Expected behaviour:**

This can be avoided, if we use [envparse](https://github.com/rconradharris/envparse) to parse the environement variables. This way it will fetch the env variable that I have set locally on my PC, instead in the project. This is also a good practice as per one of the 12 principles of `12 factors app`.

@yashLadha @gabru-md @ParthS007 your views on this?

_I would like to work on this._

**Comment by sk9331657** [comment]
@rupav  It is a great idea we can also set verification email domain using this.

**Comment by ParthS007** [comment]
@rupav Sound good to me. Please go ahead.

**Comment by gabru-md** [comment]
@rupav the issue is a certain solid one. You can proceed with it and create a PR
cheers!

**Comment by ParthS007** [comment]
@rupav Please update
