### ISSUE TITLE
Using Env variable to send verification email with address starting with 127.0.0.1 instead of badgeyay.com

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1811]
**I'm submitting a ...**
- [x] feature request

**Current behavior:**

Currently, during local development verification email contains verification email starting from badgeyay.com instead it should be replaced with 127.0.0.1 by parsing the ENV variable from config.

**Steps to reproduce:**

Will like to work in it ??
### Yes

**Comment by ParthS007** [comment]
Not relevant. Please look at other open Issues.
