### ISSUE TITLE
Password Strength Feature on settings/passwords tab

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1823]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Feature Details**
Password Strength Feature on settings/passwords tab

I'm working on this

**Comment by sk9331657** [comment]
This is a child issue of password strength on signup

**Comment by rajvaibhavdubey** [comment]
Have you added this feature in the settings/password tab?

**Comment by sk9331657** [comment]
Nopes, go ahead. :smile:

**Comment by sk9331657** [comment]
Nopes, go ahead. :smile:
