### ISSUE TITLE
Badge preview not working correctly

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1833]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

The default red_futuristic backround is not shown up when opening create-badges page.

**Expected behaviour:**

Badge preview should work normally

**Steps to reproduce:**
- Go to Create-badges
- See the badge preview

**Screenshots**

![screenshot from 2018-10-18 19-39-26](https://user-images.githubusercontent.com/33062425/47162426-8be8e180-d311-11e8-8159-05a880a3ed98.png)

Error from console

![screenshot from 2018-10-18 20-07-02](https://user-images.githubusercontent.com/33062425/47162451-9acf9400-d311-11e8-8c47-e62c3028d05d.png)

**Comment by sk9331657** [comment]
@rajvaibhavdubey Try to reload and make sure your branch is up to date with fossasia development

**Comment by rajvaibhavdubey** [comment]
@sk9331657 on localhost, it's working correctly. But try to open on badgeyay.com,on the preview badge area u will see white screen, and also open the console to see the error.
:sweat_smile:

**Comment by sk9331657** [comment]
@rajvaibhavdubey  Update issue with title Badge preview not working correctly on badgeyay.com
