### ISSUE TITLE
User should be able to click on the labels to toggle options while creating badges.

### ISSUE THREAD

**Issue by YogeshSharma0201** [fossasia/badgeyay#1834]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
Users have to click on the checkbox to toggle options.

**Expected behaviour:**
User should also be able to click on the labels of the options to toggle them.

![screenshot from 2018-10-18 20-09-10](https://user-images.githubusercontent.com/21025052/47162554-cb173280-d311-11e8-9989-38ad79d234b7.png)

**Comment by ParthS007** [comment]
Not relevant. Please look at other open Issues. Thanks for opening the Issue. :+1:
