### ISSUE TITLE
Preview toggle position not same on page change.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#1846]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

![screenshot from 2018-10-24 17-42-42](https://user-images.githubusercontent.com/20624380/47429603-84638580-d7b4-11e8-9997-ebe5000ca9d2.png)

![screenshot from 2018-10-24 17-49-25](https://user-images.githubusercontent.com/20624380/47429855-2e431200-d7b5-11e8-84c2-c1fb5bd9b963.png)

Rather toggle should be on, if we can see preview.

![screenshot from 2018-10-24 17-46-29](https://user-images.githubusercontent.com/20624380/47429699-c1c81300-d7b4-11e8-8e43-80043ca9b450.png)
Rather toggle should be off, if we cant see preview.

**Steps to reproduce:**
1) Go to http://badgeyay.com/create-badges
2) Toggle off the preview
3) Go to My Badges section using UI.
4) Click on Create Badges, and observe the toggle position (incorrect).

**Would you like to work on the issue?**

Yes.

**Comment by parammittal16** [comment]
@rupav can i work on this ?

**Comment by rupav** [comment]
Yes you can @parammittal16 .

**Comment by sk9331657** [comment]
@rupav  I am working on it now.
