### ISSUE TITLE
Implementing Font Color  Selection on FrontEnd

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1853]
**I'm submitting a ...**
- [x] feature request

**Would you like to work on the issue?**

Yes

**Comment by rajvaibhavdubey** [comment]
#1592 is already created for the same.
Thankyou :smile:

**Comment by sk9331657** [comment]
@rajvaibhavdubey  I know that actually , I am breaking the issue to smaller issues . It will make earlier to get reviewed.
