### ISSUE TITLE
Font-size appearing to be extra large

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1862]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Font-size appearing to be extra large

**Steps to reproduce:**
- Go to create-badges on badgeyay.com.

**Screenshots**

![screenshot from 2018-11-19 16-10-10](https://user-images.githubusercontent.com/33062425/48701923-a31f3580-ec15-11e8-9e58-c599024caf4d.png)

**Would you like to work on the issue?**

Yes

**Comment by parammittal16** [comment]
@rajvaibhavdubey  can i work on this ?

**Comment by rajvaibhavdubey** [comment]
I'm working on this.
