### ISSUE TITLE
make Makefile - start development serve and application with a single command.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#1864]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Currently to run the application (locally), I need to open 1 terminal for development server, the other for starting ember server. Also if I need to run the test of both frontend and backend, I need to check their syntax, and then type both commands seperately - burden for the developer.
Instead a one stop solution can be using Makefile instead.
To run both servers, we can use Procfile.dev (need to create one), and then use tools like (honcho)[https://github.com/nickstenning/honcho] or (foreman)[http://ddollar.github.io/foreman/] . All this will be started using single command `make start`.
Though we can use honcho directly, but there are many benifits of using Makefile - 

* Can be scaled up for use in production easily - just had to switch from Procfile.dev to Procfile
* Running tests easily
* Cleaning up the setup - completely
* Installing both frontend and backend requirements with a single command.
* No problem of learning new commands for basic but important tasks.

**For developers/new users**:
`make install`
`make start`
will be the only commands to start developing.

@gabru-md @ParthS007 @yashLadha @djmgit  your opinion on this?

**Would you like to work on the issue?**

**Yes**

**Comment by rajvaibhavdubey** [comment]
@rupav  Awesome Idea. LGTM :+1:
