### ISSUE TITLE
Modify the Running Locally in README.md

### ISSUE THREAD

**Issue by rahuldecoded** [fossasia/badgeyay#187]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Currently in [Running locally](https://github.com/fossasia/badgeyay#running-locally) doesn't contain every step to run the application locally.

**Are you working in this?**
*Yes*

**Comment by gabru-md** [comment]
@rahuldecoded it is not a 'bug' but rather a left over feature.
Anyways thanks for the issue. And PR

**Comment by niccokunzmann** [comment]
@rahuldecoded You can check and close the issue.

**Comment by rahuldecoded** [comment]
@niccokunzmann Thanks
