### ISSUE TITLE
Add Greenkeeper bot to badgeyay

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1877]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Greenkeeper automatically updates dependencies and has many other features. You can view more about the greenkeeper bot on https://greenkeeper.io/

**Screenshots**

![screenshot from 2018-12-11 11-49-38](https://user-images.githubusercontent.com/33062425/49782035-dba8bf80-fd3a-11e8-80ee-cbedb14b80be.png)

**Would you like to work on the issue?**

Yes

**Comment by rajvaibhavdubey** [comment]
@ParthS007 @gabru-md @yashLadha Can I proceed to make a PR on this?

**Comment by ParthS007** [comment]
@rajvaibhavdubey We have many other High priority issues, It can be implemented at a later stage.
