### ISSUE TITLE
UI/UX error

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#188]
**I'm submitting a ...**
- [x] bug report

**Current behavior:**
On clicking `Selecting a background`, the dropdown comes after the two fields

**Expected behavior:**
On clicking `Selecting a background`, the dropdown should come below the button

**Steps to reproduce:**
- open `http://127.0.0.1:5000/`
- click on `select a background` (Bug reproduced)

**Comment by vaibhavsingh97** [comment]
I am claiming this issue

**Comment by pushkalkatara** [comment]
This can be a first-timer issue also. Just need to edit the index.html.
