### ISSUE TITLE
Convert shell script to python

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/badgeyay#19]
The `merge_badges.py` file currently performs:
1. Converting SVG to PDF
2. Merging badges together in a single PDF

If it really necessary to perform these operations using shell? Can we convert the shell script to equivalent python script?

Ping @mariobehling @niccokunzmann

**Comment by niccokunzmann** [comment]
It is a small script.. You could do that. I ask myself as a maintainer, (how) does it help other people to contribute?

> If it really necessary to perform these operations using Python? Can we convert the Python script to equivalent shell script?

I exchanged the languages - I do not care. The language is only a tool. If you can name a problem that the conversion solves, I am all for it.

**Comment by jajodiaraghav** [comment]
The problems that we could solve on eliminating the shell script:
1. Make it easier to deploy to Heroku.
2. Allow users to setup devenv in windows

**Comment by jajodiaraghav** [comment]
I just successfully deployed the test branch to heroku. We do not need to remove the shell script. I will deploy the development branch in some time.

**Comment by niccokunzmann** [comment]
@jajodiaraghav sounds good.

**Comment by djmgit** [comment]
@jajodiaraghav @niccokunzmann I would like to work on it

**Comment by niccokunzmann** [comment]
@djmgit Sure, please share your progress (not a complete solution) as soon as possible, so that all people interested can have a look, join and have fun with you 👍
