### ISSUE TITLE
Badgeyay is not opening up

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1904]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Badgeyay is crashing due to some unknown reason most probably due to the recent makefile changes made in https://github.com/fossasia/badgeyay/pull/1867

**Steps to reproduce:**
- Open Badgeyay.com(It won't open)

**Screenshots**

![screenshot from 2018-12-28 16-52-51](https://user-images.githubusercontent.com/33062425/50542718-5eaa9080-0bea-11e9-9498-cced9a76eb99.png)

@ParthS007 @yashLadha @gabru-md

**Comment by sk9331657** [comment]
@rajvaibhavdubey  This can be closed

**Comment by Aakash-DD** [comment]
badgeyay.com is not opening.....how can i open this.....
