### ISSUE TITLE
Simple Error in Font Color

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1916]
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

Default Color should be ffffff but it is fffffff.
**Expected behaviour:**

**Steps to reproduce:**

**Screenshots**

**Would you like to work on the issue?**

Yes.

**Comment by SanjalDhir** [comment]
Hi, I am a newcomer and would like to work on this issue. Please guide me.
