### ISSUE TITLE
Redirecting Non-admins to homepage when they try to login using url

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1918]
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce:**

**Screenshots**

**Would you like to work on the issue?**

Yes.

**Comment by sk9331657** [comment]
@try to visit http://127.0.0.1:4200/admin using non-admin account and see the error.

**Comment by mariobehling** [comment]
Please in future describe what is wrong. Thank you.
