### ISSUE TITLE
Logo for badgeyay

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#192]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behaviour:**
Site looks very simple

**Expected behaviour:**
We can  add a logo of badgeyay. 

**Steps to reproduce:**
NA

**Comment by rupav** [comment]
Hi @ParthS007, @vaibhavsingh97. I would like to make a logo of badgeyay. Please Tell me inputs, what do you want in the logo. Should I ask on gitter channel?

**Comment by ParthS007** [comment]
yes @rupav discuss it on gitter channel.
