### ISSUE TITLE
Give a heading to the create-badges page

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1920]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

The create badges page has no heading, It should have one like 
- Badge Generator

**Would you like to work on the issue?**

Yes

**Comment by Puranjay25** [comment]
@rajvaibhavdubey is this issue valid?

**Comment by rajvaibhavdubey** [comment]
Yeah, it is valid :+1:

**Comment by abishekvashok** [comment]
We don't really need one.
