### ISSUE TITLE
Profile Image is not responsive

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1929]
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce:**

**Screenshots**

![screenshot from 2019-01-15 00-00-58](https://user-images.githubusercontent.com/17084322/51132620-bd157700-1858-11e9-876f-a3f218d5ef5a.png)

**Would you like to work on the issue?**

Yes

**Comment by rajvaibhavdubey** [comment]
@sk9331657 I would like to work on this and submit a PR. 
Thankyou :smile:
