### ISSUE TITLE
Document how to run the tests

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#195]
**I'm submitting a ...**
- [X] bug report

**Current behavior:**

I can not find any documentation about how to run the tests.

**Expected behavior:**

I would like to read about test in these places:

- The README file has a short section about the kinds of tests we use to run
- The documentation/test folder contains a section about how to setup and run the selenium tests

**Comment by ParthS007** [comment]
I want to work on this @niccokunzmann. But I am  learning selenium related topics.will u plz explain on how to start on this issue .

**Comment by souravsingh** [comment]
@niccokunzmann I am interested in working on the issue. Can you please assign the issue to me?

**Comment by niccokunzmann** [comment]
I can not somehow. You can create a PR as soon as possible and share the progress here. I think, this assigns it to you in a way.

**Comment by gabru-md** [comment]
@souravsingh are you working on this? if yes please share your progress on this issue.

**Comment by souravsingh** [comment]
I will be creating a PR in a short while.

**Comment by akshatnitd** [comment]
@gabru-md I have submitted a PR for it, since it was left pending for a long time now.
