### ISSUE TITLE
Decreasing the size of images by 50%, using webp instead of png and jpeg

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1951]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

I think we should use webp instead of jpeg, it's a better and faster optimized image format for the web.

**Would you like to work on the issue?**

Yes

**Comment by aarushi03** [comment]
@rajvaibhavdubey if it is still up for grabs, can I take it?
