### ISSUE TITLE
Upgrade urllib3 to version 1.23 or later

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#1952]
The urllib3 is out of date. Please update it.

**Comment by rajvaibhavdubey** [comment]
@mariobehling I'm claiming this.

**Comment by ashutoshtiwari13** [comment]
@mariobehling I'm taking this up!

**Comment by rajvaibhavdubey** [comment]
@ashutoshtiwari13 I've already submitted a PR for this issue.
