### ISSUE TITLE
Npm Installation Failure for semantic-ui

### ISSUE THREAD

**Issue by Enforcer007** [fossasia/badgeyay#1971]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
There's a issue with installation of frontend. NPM install fails in installing semantic-ui

**Expected behaviour:**
Should include this package in package.json of frontend folder

**Steps to reproduce:**
Can be reproduced on a Ubuntu machine having only git, npm installed.

**Screenshots**
![npm install failure](https://user-images.githubusercontent.com/6951100/51424393-f94b2d80-1bf2-11e9-8019-a3eab461632d.PNG)

**Would you like to work on the issue?**
Yes

**Comment by rajvaibhavdubey** [comment]
Closing as it is not necessary. npm build is working fine.
