### ISSUE TITLE
Implementing Edit Badge Functionality 

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1975]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce:**

**Screenshots**

**Would you like to work on the issue?**

Yes.

**Comment by rajvaibhavdubey** [comment]
@sk9331657, an issue is already made for the same and I'm already working on it.
