### ISSUE TITLE
The logo is not responsive

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1977]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

The logo should change it's width accordingly, but it simply crops out. 

**Screenshots**

![screenshot from 2019-01-22 19-46-35](https://user-images.githubusercontent.com/33062425/51541425-c4530b00-1e7e-11e9-97a5-234b795c4a9d.png)

**Would you like to work on the issue?**

Yes

**Comment by yashLadha** [comment]
This should be implemented in the SVG for changing and mutating the design. This is one of the major challeneges that still need to be tackle in badgeyay. For ref try to research over how other services are doing. All of them are doing the same thing, what we are doing but through a smarted logic.
