### ISSUE TITLE
Badge preview not showing the logo on my-badges page

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1978]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Badge preview does not show the logo on my-badges page. 

**Screenshots**

![screenshot from 2019-01-22 19-51-37](https://user-images.githubusercontent.com/33062425/51541620-47746100-1e7f-11e9-9eca-4cf812a7cde6.png)

**Would you like to work on the issue?**

Yes

**Comment by abishekvashok** [comment]
Its showing now
