### ISSUE TITLE
Badge Statistics in Settings Section

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1985]
**I'm submitting a ...**
- [x] feature request

**Current behaviour:**

**Expected behaviour:**

Section Showing Badge Statistics

**Steps to reproduce:**

**Screenshots**

**Would you like to work on the issue?**

Yes.

**Comment by yashLadha** [comment]
Please elaborate the issue @sk9331657 . This Issue description doesn't seem appropriate

**Comment by Puranjay25** [comment]
@sk9331657 do add some description in the issue.

**Comment by kushthedude** [comment]
@sk9331657 Please reopen after more description. Thanks
