### ISSUE TITLE
Forums icon missing

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1986]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Google forums icon is missing

**Screenshots**

![screenshot from 2019-01-26 22-59-45](https://user-images.githubusercontent.com/33062425/51790654-4bc1b680-21be-11e9-9c0e-080a5c31c9c2.png)

**Would you like to work on the issue?**

Yes

**Comment by kushthedude** [comment]
Solved in #2076
