### ISSUE TITLE
Update Features section on home page

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/badgeyay#1987]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Features section on home page should be updated with the latest information of the badge creation like logo addition. 

**Would you like to work on the issue?**

Yes

**Comment by yashLadha** [comment]
It would be great if you can provide some elaborate description about the issue. Like what you are planning to do? @rajvaibhavdubey  That would be a good practice and it will also help fellow developers to more clearly see your idea.

**Comment by rajvaibhavdubey** [comment]
Sure @yashLadha
