### ISSUE TITLE
Shifting to SVGs for printing with prebuilt PNGs

### ISSUE THREAD

**Issue by pushkalkatara** [fossasia/badgeyay#199]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Currently, prebuilt PNGs are being fetched and printed. Only user-defined.png has an SVG on which user can select the background color and text and print badges.

**Expected behavior:**

The user selects an image from the list, adding a placeholder in HTML and CSS as [OPTIONAL] , if the user lefts the field empty, then default made PNGs be used else if the user enters text or background or both, the whole process goes through SVG and generate a user-desired image.

**Steps to reproduce:**
Multiple Task Issue, List's here - 
- [ ] Create SVGs for all the images which currently are PNGs, reference - user-defined.svg
- [ ] Change conditions in main.py according to Expected behaviour.

**Comment by pushkalkatara** [comment]
@niccokunzmann @jajodiaraghav @gabru-md @vaibhavsingh97 @rupav  Please review this issue request.

**Comment by rupav** [comment]
@gabru-md  @vaibhavsingh97 @jajodiaraghav  What do you suggest? Please comment your opinion :)
