### ISSUE TITLE
Modify ISSUE_TEMPLATE to include issue description

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#1994]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Developers just plainly creating issues with a title

**Expected behaviour:**

There should be a description in PR for better understanding the idea, for feature requests only.

**Comment by yashLadha** [comment]
Yes, please go ahead. @rajvaibhavdubey

**Comment by sk9331657** [comment]
Working on this due to inactivity .
