### ISSUE TITLE
Create a web page UI to upload CSV to generate a badge

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#2]
The CSV has four fields:
* Name
* Type (e.g. Speaker)
* Handle or Nick
* Organization/Project

**Comment by jajodiaraghav** [comment]
Hi @mariobehling 
I would really like to work on this issue. Although, Nothing has been specified about the backend technology. Should we use Flash or Nodejs for the UI?

**Comment by mariobehling** [comment]
@jajodiaraghav Thanks for your interest. Best would be to follow the example of the Open Event Server. So Flask would be great.

**Comment by jajodiaraghav** [comment]
Can we close this issue. We have a web UI now :)

**Comment by niccokunzmann** [comment]
#5 closes this.
