### ISSUE TITLE
Color Picker integration for HEX color value for Background.

### ISSUE THREAD

**Issue by pushkalkatara** [fossasia/badgeyay#200]
**I'm submitting a ...**
- [ ] bug report
- [X ] feature request

**Current behavior:**

The user has to enter Color's Hex code to change the background color and print it.

**Expected behavior:**

Color Picker which gives options to the user to choose from several colors.

**Steps to reproduce:**
Maybe helpful - https://farbelous.github.io/bootstrap-colorpicker/

**Comment by plant99** [comment]
Hi, @pushkalkatara 
Can I work on the issue?

**Comment by plant99** [comment]
Do I have to integrate [bootstrap-colorpicker](https://farbelous.github.io/bootstrap-colorpicker/) or do I have to build a popup from scratch?

**Comment by pushkalkatara** [comment]
Yes go ahead. Choose whichever is the best for the app.

**Comment by plant99** [comment]
I will integrate it first, then eventually try to build a new one from scratch, then integrate it.

**Comment by pushkalkatara** [comment]
What is the status of this issue? Is it integrated?

**Comment by vaibhavsingh97** [comment]
@pushkalkatara @alirizwi needs to squash commits then we can merge his PR 😄
