### ISSUE TITLE
Github Login Option

### ISSUE THREAD

**Issue by Puranjay25** [fossasia/badgeyay#2003]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

There are options for login through google and twitter. For better purpose there should also be github login option. 

**Would you like to work on the issue?**

Yes.

**Comment by rishika1802** [comment]
@Puranjay25 Can i work on this issue?

**Comment by kushthedude** [comment]
> @Puranjay25 Can i work on this issue?

@rishika1802 There are several bugs in our system at present. We aim to solve the bugs and make the system more stable before introducing new features which also seems not of use at the present. 
Please look for any other issue. Thanks

**Comment by kushthedude** [comment]
Not of scope currently.
