### ISSUE TITLE
Message of "i" button  is hidden when hover.

### ISSUE THREAD

**Issue by Puranjay25** [fossasia/badgeyay#2008]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**

Full message of "i" should be diaplayed in "Create Badges" section.
**Current behaviour:**

In Create Badges page, when "i" button is hovered, the message it displays is hidden.

**Expected behaviour:**

**Steps to reproduce:**

**Screenshots**

![hidden](https://user-images.githubusercontent.com/20750726/52898028-0c0b4f00-31ff-11e9-9a43-fd8779735f48.gif)

**Would you like to work on the issue?**

Yes.

**Comment by rajvaibhavdubey** [comment]
@Puranjay25 An issue and a PR has been already made for the same. #1963 , #1964
