### ISSUE TITLE
Frontend bug while creating new badge

### ISSUE THREAD

**Issue by RAraghavarora** [fossasia/badgeyay#2011]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**
While creating a new badge, on scrolling down the preview of the badge overlaps the bottom navbar.

**Expected behaviour:**
The badge preview should not overlap the bottom nav, and should scroll up.

**Screenshots**
![foss](https://user-images.githubusercontent.com/35304178/53435488-efe98800-3a1e-11e9-9535-3d2cd988c62c.png)

**Would you like to work on the issue?**
No

**Comment by sk9331657** [comment]
@RAraghavarora  This is duplicate issue . Already one issue is opened. Will fix the issue asap. Busy with placements.

**Comment by RAraghavarora** [comment]
Oh, okay. I'll delete the issue :)
