### ISSUE TITLE
Text Color Not Displayed in My Badges section

### ISSUE THREAD

**Issue by Puranjay25** [fossasia/badgeyay#2020]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**
**Current behaviour:**

In badge description of badges in "My Badges" section Text Color is not displayed.

**Screenshots**

![screenshot from 2019-03-01 17-33-28](https://user-images.githubusercontent.com/20750726/53637201-8d73d000-3c48-11e9-827f-fac50fd6f76c.png)
**Would you like to work on the issue?**

Yes.

**Comment by kushthedude** [comment]
@Puranjay25 ,Any updates?

**Comment by Puranjay25** [comment]
@kushthedude I got stuck in a part. I have posted my issue on gitter channel of badgeyay.

**Comment by mariobehling** [comment]
Not needed.
