### ISSUE TITLE
Error in extracting user in reset_password()

### ISSUE THREAD

**Issue by RAraghavarora** [fossasia/badgeyay#2022]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**
Logical error in User.getUser()

**Current behaviour:**
User is extracted by the username without explicitly passing the keyword argument 'username'

**Expected behaviour:**
Pass the keyword argument 'username'

**Would you like to work on the issue?**
Yes

**Comment by Puranjay25** [comment]
There is nothing wrong with the current version, because data['username'] is not used anywhere else in the entire function. So it's not required to assign data['username'] to a variable.

**Comment by RAraghavarora** [comment]
@Puranjay25 I think you misunderstood the issue. The getUser function takes 4 arguments: cls, user_id, username, and email. Since we are sending username, we need to explicitly write: User.getUser(username=data['username']), instead of 
User.getUser(data['username']), 
as the 2nd version would pass the value of username to user_id.

**Comment by RAraghavarora** [comment]
I understand that I need to squash my commits, I'll do that.
