### ISSUE TITLE
Check for username while signup

### ISSUE THREAD

**Issue by Puranjay25** [fossasia/badgeyay#2027]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

When a user signup it should be verified that an already registered user with that username doesn't exists.
**Current behaviour:**

A username is chosen by multiple users.
**Expected behaviour:**

**Steps to reproduce:**

**Screenshots**

**Would you like to work on the issue?**

**Comment by rajdeepbharati** [comment]
Hi can I work on this?
