### ISSUE TITLE
badgeyay website is not loading on both desktop and mobile website.

### ISSUE THREAD

**Issue by prasadgujar** [fossasia/badgeyay#2032]
**I'm submitting a ...**
- [ /] bug report
- [ ] feature request

**Description :**

Currently badgeyay website is not working/loading both on mobile as well on desktop.
**Current behaviour:**

 Badgeyay website: [http://badgeyay.com/](url) is not working
**Expected behaviour:**

excepted to load website if website is underconstruction it should show message.

**Would you like to work on the issue?**

Yes.

**Comment by kushthedude** [comment]
@rajvaibhavdubey i dont think badgeyay is is production mode , so isnt it obvious that site wont load

**Comment by abishekvashok** [comment]
Its because of the fact that the api is down

**Comment by abishekvashok** [comment]
The api is up and website is back online now
