### ISSUE TITLE
badgeyay backend on the herokuapp giving 404 error

### ISSUE THREAD

**Issue by prasadgujar** [fossasia/badgeyay#2033]
**I'm submitting a ...**
- [/ ] bug report
- [ ] feature request

**Description :**

badgeyay backend hosted on the Heroku is not working.
**Current behavior:**

after visiting the [http://badgeyay-dev.herokuapp.com/](url) it's giving error-404 Not Found: The requested URL was not found on the server.
**Expected behavior:**

it should work fine without giving any error if the hosted URL is changed it should re-direct to new url
 
**Would you like to work on the issue?**

Yes

**Comment by rajvaibhavdubey** [comment]
Please don't make duplicate Issues. :smile:

**Comment by rajvaibhavdubey** [comment]
Duplicate Issue #2032
