### ISSUE TITLE
Remove unnecessary text

### ISSUE THREAD

**Issue by vinaysomawat** [fossasia/badgeyay#2035]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**

**Current behaviour:**
'+' present in http://localhost:4200/create-badges 

**Expected behaviour:**
It should be removed.

**Steps to reproduce:**

**Screenshots**
![Screenshot from 2019-03-18 00-20-06](https://user-images.githubusercontent.com/30196269/54496392-c84a5900-4914-11e9-984b-6227b95a4e0d.png)

**Would you like to work on the issue?**
Yes

**Comment by rajvaibhavdubey** [comment]
This has already been solved in a PR.

**Comment by thesoleninja** [comment]
@rajvaibhavdubey  Can you share the commit/PR link for this?

**Comment by rajvaibhavdubey** [comment]
https://github.com/fossasia/badgeyay/pull/2028

**Comment by sk9331657** [comment]
@thesoleninja This pr is duplicate.

**Comment by rajvaibhavdubey** [comment]
This issue can be closed, already resolved.
