### ISSUE TITLE
Webpage not loading !

### ISSUE THREAD

**Issue by khanna98** [fossasia/badgeyay#2038]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**

I have been trying to open the webpage for quite a long time now and it is not opening. My internet speed is good and there are no proxies on my network.

**Current behaviour:**

The site is not loading or showing any content even after fully loading.

**Expected behaviour:**

The site must load quickly and I should be able to use it.

**Screenshots**

![Screenshot from 2019-03-20 23-34-43](https://user-images.githubusercontent.com/29047276/54708327-2e2f1e80-4b69-11e9-991c-ff6be5687cf5.png)

**Would you like to work on the issue?**

I can try to look into the matter.

**Comment by rajvaibhavdubey** [comment]
Please don't make duplicate Issues. :smile:

**Comment by rajvaibhavdubey** [comment]
Duplicate Issue #2032
