### ISSUE TITLE
No Installation instructions for MacOS

### ISSUE THREAD

**Issue by kushthedude** [fossasia/badgeyay#2049]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

As i was exploring README.md , No specific installation instructions are given for MacOS , As some commands are different for Mac

**Expected behaviour:**

Include Specific instructions for MacOS.

**Would you like to work on the issue?**

Yup

**Comment by kushthedude** [comment]
@abishekvashok @rajvaibhavdubey Should i include them ?

**Comment by rajvaibhavdubey** [comment]
Yes please, continue :+1:
