### ISSUE TITLE
Separate Issue Templates for Bug Report and Feature Request

### ISSUE THREAD

**Issue by kushthedude** [fossasia/badgeyay#2050]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

Currently when a user submits a new issue , There are no specific templates for Bug Report and Feature Request .

**Expected behaviour:**

As there are two separate templated for types of issue in Open Event , I propose to include Separate and more accurate templates for both Bug and Feature Request
**Steps to reproduce:**

**Would you like to work on the issue?**

If needed , I will add separate templates

**Comment by kushthedude** [comment]
@rajvaibhavdubey @abishekvashok Your thoughts on it?

**Comment by abishekvashok** [comment]
We can do it but let's do it later and focus on current issues.
