### ISSUE TITLE
Align features in homepage to left instead of center

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#2070]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

Align the features portion text to the left
**Current behaviour:**

Aligned center
**Expected behaviour:**

Aligned to the left
**Steps to reproduce:**
Go to badgeyay.com
  
**Screenshots**

![Screenshot from 2019-07-28 01-44-44](https://user-images.githubusercontent.com/8947010/61999200-8a86e980-b0d9-11e9-8e15-720f16c2219e.png)

**Would you like to work on the issue?**

No. first-timers only-please

**Comment by ektaarora3501** [comment]
Can i work on this issue ?

**Comment by kushthedude** [comment]
> Can i work on this issue ?

Sure Please Proceed

**Comment by kushthedude** [comment]
@ektaarora3501  Sure Please Proceed

**Comment by vaibhavmatta** [comment]
Is the issue resolved? if not, then Can I work on it?

**Comment by vaibhavmatta** [comment]
<img width="1440" alt="Screenshot 2019-08-01 at 3 12 00 AM" src="https://user-images.githubusercontent.com/50797619/62250365-5f1e3a80-b40a-11e9-95a5-c76c7f02c502.png">

Is this what being expected?

**Comment by Aswinpookkatt** [comment]
why is it required the webpage is better as it is now .

**Comment by rajvaibhavdubey** [comment]
@vaibhavmatta yes looks good :+1: , Just confirm if @ektaarora3501 is still working on this.

**Comment by vaibhavmatta** [comment]
@rajvaibhavdubey , @ektaarora has resolved the issue Successfully. We both worked together. She will push it to the repository soon.
Thanks

**Comment by kushthedude** [comment]
@vaibhavmatta Want to claim?

**Comment by vaibhavmatta** [comment]
@kushthedude I am Claiming it.

**Comment by sanjeev0007** [comment]
If no one is working on this isssue can i work?

**Comment by vaibhavmatta** [comment]
@sanjeev0007 
I have made a PR for it. Der are still some bugs ony side. You can go for it.

**Comment by sanjeev0007** [comment]
@vaibhavmatta OK!

**Comment by AmanKumarBharti** [comment]
is the issue open or assigned?

**Comment by vaibhavmatta** [comment]
@AmanKumaraBharti Issue is still open, You can claim it if you want to.

**Comment by michaelschomburg** [comment]
Hello, I would like to work on it if it's still open?

**Comment by abishekvashok** [comment]
Sure go on
