### ISSUE TITLE
Simplify documentation and rename "Api" to "Backend"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#2074]
Keeping the documentation in subfolders of frontend and API makes it difficult to find. Please move all documentation to "/docs" in the main folder. Change the following:
* Integrate Readme.md content https://github.com/fossasia/badgeyay/tree/development/frontend into readme of start folder and only keep a short explanation.
* Integrate Readme.md content of https://github.com/fossasia/badgeyay/tree/development/api into readme of start folder and only keep a short explanation.
* Move /api/docs/installation to /docs/backend/installation
* Rename folder "api" to "backend"

**Comment by abishekvashok** [comment]
On it

**Comment by abishekvashok** [comment]
@mariobehling done

**Comment by abishekvashok** [comment]
@mariobehling pls review #2101
