### ISSUE TITLE
Many blank lines and blank spaces in our code files

### ISSUE THREAD

**Issue by kushthedude** [fossasia/badgeyay#2077]
I have noticed many files containing blank spaces and blank lines which have no use and makes the code look bad. 
This will be a parent issue If anyone finds such occurrence fix them and submit the PR

**Comment by abishekvashok** [comment]
Please open relevant issues for each file, instead of opening one parent issue and not specifying anything

**Comment by kushthedude** [comment]
> Please open relevant issues for each file, instead of opening one parent issue and not specifying anything

What more do you need, should I spoon feed you every file ? @abishekvashok Please give a valid excuse to close any issue or revert a PR

**Comment by geetchoudhary** [comment]
@kushthedude , Can I help with this?

**Comment by kushthedude** [comment]
Sure

**Comment by gabru-md** [comment]
can be closed
