### ISSUE TITLE
Deployment on other cloud platforms.

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#208]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
Till now the project can be deployed only on Docker and Heroku

**Expected behavior:**
Branch out deployment into other cloud platform such as AWS,Kubernetes etc.

**Comment by S2606** [comment]
Please give me your views @fossasia/badgeyay-admin

**Comment by vaibhavsingh97** [comment]
@S2606 We can go ahead but we need documentation + implemented url link so please break this issue into small one 😄

**Comment by meets2tarun** [comment]
@S2606 
You can try deploying it on the platform which you find.
If successful test the changes, and then we will include them in the documentation.

**Comment by alirizwi** [comment]
@S2606 @vaibhavsingh97 @meets2tarun, Can I work on this issue as I want to learn deployment on AWS?

**Comment by S2606** [comment]
@alirizwi Sure go ahead and send a PR..

**Comment by S2606** [comment]
@alirizwi Dont forget to create a seperate issue for that

**Comment by idealadarsh** [comment]
@S2606  Hello, I'd like to add support for deployment to Scalingo.

**Comment by S2606** [comment]
Hey @idealadarsh Sure go ahead..

**Comment by idealadarsh** [comment]
@S2606 I also found a way to deploy it on IBM Bluemix.

**Comment by vaibhavsingh97** [comment]
@idealadarsh Go ahead

**Comment by jajodiaraghav** [comment]
I would like to know what exactly we are getting from deploying the app on so many platforms?
Can someone explain?

**Comment by idealadarsh** [comment]
The "Deploy to Heroku" button was not working, the problem was in the url. I fixed it.

**Comment by jajodiaraghav** [comment]
I think we can close this as we have already deployed badgeyay to several platforms.
