### ISSUE TITLE
Unable to download badges due to Invalid Firebase DB URL

### ISSUE THREAD

**Issue by kushthedude** [fossasia/badgeyay#2085]
**Description**

Unable to download badges due to Invalid Firebase DB URL

**Stack-Trace:**
```py
File "/Users/kush/badgeyay/venv/lib/python3.7/site-packages/firebase_admin/db.py", line 703, in from_app
    db_url = cls._get_db_url(app)
  File "/Users/kush/badgeyay/venv/lib/python3.7/site-packages/firebase_admin/db.py", line 724, in _get_db_url
    'Firebase Realtime Database instance.'.format(url))
ValueError: Invalid databaseURL option: "https://badgeyay-195bf.firebaseio.com,". databaseURL must be a valid URL to a Firebase Realtime Database instance.
```

**Comment by kushthedude** [comment]
@yashLadha @abishekvashok, I would like some help here, Can you guys help me in fixing the DB issues.

**Comment by vaibhavmatta** [comment]
@kushthedude I want to help in this issue. Please allow me and tell me more about the issue. 
Thanks

**Comment by kushthedude** [comment]
> @kushthedude I want to help in this issue. Please allow me and tell me more about the issue.
> Thanks

Not ready to be worked upon

**Comment by vaibhavmatta** [comment]
Alright Sir, @kushthedude . Please keep my interest in ur notice and tell me the task whenever you feel like. Thanks

**Comment by kushthedude** [comment]
> Alright Sir, @kushthedude . Please keep my interest in ur notice and tell me the task whenever you feel like. Thanks

Sure

**Comment by kushthedude** [comment]
@fossasia/badgeyay-admins Is something wrong with the `Production Config` of our app, As on development most of the functionalities work as expected but on development, each and every action throws an error 
```js
Uncaught TypeError: Cannot read property 'nextSibling' of undefined 
```
