### ISSUE TITLE
Name tag under feature section can be made more readable 

### ISSUE THREAD

**Issue by vaibhavmatta** [fossasia/badgeyay#2087]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**
SHUBHAM KUMAR - information is not easily readable . It's readability can be increased by changing either colour or the background.

**Current behaviour:**
Refer the screenshot.

**Expected behaviour:**
Text can be more readable .

**Steps to reproduce:**

**Screenshots**

<img width="1440" alt="Screenshot 2019-08-01 at 3 12 00 AM" src="https://user-images.githubusercontent.com/50797619/62412279-a7617680-b61d-11e9-8c92-5db3f6d9177c.png">

**Would you like to work on the issue?**
YES

**Comment by vaibhavmatta** [comment]
I want to work on it.

**Comment by kushthedude** [comment]
> I want to work on it.

@vaibhavmatta I don't think we need to change the badge on the Home Page, As it simply depicts the type of customisation and information we can offer on our platform
