### ISSUE TITLE
Login Dashboard: Update G+ Depreciated buttons

### ISSUE THREAD

**Issue by lelouchB** [fossasia/badgeyay#2089]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request 

**Description :**

New Google  signin option 

**Current behaviour:**

It currently shows Goolge+ sign-in option but as we all know it was shut down last year, it may mislead users and some users may not even use this sign-in option thinking google+ is no more

**Expected behaviour:**

Google Sign In  instead of Google + sign in

**Steps to reproduce:**
- Go to `Login Section`
- Try to use O-Auth

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/45850882/62419128-fb5c7180-b696-11e9-8cf2-2631aea60546.png)

**Would you like to work on the issue?**
Yes I would definitely like to work on the issue and want to add other login option like GitHub, Facebook, etc,

**Comment by kushthedude** [comment]
@lelouchB You can work on it if you want.

**Comment by lelouchB** [comment]
Thanks a lot, I will get on it right away, if you have any pointers for me let me know, This is my first time contributing to an Open Source Project, I appreciate all the help I can get

**Comment by kushthedude** [comment]
> Thanks a lot, I will get on it right away, if you have any pointers for me let me know, This is my first time contributing to an Open Source Project, I appreciate all the help I can get

For the following issue , just change the the logo of button. It would be a bit easy and you will get idea of the codebase pretty well . Then you may go for some bug fixes if you like

**Comment by lelouchB** [comment]
Hi I have done the changes and made a PR, please review it 
Also, I want to join this organization and want to continue working on OS projects, could you please let me know what's the process.

**Comment by rajvaibhavdubey** [comment]
Fixed in #2090

**Comment by rajvaibhavdubey** [comment]
> Hi I have done the changes and made a PR, please review it
> Also, I want to join this organization and want to continue working on OS projects, could you please let me know what's the process.

Read the Fossasia's contributors guide, there youll get to know the complete process. 
Thankyou for contributing :smile:
