### ISSUE TITLE
update outdated dependencies on frontend

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#2099]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

The many dependencies in the fronend are outdated

**Current behaviour:**

They are outdated

**Expected behaviour:**

They are upto date

**Steps to reproduce:**
Run `npm outdated`

**Would you like to work on the issue?**

Yes, on it

**Comment by amreshk005** [comment]
@kushthedude is it still open? if yes can I work on this?

**Comment by kushthedude** [comment]
Not of priority currently.

**Comment by abishekvashok** [comment]
Hey we recently adopted a new roadmap which would hinder this issues proceeding. So for now, I am closing this. Thanks for looking at the code :)
