### ISSUE TITLE
Add QR code support for backend

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#2116]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

Add support for QR code on the back end.
Parent issue #1729

**Would you like to work on the issue?**

Yes

**Comment by kushthedude** [comment]
To be done after #2119

**Comment by abishekvashok** [comment]
Hey we recently adopted a new roadmap which would hinder this issues proceeding. So for now, I am closing this. Thanks for looking at the code :)
