### ISSUE TITLE
Convert Website to PWA(Progressive Web App)

### ISSUE THREAD

**Issue by lelouchB** [fossasia/badgeyay#2118]
**I'm submitting a ...**
- [ ] bug report
- [✔️  ] feature request

**Description :**

Convert the existing website to PWA so that it is more easily accessible to users
**Current behaviour:**

Site have no manifest or sevice worker
**Expected behaviour:**

After sucessful conversion, users will able to install the website as an chrome web app, and on mobile phones tooo. Website will be available offline also.
**Steps to reproduce:**
Creating Manifest.json and configuring  service worker
**Screenshots**

![1_rZ8GSGbL2CkQnnLBrnjZtQ](https://user-images.githubusercontent.com/45850882/63649417-c81f7680-c75a-11e9-839e-ced39835a046.png)

**Would you like to work on the issue?**

Yes, I will love to work on this issue.

**Comment by kushthedude** [comment]
Not required for now
