### ISSUE TITLE
Migrate from Bower to Yarn

### ISSUE THREAD

**Issue by kushthedude** [fossasia/badgeyay#2122]
Bower is dead and not used as an FE Package manager now.
```sh
We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```
This must be enough. Let's migrate to `Yarn` now.

**Comment by geetchoudhary** [comment]
@kushthedude , Can I work on this?

**Comment by kushthedude** [comment]
Go on , But this is not a `Good First Issue` , I suggest making yourself comfortable with the codebase prior.
