### ISSUE TITLE
Feature Enhancement: Preview of badge should be available

### ISSUE THREAD

**Issue by joshiadvait8** [fossasia/badgeyay#2127]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

Preview of the badge should be available in My badges section 

**Current behavior:**

There is no option of preview in my badge section

**Expected behavior:**

Preview of badge should be available before downloading PDF

**Steps to reproduce:**

**Screenshots**

**Would you like to work on the issue?**

yes

**Comment by LeenaKaushik11** [comment]
Can I work in this issue @joshiadvait8

**Comment by parthsarthiprasad** [comment]
id like to add on to this feature @joshiadvait8

**Comment by abishekvashok** [comment]
Hey we recently adopted a new roadmap which would hinder this issues proceeding. So for now, I am closing this. Thanks for looking at the code :)
