### ISSUE TITLE
Wrong command in localvir.md for restarting postgresql

### ISSUE THREAD

**Issue by geetchoudhary** [fossasia/badgeyay#2128]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**
The command to restart postgresql in mac is wrong.

**Current behaviour:**
`brew services postgresql restart` gives error.

**Expected behaviour:**
postgresql should be stopped and restarted succesfully.

**Screenshots**
<img width="1440" alt="Screenshot 2019-09-26 at 1 37 33 PM" src="https://user-images.githubusercontent.com/35570715/65671026-1f6b7c00-e064-11e9-8801-0d3067eb9491.png">

**Would you like to work on the issue?**
Yes. Working on it.

**Comment by kushthedude** [comment]
Both `brew services restart postgresql` or `brew services postgresql restart` works well on fish and bash shell.

**Comment by geetchoudhary** [comment]
I have attached the screenshots with the issue here
<https://github.com/fossasia/badgeyay/issues/2128>. PTAL.
