### ISSUE TITLE
Removing the function being displayed on badge preview

### ISSUE THREAD

**Issue by DaKeiser** [fossasia/badgeyay#2139]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**

A function appears on the badge preview

**Current behaviour:**

A function appears on the badge preview although it shouldn't.

**Expected behaviour:**

The function must not appear on the badge preview.

**Steps to reproduce:**

**Screenshots**

![test](https://user-images.githubusercontent.com/42712983/66021586-cb034900-e508-11e9-9ff6-19d69d244f5a.png)

**Would you like to work on the issue?**

Yes

**Comment by kushthedude** [comment]
@DaKeiser Please tell `Steps To Reproduce`.

**Comment by LeenaKaushik11** [comment]
Please explain @DaKeiser

**Comment by abishekvashok** [comment]
Hey we recently adopted a new roadmap which would hinder this issues proceeding. So for now, I am closing this. Thanks for looking at the code :)
