### ISSUE TITLE
Store assets in our repository rather than calling third party services

### ISSUE THREAD

**Issue by kushthedude** [fossasia/badgeyay#2140]
- Store assets in our repository rather than calling third party services, As it may tend to call too much third party services and leads to slow loading time.

- Also some of the assets are not loading

**Comment by jantznick** [comment]
Do you have a list of third party services used or will it require combing through the current code a bit?

**Comment by kushthedude** [comment]
@jantznick Thanks for your interest in the `BadgeYay`, Regarding the issue I just need to store image assets and license assets in our repository rather than rendering them from 3rd party websites.

**Comment by hash84** [comment]
@kushthedude Can you list the which image and license assets should be stored in the repository 
I would like to work on this issues

**Comment by kushthedude** [comment]
See the badges used in READme and also docker svg is broken

**Comment by Nikhil-Vats** [comment]
@kushthedude I would love to work on this. I will send a PR in a day. I have a few questions -
1. These assets should be stored in `badgeyay/frontend/public/images`, right?
2. Where is the docker svg used which is broken?
3. I couldn't find any images/assets in LICENSE, where are they exactly?

**Comment by Nikhil-Vats** [comment]
I have sent a PR with all assets used in README stored in reposiitory. I will update it as soon as I figure out about the License assets and broken docker svg. Let me know if you have any suggestions/reviews.
