### ISSUE TITLE
Unable to login to Badgeyay on local server

### ISSUE THREAD

**Issue by iamaadijo** [fossasia/badgeyay#2143]
- I followed the instruction on how to set up Badgeyay on local to the T but still wasn't able to login to Badgeyay on the local installation. 

- Tried registering a new user. Screenshot for this is attached below.

**To Reproduce**
Steps to reproduce the behaviour:

- Just follow the current Readme to setup Badgeyay on local installation

**Screenshots**
![Badgeyaylocalinstalltion](https://user-images.githubusercontent.com/38288671/66274068-3f871080-e898-11e9-9d09-48ebe1575efb.png)

I am posting an issue for the first time. I apologize in advance for any inconvenience I may cause.

**Comment by abishekvashok** [comment]
Hey we recently adopted a new roadmap which would hinder this issues proceeding. So for now, I am closing this. Thanks for looking at the code :)
