### ISSUE TITLE
Addition of Semantic UI in further readings

### ISSUE THREAD

**Issue by nirne12** [fossasia/badgeyay#2158]
I have seen some of the PR's where the user doesn't have an idea about the UI which the app is based on.
It would be great to include `Semantic UI` in Further Readings and Links to make them more comfortable with the WEB-APP

**Comment by abishekvashok** [comment]
Hey we recently adopted a new roadmap which would hinder this issues proceeding. So for now, I am closing this. Thanks for looking at the code :)
