### ISSUE TITLE
no module named `defusedxml.lxml`

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#216]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

`defusedxml.lxml` is missing from `requirements.txt`

**Expected behavior:**

should not cause any error.

**Steps to reproduce:**
Add `defusedxml` to `requirements.txt`

**Yes I will work on this**

**Comment by S2606** [comment]
@gabru-md I just ran into the same error :) but even after installing defusedxml, this error pops out

![image](https://user-images.githubusercontent.com/18497513/31053333-d142ae72-a6b8-11e7-962d-24cd92c28e53.png)

**Comment by gabru-md** [comment]
@S2606 this error is persistent, When i try to install `cairocffi` i get this error :
![screenshot at 2017-10-01 10-32-03](https://user-images.githubusercontent.com/25414121/31053383-cbe47cdc-a693-11e7-9009-46011db6c6fe.png)

I cannot get rid of this. But would like to work upon it.
meanwhile can you have a look through #217

**Comment by ananyo2012** [comment]
Hey all seems you all are using Fedora. Install the `python3-devel` and `python-devel` packages. It will solve the issue.

**Comment by gabru-md** [comment]
yes i see and solved it .
Will be adding it to my PR Thanks!
