### ISSUE TITLE
V2-Setup Django in the project

### ISSUE THREAD

**Issue by codedsun** [fossasia/badgeyay#2164]
**Is your feature request related to a problem? Please describe.**
Setup django in the backend folder of the project on v2 Branch

**Describe the solution you'd like**
With the following discussion, it has been decided to reboot the badgeyay with ReactJS+Django

**Comment by codedsun** [comment]
@iamareebjamal Shall i send the PR with basic initialisation of project or do we have to do something else- like setting the directory structure, connecting the DB?

**Comment by iamareebjamal** [comment]
It's same in all Django projects

**Comment by codedsun** [comment]
@iamareebjamal What about the other files in backend folder as the v2 branch is even with development branch?

**Comment by codedsun** [comment]
@kushthedude Please give your inputs.

**Comment by kushthedude** [comment]
@codedsun @iamareebjamal I think we should start v.2 branch as clean tree.
Also it would be great if you could mention [V.2] in your issue heading. It would make issue tracker clean.

**Comment by codedsun** [comment]
@kushthedude Yes, it should be a clean tree. Who will do it?

>Also it would be great if you could mention [V.2] in your issue heading. It would make issue tracker clean.

Okay sure

**Comment by kushthedude** [comment]
@iamareebjamal Do you have admin rights for this repo ? I would like you to enable Travis and Codacy as mandatory check. Also to enable the `Update Branch` switch for the repository .

**Comment by codedsun** [comment]
@iamareebjamal Please update

**Comment by iamareebjamal** [comment]
On?

**Comment by codedsun** [comment]
>@iamareebjamal Do you have admin rights for this repo ? I would like you to enable Travis and Codacy as mandatory check. Also to enable the Update Branch switch for the repository .

This

**Comment by iamareebjamal** [comment]
That has been done already

**Comment by codedsun** [comment]
@iamareebjamal ? Which PR. in channel it was raised to setup on v2 branch. Also I see no files in v2 branch for django setup

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/badgeyay/issues/2164#issuecomment-548729565 

This has been done

**Comment by codedsun** [comment]
@iamareebjamal Yes, the task mentioned in the comment is done. Thanks
I thought you are talking about the setup of django. I have setup and sent the PR. Please check

**Comment by codedsun** [comment]
@iamareebjamal Please close this issue, as I have done this and PR is merged
