### ISSUE TITLE
Integrate Auth in Django [V-2.0]

### ISSUE THREAD

**Issue by codedsun** [fossasia/badgeyay#2175]
**Is your feature request related to a problem? Please describe.**
Integrate Auth in Django
Parent issue #2168

**Comment by codedsun** [comment]
@iamareebjamal Shall i use the same models as previous?

**Comment by iamareebjamal** [comment]
You can't

**Comment by codedsun** [comment]
I will setup a new db and create that models, this is what I meant..

**Comment by codedsun** [comment]
Or we shall use auth provided by django? @iamareebjamal

**Comment by iamareebjamal** [comment]
Obviously

**Comment by codedsun** [comment]
> Obviously

For which one? @iamareebjamal

**Comment by iamareebjamal** [comment]
Django Auth. What's the use of Django if we reimplement everything ourselves

**Comment by codedsun** [comment]
I will send a PR by this weekend
