### ISSUE TITLE
Add django social auth function[V-2.0]

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/badgeyay#2177]
Add django social auth function[V-2.0]
1. github
2. facebook
3. twitter
**Additional context**
want to work on this .

**Comment by maze-runnar** [comment]
@kushthedude ,should i start work on this ?

**Comment by kushthedude** [comment]
No that is too much later

**Comment by maze-runnar** [comment]
So what would be the next, after general login implementation to work on ?

**Comment by codedsun** [comment]
@maze-runnar @kushthedude  We have to decide the models, if anyone could help here.
https://github.com/fossasia/badgeyay/issues/2168

**Comment by harsh7in** [comment]
May I work on this project??
