### ISSUE TITLE
Getting error while running yarn install

### ISSUE THREAD

**Issue by rishipurwar1** [fossasia/badgeyay#2183]
I tried to clone badgeyay frontend repository. I ran all the commands as given in readme. But when I run yarn install it gives an error(An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/free-solid-svg-icons/-/free-solid-svg-icons-5.11.1.tgz: ESOCKETTIMEDOUT").
I already install npm and node. 

OS: Window 10 Pro

Thank You

**Comment by Dishebh** [comment]
@rishipurwar1 Instead of opening an issue for it, pls try communicating the same problem on the gitter channel -
https://gitter.im/fossasia/badgeyay
Thanks
