### ISSUE TITLE
To become a maintainer 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#220]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request

I want to take responsibility to add labels of hacktoberfest to the existing issues .

**Comment by niccokunzmann** [comment]
@ParthS007 contributed in #218. According to the maintainer section, this issue nominates him to become a maintainer. ([source](https://github.com/fossasia/badgeyay#maintainers)).
I will add him, we can let the issue open for discussion and if there are no disagreements, close it after a few days. @fossasia/badgeyay-admin

**Comment by bhaveshAn** [comment]
@niccokunzmann 
I have contributed in #229 and #259  and would like to become a maintainer. Please add me @fossasia/badgeyay-admin . Thanks !

**Comment by niccokunzmann** [comment]
@bhaveshAn You are added. If there are any objections, they can be told here. We have quite a list of maintainers now... I wonder how you keep at sync :)

**Comment by bhaveshAn** [comment]
>   wonder how you keep at sync :) 

Actually, I made the issue 1 hour back and there were connection problems so it came into existence now. :relaxed:

**Comment by jajodiaraghav** [comment]
Closing as Parth is now a maintainer.
