### ISSUE TITLE
Add option to upload a zip file

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/badgeyay#23]
Add option to upload a zip file containing the corresponding csv+png files, and return the badges to download

**Comment by jajodiaraghav** [comment]
Claiming :rocket:

**Comment by niccokunzmann** [comment]
Why a zip file if we can upload the png file and the csv file as is? I think that this is not so clear for a user how to create a zip file from two files and upload it instead of uploading two files directly.

**Comment by jajodiaraghav** [comment]
We will have an alternate button which will slidedown the form for zip upload. 
Currently the user can only upload one csv at a time. With this, they will be able to upload as many as required in a zip format and get the desired PDF containing all the badges with the corresponding background.

We can surely discuss in case you want changes in the implementation of the feature.

**Comment by jajodiaraghav** [comment]
The ZIp file will contain for instance, 5 csv files, and their corresponding 5 PNG files for their background.
We will document the right format of the zip file to upload.

**Comment by niccokunzmann** [comment]
The CSV file is an indermediate format only. #28 is the real use-case to me. However, if you think this is a real use-case, I will of cause merge. I can not judge that.

**Comment by jajodiaraghav** [comment]
Let's put this on hold until we are done with #28 :)

**Comment by niccokunzmann** [comment]
We can remove the label once #28 has proceeded and you think it should be removed.
