### ISSUE TITLE
Add feature for required status checks

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#230]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
Currently the PR can be merged irrespective of the test passed.

**Expected behavior:**
Make some status checks complusory so as to not allow buggy code to the project

**Comment by S2606** [comment]
@fossasia/badgeyay-admin Please give your views.

**Comment by vaibhavsingh97** [comment]
@S2606 We have travis already but failing 😞 and i tried to fix but locally it's working fine but on travis it's failing. You can collaborate with me or guide me to fix the issue.

**Comment by S2606** [comment]
@vaibhavsingh97 I would love to collaborate but the thing is i currently have exams going on. Can you please wait for a few days?

**Comment by vaibhavsingh97** [comment]
@S2606 I have also exams from 9 😓

**Comment by S2606** [comment]
@fossasia/badgeyay-admin Since travis is now fixed we can set travis status as required

**Comment by gabru-md** [comment]
Sure!

**Comment by meets2tarun** [comment]
@S2606 
Where you are thinking to set Travis status?
How will you verify the status of PR with that?

**Comment by S2606** [comment]
@meets2tarun I am talking about this
![image](https://user-images.githubusercontent.com/18497513/31927437-a5f7f71c-b8b1-11e7-85c1-91fbc1e98041.png)
Only project owner can do this

**Comment by meets2tarun** [comment]
No, its automatic and it automatically happen whenever a new PR has been made.

**Comment by S2606** [comment]
I am talking about the `Required` tag which if you see in the current PR is not there.

**Comment by abishekvashok** [comment]
@S2606 I am closing this down. We can add it when ee fix Travis. Pls reopen by then :)
