### ISSUE TITLE
Add Vagrantfile for Setup using Vagrant

### ISSUE THREAD

**Issue by ananyo2012** [fossasia/badgeyay#235]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Presently developers using Windows OS (Version < Windows 10) find it difficult to do the setup. We can setup a Vagrantfile and install script similar to  https://github.com/fossasia/open-event-orga-server/blob/nextgen/docs/installation/vagrant.md

**Expected behavior:**

Will make it easier for developers using Windows OS to do the setup

**Comment by vaibhavsingh97** [comment]
@ananyo2012 Do you like to work on this?

**Comment by ananyo2012** [comment]
Yes I would like to work on this

**Comment by S2606** [comment]
@ananyo2012 any progress??

**Comment by ananyo2012** [comment]
I am getting many installation failures for certain packages. Trying to
solve them. Sorry I was busy for the past 2 days. Will send a PR for this
soon.
