### ISSUE TITLE
"Select a background" pane misaligned.

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/badgeyay#243]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

The dropdown pane is misaligned

**Expected behavior:**

It should open just below the dropdown button

**Steps to reproduce:**
Click on "Select a background"

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav It's a first timer issue 😄

**Comment by jajodiaraghav** [comment]
I would still like to work on this. There are a bunch of first timer issues. We are not going to run out of them anytime soon
