### ISSUE TITLE
Deploy on Heroku through Travis-CI

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#247]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
Only manual deployment is possible.

**Expected behavior:**
After successful travis build deploy to heroku 

**Would you like to work on this?**
yes

**Comment by S2606** [comment]
To be done after #238

**Comment by S2606** [comment]
Since Travis CI is now working,starting work on this

**Comment by vaibhavsingh97** [comment]
@S2606 Go ahead

**Comment by S2606** [comment]
@vaibhavsingh97 I believe based on gitter group chat you are working on this.Can i know the status?

**Comment by vaibhavsingh97** [comment]
@S2606 I am working on it. Will send PR latest by Today

**Comment by gabru-md** [comment]
@vaibhavsingh97 Please update
