### ISSUE TITLE
Request Timeout error

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#257]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**
``2017-10-07T14:45:20.325137+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/upload" host=badgeyay-dev.herokuapp.com request_id=86410bb4-fb6f-4043-8f30-682c2c321ec9 fwd="27.251.197.195" dyno=web.1 connect=1ms service=30002ms status=503 bytes=0 protocol=https``

**Expected behavior:**
This error should not happen

**Steps to reproduce:**

- use one of the samples for `Upload to csv...`

- Select any background for eg:- team.png

- Click upload

**Comment by S2606** [comment]
@fossasia/badgeyay-admin Need Help..

**Comment by vaibhavsingh97** [comment]
@S2606 Can you please add *Steps to reproduce`. This will help us a lot to reprodice issue and fixing the issue

**Comment by S2606** [comment]
@vaibhavsingh97 Done

**Comment by gabru-md** [comment]
@S2606 Sorry but i cannot seem to replicate this issue on my side
Can you please add a video or something to show the issue with log?
