### ISSUE TITLE
Clarify who needs to be contacted for admininstrative changes

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#26]
Context: I would like to add @meets2tarun to the people who have write access as he is a maintainer.
I would like to add @jajodiaraghav to the people with write access because he has proven to be productive for the project and can merge and review other people's work.

Problem: I do not know who to contact for this.

Two solutions exist:
1. pass admin permissions to me so I can do this.
2. find an other admin to do it, which is also required for 1.

Roadmap
1. Discuss on gitter
2. ping fossasia administrators
3. ping different teams, open-event team first, then others.

**Comment by mariobehling** [comment]
@niccokunzmann Gave you admin access and added them to the team. Keep it up!
