### ISSUE TITLE
Add logs for working progress

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#264]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
There is no such feature which shows uploading process

**Expected behavior:**
A box which would show progress of badge making

**Comment by S2606** [comment]
@fossasia/badgeyay-admin What do you think??

**Comment by vaibhavsingh97** [comment]
yes, we can have proggress bar 👍 but  it can be handled in #210 as i don't think working on this UI would make sense

**Comment by S2606** [comment]
@vaibhavsingh97 After the UI is done.I would like to work on this..

**Comment by S2606** [comment]
And i am talking about progress as in the code execution..

**Comment by meets2tarun** [comment]
@S2606 Here the need of logs for which process is unclear.
And where you are thinking to show the logs?

**Comment by vaibhavsingh97** [comment]
@S2606 How would you going to proceed?

**Comment by S2606** [comment]
@meets2tarun Right when the user clicks the upload button,the process of creating the .pdf and merging them can be shown.
@vaibhavsingh97 I can only start when new UI is created

**Comment by jajodiaraghav** [comment]
The current upload process reloads the page. In order to show progress, we have to upload files asynchronously.

**Comment by djmgit** [comment]
@jajodiaraghav I agree, presently merge_badges is executed as a separate process. Even if it is executed from main.py as a method still I am not sure how we can continuously pass state information(number of badges/pdfs generated) to the view. I guess only way is if we are able to decouple the file uploading process (ajax) or perhaps entire application. In that case we can use ajax requests to constantly poll the state of the server. What do you think? Should we decouple the entire application and go for REST approach?

**Comment by S2606** [comment]
@djmgit using REST approach is useful for integrating with open-event-orga-server as an API.

**Comment by S2606** [comment]
@djmgit @vaibhavsingh97 @ParthS007  Can i start work on this?

**Comment by vaibhavsingh97** [comment]
@S2606 How you are going to proceed? As of now, if the application is executed from `main.py` as a method still how you pass the state to the view continuously to show the logs?

**Comment by meets2tarun** [comment]
One can start to work on the issue then we will track down its progress.

**Comment by Pravandan** [comment]
Why not we separate the frontend from the backend logic and that way if we build the frontend say in React then we can load up asynchronously without the need of reloading the entire page.

**Comment by abishekvashok** [comment]
@S2606 any updates.
@Pravandan the front-end and backend is now seperated

**Comment by S2606** [comment]
@abishekvashok Actually this was last discussed long back and to be honest since the UI is now changed, do we need this?? If yes then once the new version is live, I will send a PR for it. What do you think?

**Comment by abishekvashok** [comment]
Closing it then as this was for an old ui. Thank you.
