### ISSUE TITLE
bad request on uploading

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#271]
After selecting csv file and background and clicking upload, the following page is shown -

![badge](https://user-images.githubusercontent.com/16368427/31335271-71ea5314-ad0f-11e7-80d8-26fc2dbd445c.png)

POST request at /upload returns 404

![404](https://user-images.githubusercontent.com/16368427/31335347-c689bc3e-ad0f-11e7-895d-2073deca7b3e.png)

**Comment by vaibhavsingh97** [comment]
@djmgit This error occurs when the POST method is accessing values that are not in the form. We should check the spelling of form variables and the variables in the respective handler function.

**Comment by jajodiaraghav** [comment]
@djmgit Are you working on this?

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav I am trying to figure it out wil update 😄 and i think meanwhile @djmgit also trying to fix the issue 👍

**Comment by djmgit** [comment]
@vaibhavsingh97 I am trying to figure and I would love to collaborate with @vaibhavsingh97 on this :)

**Comment by vaibhavsingh97** [comment]
@djmgit Can you ping me on gitter

**Comment by djmgit** [comment]
@vaibhavsingh97 sure
