### ISSUE TITLE
Import from Open-Event

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#28]
This service should create badges for evetnyay. This is why it is called badgeyay.
Please allow a flow where I, as an eventyay-user can

1. Export the data from the event for a category of participants (speakers, VIP, orga, ...)
2. import this to the badgeyay frontend
3. choose the background image
4. generate the badges

Hints:

- There is a python file which generates the CSV file from the JSON file: https://github.com/fossasia/badgeyay/blob/ots-eventyay/generate-speaker-csv.py
- This can be tested on actual eventyay Open-Tech-Summit data

**Comment by pushkalkatara** [comment]
Hi, I am new to open source, I am familiar with Flask apps and wanted to contribute to the repository. I have setup the repo on localhost, I wanted to know where I can get the data which is to be exported and imported to badgeyay. A link would be helpful.

**Comment by niccokunzmann** [comment]
For some test data, you can create an event on eventyay and download this. I will generate a anonymous data representing participants of a past event.

**Comment by niccokunzmann** [comment]
[speakers.json-anonymous.zip](https://github.com/fossasia/badgeyay/files/1300904/speakers.json-anonymous.zip)

Here is anonymized data from eventyay.

**Comment by nanspro** [comment]
i would like to work on this issue

**Comment by nanspro** [comment]
Can you describe what shall be done ,fully

**Comment by nanspro** [comment]
also what is the  use of eventyay_export_anonymizer.py
and speakers.json-anonymous.json in our project.

**Comment by nanspro** [comment]
@niccokunzmann

**Comment by nanspro** [comment]
@niccokunzmann  @jajodiaraghav

**Comment by niccokunzmann** [comment]
The anonymizer can be used to anonymize data from existing eventyay events because we can not publish the data of the participants. speakers.json-anonymous.json is such an anonymous json file. It can be used to test the applcation. Real world data shows bugs where test data sometimes does not - e.g. size of result/input, special characters

**Comment by niccokunzmann** [comment]
@jajodiaraghav If you think, this is done, it can be closed. Right, this issues is open too long.
