### ISSUE TITLE
Simplify User Interface

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#283]
- [x] Remove zip as Download Type and only use PDF downloads -> This way we don't need this field anymore. Please remove this field.
![screenshot from 2017-10-21 02-08-00](https://user-images.githubusercontent.com/1583873/31845752-b5b2dbfe-b604-11e7-98b7-9a021f0fb5f6.png)
- [x] Follow the approach of the web app generator (http://opev-webgen-dev.herokuapp.com/) and only show relevant fields according to user choice.
  * Add radio buttons
  * below the buttons show the field according to the choice
![screenshot from 2017-10-21 02-10-01](https://user-images.githubusercontent.com/1583873/31845863-ebb8e670-b605-11e7-9909-8131d53b580b.png)
- [x] Change "Upload a CSV file to generate badges" to "Add a CSV file with the fields Name, Organization, Handle"
- [x] Change "Enter data manually" to "Enter One Name per Line", 
  * Into the box below enter as an example "Eg. Hong Phuc Dang, FOSSASIA, @hpdang"
  * When the user types into the box make the example disappear
![screenshot from 2017-10-21 02-23-19](https://user-images.githubusercontent.com/1583873/31846067-2f81a3dc-b607-11e7-9c0f-28a122f56acf.png)
- [x] Follow the approach of the web app generator and provide three radio buttons and options below as: 
  * Upload a PNG file for badge background Choose File
  * Select from default images Select a background 
  * Select a background color.
- [x] Take out "Enter Eventyay URL and Type". It is unclear what this field is good for.

**Comment by vaibhavsingh97** [comment]
@mariobehling Sure!! in #210 this will be taken care of 👍

**Comment by ParthS007** [comment]
I am working on it

**Comment by vaibhavsingh97** [comment]
@ParthS007 To fix #286, I have to solve this issue partiall. But you can still work on this issue 👍

**Comment by ParthS007** [comment]
I am working on it with @gabru-md  . Will made PR by tommorow

**Comment by ParthS007** [comment]
Closing it reference to #309
