### ISSUE TITLE
Provide info about suitable size and resolution of background png

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#284]
For the field "Upload a PNG file for badge background" it is unclear what size or ratio the png should have. Please provide info as a helper text below the field about best size, ratio and resolution.

**Comment by rupav** [comment]
I would like to work on it.

**Comment by vaibhavsingh97** [comment]
@rupav what I think that we will take care in UI, let me know your opinion on this

**Comment by rupav** [comment]
@vaibhavsingh97 yeah sure. You are talking about the prototype ?

**Comment by vaibhavsingh97** [comment]
Yup!

**Comment by djmgit** [comment]
Okay, so this will be solved as a sub issue of #210

**Comment by ParthS007** [comment]
I am working on it .

**Comment by ParthS007** [comment]
I am now working on this
