### ISSUE TITLE
Add explanation and sample JSON file for "Advanced Config"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#285]
Badgeyay has an Advanced field "Upload a config file (JSON) to customise badges". Please provide some helper text about what can be configured additionally through the JSON file and add a link to a sample JSON file.

**Comment by mohdomama** [comment]
I would like to work on this.
What I propose is  :
- Add helper text (This can be a mouseover text )
- Add a sample json config file in the samples folder and provide its link on the index page, below the ` Choose file` option.

**Comment by mohdomama** [comment]
@vaibhavsingh97 i believe there is  no need of working on this if you are making a new UI ?

**Comment by mohdomama** [comment]
@vaibhavsingh97 I have actually worked and made the changes that I proposed for this issue, but just wanted to confirm would it be right for me to send a PR considering the fact that a new UI is on its way ?

**Comment by vaibhavsingh97** [comment]
Yes, please send PR

**Comment by mohdomama** [comment]
@vaibhavsingh97 please review :smile:

**Comment by ParthS007** [comment]
closing it with reference to #346
