### ISSUE TITLE
Improve Upload button area and rename it to Generate Badges / Show Download in same area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#286]
![screenshot from 2017-10-21 02-44-41](https://user-images.githubusercontent.com/1583873/31846297-d2cd76ae-b609-11e7-9d59-860757a75da8.png)

* Rename "Upload" button to "Generate Badges"
* Correct English and use "Your badges have been created successfully."
* Move the text to the bottom and use the same blue as on https://eventyay.com as a background
* Show a) a progress icon in the "Generate Badges/Upload" area and b) then display the "Download" button in the same area

**Comment by S2606** [comment]
@mariobehling Will fix this..

**Comment by S2606** [comment]
@mariobehling Since we are upgrading the UI of badgeyay,It would be better if we fixed only the first two options.What do you think?

**Comment by vaibhavsingh97** [comment]
@S2606 what I think is that we should take care these options in new UI. Instead of working on this

**Comment by vaibhavsingh97** [comment]
I will send PR for new UI latest by tomorrow

**Comment by vaibhavsingh97** [comment]
Claming this issue 👍

**Comment by djmgit** [comment]
@gabru-md have a look at #323
