### ISSUE TITLE
Choose/change paper size

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#29]
The following paper sizes should be supported:

- A3 (this is currently supported but A4 is more important)
- A4 - this is used in Germany
- ?? - this is used in Singapore

This issue requires some research about:
- where do the next conferences of fossasia take place, which paper format do they use
- what are the dimension of the badges used there? name cards, A6, ???

Please share your research here as it is much appreciated to direct the development flow.
You can implement paper-and badge-sizesfor the different use-cases.

**Comment by S2606** [comment]
@niccokunzmann Wouldnt it be better if we ask for the paper dimensions based on the given options?

**Comment by niccokunzmann** [comment]
@S2606 I would like to understand:
- `better` than what?
- Which are the "given options"`?

**Comment by jajodiaraghav** [comment]
Can we implement this configeration feature within the config JSON file that we are allowing users to upload along with the CSV?

**Comment by niccokunzmann** [comment]
Yes, sounds good.

**Comment by djmgit** [comment]
@niccokunzmann I would like to work on this :)

**Comment by jajodiaraghav** [comment]
@djmgit Any update on this?
