### ISSUE TITLE
Autodeploy project to Heroku

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#3]
Autodeploy project to Heroku on each new merged commit.

**Comment by niccokunzmann** [comment]
For starters, here is a guide. https://devcenter.heroku.com/articles/github-integration

**Comment by jajodiaraghav** [comment]
Can someone without admin access to the repo deploy to heroku? If yes, then I would like to work on this.

**Comment by niccokunzmann** [comment]
There are several things involved:
1. Add a configuration which can be deployed to heroku (possible for people without write access)
2. Create a hook which deploys this to heroku (possible for people with admin right, not me)

So, you can go ahead and create a "deploy to heroku button". If this is done, the admin has alsmost no effort, I believe, to add the hook.

**Comment by jajodiaraghav** [comment]
I was testing the app by deploying to heroku. Link: https://badegyay.herokuapp.com/

The shell script `merge_badges.sh` doesn't work. It failed with error `sudo command not found`
Any idea how to fix this?

**Comment by niccokunzmann** [comment]
Yes, sudo is not available under heroku. The build script needs some packages installed:
https://github.com/fossasia/badgeyay/search?utf8=%E2%9C%93&q=sudo&type=
You can remove this error by installing the packages before with a heroku config, if that is possible. While Heroku runs, you can not change the system too much.

**Comment by jajodiaraghav** [comment]
Here is a little help in case someone wants to work on this:
1. https://github.com/jajodiaraghav/badgeyay/blob/heroku/Aptfile
2. https://github.com/jajodiaraghav/badgeyay/blob/heroku/Procfile
3. Add gunicorn in requirements.txt
4. Add symlink of requirements.txt in root folder

**Comment by S2606** [comment]
@jajodiaraghav I will work on this
