### ISSUE TITLE
Option to change text colour of details printed on badge

### ISSUE THREAD

**Issue by ananyo2012** [fossasia/badgeyay#308]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

 I would like a feature where I can choose a specific color of text that goes with the background. Is there a way to do it ? If no we should implement it.

**Do you want to work on this issue ?**
Yes

**Comment by abishekvashok** [comment]
Unassigning due to inactivity.

**Comment by rupav** [comment]
Claiming this then. @abishekvashok .

**Comment by abishekvashok** [comment]
Okay @rupav pls carry on

**Comment by rupav** [comment]
Working on it, max. 2 days for PR.
