### ISSUE TITLE
Installation Error in OS

### ISSUE THREAD

**Issue by bodhwani** [fossasia/badgeyay#312]
OSError: cannot load library libcairo.so.2: dlopen(libcairo.so.2, 2): image not found.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2

**Comment by S2606** [comment]
Which os are you using @bodhwani ?

**Comment by bodhwani** [comment]
macOS Sierra(version 10.12)

**Comment by S2606** [comment]
Have you tried installation using Virtual Environment??

**Comment by bodhwani** [comment]
Yes! All libraries installed successfully. While running main.py file, its giving error

**Comment by gabru-md** [comment]
Try this :
```sh
brew install cairo
brew install pango
```
Maybe this will solve the problem.

Have a look here : https://stackoverflow.com/questions/28211418/python-oserror-cannot-load-library-libcairo-so-2

**Comment by ParthS007** [comment]
closing this as no further  queries are asked .

**Comment by rupav** [comment]
For Window Users, if you have conda package, `conda install cairo` will do.
