### ISSUE TITLE
Travis Build is failing

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#318]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Travis build is failing beacuse of some test cases is failed

**Expected behavior:**
Travis Build should pass

**Yes, I am interested in solving this issue**

**Comment by S2606** [comment]
@vaibhavsingh97 I think this should be solved after #309

**Comment by vaibhavsingh97** [comment]
@S2606 Travis is failing there too, so in my opinion we should merge that PR and work on travis afterwords. What's your opinion?

**Comment by harshit98** [comment]
@vaibhavsingh97 Is it still failing?

**Comment by vaibhavsingh97** [comment]
Yes, I will probably fix it by today. Delay is due to I am not well

**Comment by harshit98** [comment]
@vaibhavsingh97 Please let me know if you need help from my side. 👍

**Comment by vaibhavsingh97** [comment]
@harshit98 Fixed the issue in #334 😄
