### ISSUE TITLE
Reduce width of flash message and centre text

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#323]
Presently the width of the flash message is much larger than the width of the container and the text is not centre aligned. Reduce the width and centre the text,
![width](https://user-images.githubusercontent.com/16368427/32584531-bf67be5c-c51e-11e7-8688-497408e8ac18.png)

**Comment by S2606** [comment]
Can i work on this @djmgit ??

**Comment by djmgit** [comment]
@S2606 I have no problem :) @vaibhavsingh97 are you working on this?

**Comment by vaibhavsingh97** [comment]
Yes, will fix with #286

**Comment by ParthS007** [comment]
closing it with reference to #286
