### ISSUE TITLE
Make generate badges button one-time clickable

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#325]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
The button is clickable more than once

**Expected behavior:**
Should be one-time only

**Comment by rupav** [comment]
Can I work on it ?

**Comment by S2606** [comment]
@rupav I am working on it..

**Comment by vaibhavsingh97** [comment]
@S2606 in #286 it will be taken care of. Can you please close this for now

**Comment by ParthS007** [comment]
closing it in reference to #286
