### ISSUE TITLE
Merging of UI branch into development 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#327]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request

**Current behavior:**
Currently, UI changes in PR #309 is present in UI branch.

**Expected behavior:**
I want it to merge with development branch as it is not possible to do changes in both branch simultaneously because when we want to merge UI into development, there will be large merge conflicts . My view is to merge it and do changes in only one branch.

I want your views @jajodiaraghav @vaibhavsingh97 @djmgit @gabru-md @S2606 .Please respond to it as merge conflicts will increase with merging PRs in the development branch .

**Comment by mariobehling** [comment]
Absolutely. Please go ahead.

**Comment by vaibhavsingh97** [comment]
@ParthS007 Please proceed with merge

**Comment by jajodiaraghav** [comment]
Please go ahead!
I think the best way is to merge UI branch to development and then continue the dev process in the development branch itself.

**Comment by gabru-md** [comment]
@ParthS007 please merge this. 
And @vaibhavsingh97 are the changes auto deployed on heroku ?

**Comment by vaibhavsingh97** [comment]
@gabru-md Yes! can send dummy PR to check that 😅 
P.S: Change title to `badgay-dev`

**Comment by ParthS007** [comment]
closing it
