### ISSUE TITLE
Document how to use the file from #32

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#33]
**I'm submitting a ...**  (check one with "x")
- [X] bug report

**Current behavior:**

I do not know how to use to file.

**Expected behavior:**

I would like to read in the REAME file about the meaning of the file and the project guidelines which seem to be mainfested in the file.

**Related code:**

#32

**Comment by S2606** [comment]
@niccokunzmann This file is for linting as you know we have identation issues in Python. this file helps in maintaining one code style. Also this file is being automatically read by EditorConfig plugins of different IDE's and suitable adjustments are being made.

**Comment by S2606** [comment]
@niccokunzmann Since i have clarified your doubt can we close this issue?

**Comment by jajodiaraghav** [comment]
Hi, I think that we are asking for too much data in ISSUE_TEMPLATE
I think we can delete:
Related code, Other information & System information part

I would like to know what others think :)

**Comment by S2606** [comment]
@jajodiaraghav  yeah I think it needs to be removed. Sending an PR

**Comment by niccokunzmann** [comment]
@S2606 

> Since i have clarified your doubt can we close this issue?

No. Documentation should be in a file and not in a closed issue.
I would accept `#` comments describing how to use the file. Specifically I would like to

- [ ] have your issue comment as a comment in this file
- [ ] have a link to at least one plugin you claimed exists in this description

In case you want other people to follow your guidelines, a plugin-description might not be enough for people to realize that the guidelines are something we strive to achieve and thus they could be prominently presented, explained and motivated in the README file.

**Comment by S2606** [comment]
@niccokunzmann can i just provide the link regarding this?? it essentially contains things required?

http://editorconfig.org/#download

**Comment by niccokunzmann** [comment]
Sure, this link is even more helpful!
