### ISSUE TITLE
Allow all image files and show only image files to select as background images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#339]
Please change the functionality to choose background images as follows:
* currently only png files can be chosen, change to: All image files
* browsing files to choose shows "all" files to the user. Change to show "only image files".

![screenshot from 2017-11-12 08-21-04](https://user-images.githubusercontent.com/1583873/32696840-ffa0f9b4-c782-11e7-8050-6f517ccbed08.png)

**Comment by S2606** [comment]
claiming this issue..
