### ISSUE TITLE
User defined image shows up instead of background color

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#340]
When a user opens the background color option, a user defined image shows up instead the background color info. Expected: Only show background color. Don't show user-defined.png.

![screenshot from 2017-11-12 08-26-59](https://user-images.githubusercontent.com/1583873/32696862-6547a7ae-c783-11e7-9310-6700f4efcf23.png)

**Comment by djmgit** [comment]
Will work on this

**Comment by djmgit** [comment]
@mariobehling when a user selects a default image from the background, he is able to see the sample image (as small icons in drop down). But when he wants to use image with custom colour (colour set by him), he is able to see the colour (the colour picker shows that), but how should the app show him the image he is using, that is the image whose colour he is setting? I mean if we remove the image from there, then what is a suitable way of showing the sample image or should we not show him the sample image at all?

**Comment by ParthS007** [comment]
@mariobehling Can you please tell what exactly have to be done? 
Permanent removal of user-defined png or something else.

**Comment by ParthS007** [comment]
@djmgit  I think We have to remove user-defined PNG and only show color which is shown by color picker.Working on this :+1:

**Comment by djmgit** [comment]
@ParthS007 I guess removing the user-defined image will be enough, since the color is already shown bu the picker. What I mean is, we do not need to show the color separately.

Yeah sure, please send a PR :+1:

**Comment by ParthS007** [comment]
@djmgit Please merge #372 so that I can proceed with this issue.
