### ISSUE TITLE
Add JSON sample data that makes sense

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#341]
In the guide there is JSON data, that does not make a lot of sense. Please add data using FOSSASIA links, e.g. Twitter: @fossasia.

![screenshot from 2017-11-12 08-34-12](https://user-images.githubusercontent.com/1583873/32696921-8a76c9f0-c784-11e7-9cbd-a31b8e147c79.png)

**Comment by S2606** [comment]
Claiming this issue..
