### ISSUE TITLE
Take out indent to use space more efficiently

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#345]
The indent of sub items is not required. More and more functionality is added and we need space for that. Therefore please take out the indent of sub-items.

![screenshot from 2017-11-12 09-00-48](https://user-images.githubusercontent.com/1583873/32697078-22ad27fc-c788-11e7-8a1c-80656e9c253c.png)

**Comment by S2606** [comment]
@vaibhavsingh97 any reason for reopening??

**Comment by vaibhavsingh97** [comment]
@S2606 Problem with heroku. Now fixed don't know it's waiting for travis and travis already passed the PR. Now fixed the issue 👍

**Comment by mariobehling** [comment]
The PR is not matched with the issue and the change made is not as desired. The goal was to change the indentation. The goal was not to change the space between the button and the following text. Therefore I am reopening it. 

Please make it easier to follow up and stick to best practices.

![screenshot from 2017-11-18 22-19-35](https://user-images.githubusercontent.com/1583873/32984856-9dcafdbc-ccae-11e7-9061-7524b2bc65a7.png)

**Comment by raju249** [comment]
Anyone working on this issue ?

**Comment by raju249** [comment]
Claiming this if no one is active on this!

**Comment by raju249** [comment]
Sorry, my bad, its fixed

**Comment by raju249** [comment]
Why is this issue open yet ?
@vaibhavsingh97 
/cc @mariobehling

**Comment by vaibhavsingh97** [comment]
Closing, since this issue is fixed
