### ISSUE TITLE
Take out "Customise Badges (Optional)"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#346]
Customise Badges seems to be overkill for the app at the moment. If a set of JSON is needed as a feature it can be added later.

Right now the app needs to focus on getting the basic features right.

Take out "Customise Badges (Optional),  Add Custom text,  Add JSON file"

**Comment by rupav** [comment]
I am working on this issue.

**Comment by ParthS007** [comment]
working on this due to inactivity
