### ISSUE TITLE
Generated badge size wrong (too small)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#347]
Badges are generated as a set. The idea is to fold them in the middle and have the badge in the plastic showing the info in both directions.

Currently the badges are generated as A6. One side of the badge is A6. Two sides of the badge should use the space of A5

As we are printing back and front the display is to small. The badges should be generated as A5.

**Comment by S2606** [comment]
Claiming this.. :)

**Comment by ParthS007** [comment]
closing this in reference to #817
