### ISSUE TITLE
Add option to "Select Badge Size" and implement A6 and A7

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#349]
Right now we have only one size which is A6 (one sided) and A5 (if both sides are printed on one page). Please add a section "Select Badge Size" after the section "Choose Data Source and in front of section "Choose your Badge Background".

![screenshot from 2017-11-12 10-08-05](https://user-images.githubusercontent.com/1583873/32697485-6f2c20a2-c791-11e7-8b2b-962e1c610d66.png)

* Add radio buttons for two sizes for now:
  * A6 (horizontal)
  * A7 (horizontal)

* Add a tick box to print the badge as foldable item twice, which is the current implementation
  * [ ] Print badge twice on page as foldable item

**Comment by S2606** [comment]
@mariobehling I think we dont need #347 since this issue can be handled here.. BDW claiming this

**Comment by nityanandagohain** [comment]
Can i work this issue .

**Comment by S2606** [comment]
@nityanandagohain i am working on this

**Comment by abishekvashok** [comment]
@S2606 any updates?

**Comment by abishekvashok** [comment]
@S2606 take your own time, we don't mind it but we need to be sure that you're intrested

**Comment by ParthS007** [comment]
Closing this as completed :+1:  
Reference to #954
