### ISSUE TITLE
Add options like speaker, guest etc. to be drawn from CSV instead of hardcoding it in the image

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#351]
Currently the default images are showing the name and logo of the event (here FOSSASIA) and the speaker, guest, camera crew etc.

Instead implement as follows:
* Add item for role into CSV or manual box, e.g. Hong Phuc,Dang,Organiser,@hpdang,FOSSASIA
* Change images and take out FOSSASIA logo and roles, e.g. speaker
* Also rename background image to color and theme item. Use e.g. "gray_futuristic", "red_futuristic"

**Comment by djmgit** [comment]
Working on this

**Comment by ParthS007** [comment]
working on this due to inactivity 👍

**Comment by djmgit** [comment]
@ParthS007 please go ahead :+1:

**Comment by ParthS007** [comment]
giving PR by Wednesday 👍
