### ISSUE TITLE
Implement a badge preview

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#353]
Eventbrite and other solutions have a simple badge preview below.

Please implement a badge preview in the same fashion.

![screenshot from 2017-11-12 10-32-20](https://user-images.githubusercontent.com/1583873/32697618-df7ba5a0-c794-11e7-9cd3-861f29ca23db.png)

**Comment by jajodiaraghav** [comment]
Claiming 🚀

**Comment by harshit98** [comment]
@jajodiaraghav What's the status of this issue? Can I work on this?

**Comment by jajodiaraghav** [comment]
@harshit98 You can take this one

**Comment by gabru-md** [comment]
@harshit98 If you are not working on this issue I would like to give it a try.

**Comment by vaibhavsingh97** [comment]
Reopening as partially fixed

**Comment by rupav** [comment]
@vaibhavsingh97 #443 take care of this issue. This can be closed then?

**Comment by abishekvashok** [comment]
@vaibhavsingh97 can you update on what more is required pls?

**Comment by abishekvashok** [comment]
@vaibhavsingh97 i am closing this now as I feel it's fixed. If you don't think so pls reopen it :)
