### ISSUE TITLE
Implement Rest-API for all functionalities

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#356]
The goal of the API is to enable us to completely access the functionality of the app through an API, e.g. by eventyay.

**Comment by djmgit** [comment]
@jajodiaraghav @S2606 @gabru-md this has already been added as a GCI task. If you guys are interested to mentor, please add your names here : https://docs.google.com/spreadsheets/d/1Y0nxuV_nJfj4MMqfrLZGs1ZN68xvwyEvlejQkksFE0U/edit#gid=0
task no. 164

**Comment by abishekvashok** [comment]
Closing this as the api as part of the gci task was added.
