### ISSUE TITLE
Seperate front-end and backend / Create front-end using emberJS

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#357]
Please seperate front-end and backend. Create a folder for the front-end. Use ember JS as front-end technology.

**Comment by djmgit** [comment]
@jajodiaraghav @S2606 @vaibhavsingh97 @gabru-md @ParthS007 should we also add this issue as a GCI task? The REST api part is already a GCI task and this issue too will be a nice advanced task as it is comprehensive enough. What do you guys feel?

**Comment by S2606** [comment]
@djmgit Yes we should add this as GCI Task.

**Comment by gabru-md** [comment]
I agree with this. This will help students learn a new framework as well.
I would love to know the thoughts of other maintainers.

**Comment by vaibhavsingh97** [comment]
@djmgit Agreed 👍

**Comment by jajodiaraghav** [comment]
I am not sure a GCI student would be able to create the entire frontend using EmberJS. Lets still add this as a task and see how this goes.

**Comment by ParthS007** [comment]
agreed with @djmgit  but it will difficult for them as said by @jajodiaraghav.

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav yes, you are right and we are here to guide them and we will work with the student so that's not an issue.

**Comment by anshumanv** [comment]
This can probably go as an advanced task.

**Comment by djmgit** [comment]
Yup, added it as an advanced task, any GCI mentor who is interested in mentoring please add your name in task 189 here : https://docs.google.com/spreadsheets/d/1Y0nxuV_nJfj4MMqfrLZGs1ZN68xvwyEvlejQkksFE0U/edit#gid=0

**Comment by anshumanv** [comment]
Alright, just added @djmgit :+1:

**Comment by gabru-md** [comment]
@anshumanv @djmgit add my name as well.
I'm a bit busy due to my exam today. So if guys could add mine for me ?

**Comment by anshumanv** [comment]
Added @gabru-md :tada:

**Comment by abishekvashok** [comment]
Closing this as it was done and the backend and front-end folder exists in the development branch as for now.
