### ISSUE TITLE
Adding icon linked to susper.com in the top right menu

### ISSUE THREAD

**Issue by marvin08** [fossasia/badgeyay#366]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There is no icon of susper in the top right menu.

**Expected behavior:**
There should be a icon linked to susper.com in the top right menu.

**Would you like to work on this issue?**
Yes.

**Comment by marvin08** [comment]
Suggestions required @vaibhavsingh97 @gabru-md @S2606 @djmgit. Should I take this up?

**Comment by harshit98** [comment]
@marvin08 Yes. Please go ahead.
