### ISSUE TITLE
Vagrant setup not helpful.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#373]
**I'm submitting a ...**
- [x ] bug report
- [ ] feature request

**Current behavior:**

Following the installation steps of Vagrant.

**Expected behavior:**

Badgeyay in local host should have same functionality as https://badgeyay-dev.herokuapp.com/
My local repo is up-to date, still 
![2017-11-23 2](https://user-images.githubusercontent.com/20624380/33172789-84a59ad2-d077-11e7-81b5-6293e53b3163.png)

**Generate Badges** is disabled whatsoever you give input.
This file contains all the verbose in cmd during installation process.
[cmd vagrant installation.docx](https://github.com/fossasia/badgeyay/files/1498988/cmd.vagrant.installation.docx)

**Steps to reproduce:**
Windows 10 OS 64-bit
Just Follow the installation step of Vagrant setup.

**Comment by rupav** [comment]
**PS:** It started working out of the blues only 1 time (was able to generate badges), but then i had to shut down, so 
`vagrant halt`. From then `vagrant up, vagrant ssh ` and following other commands are not generating the correct deploy. I even reinstalled to check but it wasn't helpful too.

**Comment by rupav** [comment]
@ananyo2012 please help, having problems using Vagrant.

**Comment by ananyo2012** [comment]
@rupav Are you able to start the badgeyay server successfully ?

**Comment by rupav** [comment]
@ananyo2012  Yeah, I have posted a screenshot of that too. But see the difference with original deploy. Also 'Generate Badges' button is blocked.

**Comment by vaibhavsingh97** [comment]
@rupav Button will be blocked until you add both CSV and PNG background

**Comment by rupav** [comment]
@vaibhavsingh97 I tried that too, I have mentioned that in the issue message itself, whatever I give input generate badge is blocked.

**Comment by ananyo2012** [comment]
@rupav Since you got the website running the packages got installed correctly. Can you post the logs you get when try to generate the badges ?

**Comment by rupav** [comment]
@ananyo2012 I am not able to generate badges because of blocked button. Also please look how the look of deploy is different from the original heroku deploy (indentation problem, extra lines : "Please upload csv ...", "please select a default background...."). 
Are you able to generate badges using vagrant with windows as host OS?
I have attached log too while setting up vagrant. Found these unusual:

- default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
-     default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
- default:
    default:     warning: no previously-included files matching '*' found under directory 'docs/_build'
-     default:
    default:     warning: no previously-included files matching '*' found under directory 'docs/_build'
    default:     warning: no previously-included files matching '*.pyc' found under directory 'tests'
- default:     warning: no previously-included files matching '*.pyc' found under directory 'tests'

**   ` default:     warning: no files found matching '*.sh'
    default:     no previously-included directories found matching 'docs/_static'
    default:     warning: no previously-included files found matching '.coveragerc'
    default:     warning: no previously-included files found matching 'codecov.yml'
    default:     warning: no previously-included files found matching '.editorconfig'
    default:     warning: no previously-included files found matching '.landscape.yaml'
    default:     warning: no previously-included files found matching '.travis'
    default:     warning: no previously-included files found matching '.travis/*'
    default:     warning: no previously-included files found matching 'appveyor.yml'
    default:     warning: no previously-included files found matching 'build_children.sh'
    default:     warning: no previously-included files found matching 'tox.ini'
    default:     warning: no previously-included files matching '.git*' found anywhere in distribution
    default:     warning: no previously-included files matching '*.pyc' found anywhere in distribution
    default:     warning: no previously-included files matching '*.so' found anywhere in distribution
`
**
and similar type errors/warning.

**Comment by ananyo2012** [comment]
@rupav Yes I am running badgeyay in Windows 7 OS with vagrant with Oracle virtualbox provider. I am successfully generating badges. These are warning and can be safely ignored. Since you are successfully run the server there doesn't seems to be problem with vagrant setup.

If you look at `index.html` you will see the page is exactly similar to that of the deployed version. The only differnce some of the hidden fields are displayed. Probably there is some javascript error that is occuring that is not enabling the `Generate Badges` button. Can you say which browser you are using and can you check whether javascript is enabled in your browser?

**Comment by rupav** [comment]
@ananyo2012  sorry for late reply.  I tested it on `Firefox` browser and I dont know what exactly I have to look into `about:config` to see if JS is enabled.
I will try again on Microsoft Edge and Firefox.

**Comment by rupav** [comment]
@ananyo2012 It is working 😁. Thanks for your help. I dont the reason of it working earlier. But now its working fine.
what do you suggest : `vagrant halt` or `vagrant suspend` ?

**Comment by ananyo2012** [comment]
I usually use `vagrant halt` for shutting down the vm.

**Comment by rupav** [comment]
@ananyo2012 @vaibhavsingh97 thanks one gain for your time and helping me setting up badgeyay. :)
Closing this issue now.
