### ISSUE TITLE
Add custom font for creation of badge

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#374]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There is only one defined font used for creation of the badge.

**Expected behavior:**
We can have different font options as per the user preference

**Comment by rupav** [comment]
Yes that's a great idea ! According to event type, user can change the font. 
Can I work on it ?

**Comment by yashLadha** [comment]
I am working on this. Sorry @rupav
