### ISSUE TITLE
Auto deployment using Surge 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#377]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behavior:**
After auto-deployment, It will be easy for reviewers to review PR as deployment link is generated automatically.

**I am working on this Issue**

**Comment by raju249** [comment]
I think surge is best suited for static hosting. And badgeyay is not static website.
What you think ?

**Comment by djmgit** [comment]
@ParthS007 @raju249 Yes, surge allows only static hosting I guess. You will not be able to host back end logic. Surge can be used when the site has been separated into api and front end. Then we can use surge or netlify for for front end hosting.

**Comment by raju249** [comment]
Exactly

**Comment by ParthS007** [comment]
Thanks @raju249 @djmgit . I was new to Surge that's why I thought of implementing it on badgeyay.Since it is not a static web app, Surge cannot be implemented on it so closing this issue , will implement on Surge when we have a separate front-end
