### ISSUE TITLE
GCI Task: Code Formatting 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#378]
- **Objective**: Many python scripts don't have proper indentation and comments.The task is to choose one file and leave comments in the code after the proper understanding of the code and remove empty and unnecessary lines.The overall aim is that the code looks neat and tidy.

- **Requirements**: Code formatting, Python, Git
- **Expected Outcome**: A pull request with a properly formatted and neat version of the code of any one file of the codebase.
- **Type**: Code
- **Time to Complete the task in days** : 5

**Comment by ParthS007** [comment]
@djmgit @vaibhavsingh97 @harshit98 Please make a label as GCI task and apply to it. Thanks

**Comment by ParthS007** [comment]
:+1:

**Comment by YashKumarVerma** [comment]
working on it!

**Comment by YashKumarVerma** [comment]
@ParthS007 the comments should explain the code or their function ?

**Comment by YashKumarVerma** [comment]
can i work on this file ? 

https://github.com/YashKumarVerma/badgeyay/blob/development/app/generate-badges.py

**Comment by Aryan9101** [comment]
I claim this task too. What specific file do you want me to work on?
