### ISSUE TITLE
GCI Task: Code refactor and updation

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#379]
## Objective
Updating app/generate-badges.py so that it can be used as a library and can be imported from another file. At the same time provision should be kept for executing and running the file as a stand alone module so that the present system is not broken.

## Requirements
- A github account
- Knowledge of Git
- Basic knowledge of python.
- Clone the badgeyay repository
- Understand the code flow in generate-badges.py . 
- Create  a suitable issue for this task here.
- Create a new branch.
- Make changes.
- Add and commit your changes. Provide a suitable commit message.
- Send a pull request.

## Expected outcome
Submit a pull request with changes

**Comment by abishekvashok** [comment]
@djmgit we should make generate-badges.py a module and implement it as a module throughout badgeyay right?

**Comment by djmgit** [comment]
@abishekvashok exactly, after that we should be able to import and use generate-badges.py module from merge-badges.py

**Comment by abishekvashok** [comment]
So should i do that as well? If i work on this.

**Comment by djmgit** [comment]
@abishekvashok if you want  to do it then please go for it :)

**Comment by abishekvashok** [comment]
I will give it a try.
