### ISSUE TITLE
GCI Task: Remove usage of pdftk and use pypdf

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#380]
## Objective
Presently the project used a non python library called pdftk to merge pdf files. So every time we need to merge pdf files we have to use pdftk as a separate process via subprocess as it is not available as a native python library. Also it involves the usage of some shell commands which creates problem for windows. However there is a very nice native python library present known as pypdf which allow us to work on pdf files including their merging. The objective of this issue is to remove the usage of pdftk and use pypdf in place of it.

## Requirements
- A github account
- Knowledge of Git
- Basic python knowledge
- Clone the badgeyay repo.
- Create  a suitable issue for this task here, comment that your are working on it.
- Create a new branch.
- The file named merge_badges.py uses pdftk. Remove its usage. The desired implementation is already 
- present in merge_badges_v2.py. You may go through it to find out how to solve this task.
- Add and commit your changes. Provide a suitable commit message.
- Send a pull request.
- Post a screenshot of your code on twitter.

## Expected Outcome
- A pull request with the necessary change done.
- Tweet a link and screenshot of your code to @fossasia @mariobehling @hpdang @gci and/or share it on Facebook or any other social media

**Comment by abishekvashok** [comment]
@djmgit can I work on it? Looks interesting.

**Comment by djmgit** [comment]
@abishekvashok Sure, please go ahead, but before sending a PR, please claim the corresponding task on GCI website, and then send the PR.

**Comment by abishekvashok** [comment]
@djmgit sure
