### ISSUE TITLE
Implement Yaydoc docs generation in badgeyay

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/badgeyay#382]
Yaydoc is FOSSASIA's own automatic documentation generation and deployment project. At the crux of it, Yaydoc generates a documentation website using the markdown present in a project's repository and keeps the website in sync with the changes made in project's documentation.

The project requires a .yaydoc.yml configuration file at the project's root directory. Adding necessary information in the configuration file and registering the project at https://yaydoc.herokuapp.com/ will be enough to generate the documentation website.

**Objective:** Create the .yaydoc.yml file in the badgeyay repository and show preview Documentation website generated from the Yaydoc website.

**Expected Outcome:** Submit a pull request creating .yaydoc.yml file and a link to the preview page

**Links:** http://dev.yaydoc.org/user_manual/yaydoc_configuration.html

**Comment by abishekvashok** [comment]
@djmgit @imujjwal96 can I work on it?

**Comment by abishekvashok** [comment]
@imujjwal96 @djmgit done in #411 pls review.
