### ISSUE TITLE
Local deployment using Docker is not working.

### ISSUE THREAD

**Issue by harshit98** [fossasia/badgeyay#394]
I was setting up the local deployment of badgeyay using Docker. It gives error whenever `RUN pip install --no-cache-dir -r requirements.txt` line comes. 

`ERROR: pip not found
The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 127`

**Comment by ParthS007** [comment]
I will correct it @harshit98 👍
