### ISSUE TITLE
Duplicate badges

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#4]
Presently duplicate badges are being generated, is this intentional? If not then I would like to fix this.

**Comment by djmgit** [comment]
[badges_1.svg.zip](https://github.com/fossasia/badgeyay/files/1289781/badges_1.svg.zip)

**Comment by niccokunzmann** [comment]
Good question! This is to fold them in the middle, stick them into the badge holder and have the same badge regardless of wether you turn it around.

**Comment by niccokunzmann** [comment]
There could be an option, though.. Maybe some people do need it only on one side.

**Comment by djmgit** [comment]
@niccokunzmann yeah, if some one needs it on only one side then it is use less to print an extra image.
How about including a config file, maybe a config.json or config,csv and mentioning this in that, or we may use  a switch (via optparse) ?

**Comment by niccokunzmann** [comment]
You can go for what you think is best.

**Comment by djmgit** [comment]
@niccokunzmann okay, I am working on it.

**Comment by niccokunzmann** [comment]
#5 intorduced a web UI. Thus adding a JSON configuration could be handy as it can be generated by the website, too. @jajodiaraghav How would you like to configure the badge generation?

- Command line Parameters
- JSON

**Comment by jajodiaraghav** [comment]
@niccokunzmann Best would be to use JSON just like we use in other projects. In case there is a requirement of a CMD line params, we can integrate in later :)
