### ISSUE TITLE
Need of a webapp

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/badgeyay#40]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

A web app made up of flask deployed on Heroku which will trigger Travis with the required configuration to get required badges as a Github Release and provide it to the users.
@niccokunzmann

**Comment by jajodiaraghav** [comment]
Hi @meets2tarun 
We already have a web app. Another issue has already been opened that specifies deployment in heroku

**Comment by jajodiaraghav** [comment]
Run the app using `python app/main.py`

**Comment by meets2tarun** [comment]
Yes, ok
But I'm asking to provide a GUI which can be easily accessed and used by a one who doesn't know to code.

> Run the app using python app/main.py

It may result in dependencies problem too.

**Comment by jajodiaraghav** [comment]
So is this issue similar to #3 ?

**Comment by meets2tarun** [comment]
@jajodiaraghav 
Absolutely not!

**Comment by niccokunzmann** [comment]
@meets2tarun In which way is this different to #3 ?

**Comment by gabru-md** [comment]
So you want a drag and drop sort of UI that takes an image and then outputs the badge ?

**Comment by gabru-md** [comment]
As discussed , this issue can be closed!
PS : @jajodiaraghav  @vaibhavsingh97 @S2606
