### ISSUE TITLE
Build a auto local deployment script

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/badgeyay#412]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
It takes plenty of time in installing **badgeway**.
We should make the installation process easier to fasten up the development rate!

**Expected behavior:**
A `build.sh` script that'll install **badgeyay** in one shot :tada:

**Comment by raju249** [comment]
I think the instructions are pretty explanatory for local installation. There can be other consequences using bash script, which can vary depending on user configuration. A bash script would help if we had used some kind of VM for our application using vagrant or other manager.

@vaibhavsingh97 @djmgit what you guys think ?

**Comment by yashLadha** [comment]
Exactly @raju249 . You have to check for the dependencies that exists in the repositories or not. Different systems have different package managers. Keep in mind that the install instructions differs for different os. Try to mind that case, that not to be centric with one distribution. Like manjaro uses pacman, Debian/Ubuntu uses apt, Fedora uses dnf or yum. Also there is a need to check for the existing dependencies installed or not like python and pip. Showing correct messages for the installation of them.

**Comment by raju249** [comment]
Yes @yashLadha .
@0x48piraj please make a note of what @yashLadha said.
If you really want to automate the installation then try thinking using some VM. But IMHO, a VM for badgeyay seems an overkill.
Let me know what you guys think.

**Comment by 0x48piraj** [comment]
@raju249 @yashLadha Thanks a lot on raising this issue!
I was thinking of making a script that will detect all kinds of OS'es and then will launch the native commands :wink: 
But, It will take time, and as @raju249 said, The documentation is well written! :heart: 

Should I close this ?

**Comment by yashLadha** [comment]
If you think you can GFI @0x48piraj

**Comment by 0x48piraj** [comment]
Ok, As you say so :blush:

**Comment by harshit98** [comment]
> Exactly @raju249 . You have to check for the dependencies that exists in the repositories or not (of specific OS). Different systems have different package managers. Keep in mind that the install instructions differs for different os. Try to mind that case, that we do not have to be centric with one distribution. Like manjaro uses pacman, Debian/Ubuntu uses apt, Fedora uses dnf or yum. Also there is a need to check for the existing dependencies installed or not like python and pip. Showing correct messages for the installation of them.

Yes. Even I agree with this.

> I think the instructions are pretty explanatory for local installation.

Yep. Already there are other deployment methods as well. But I know, it is pretty tiring to write too many commands. To avoid that, we're already working on docker. It's almost done. So, I'm closing this issue.

**Comment by 0x48piraj** [comment]
That's why I asked at first :wink: 
I started writing code, coded upto linux, ubuntu, and fedora.
But, Yes! It's wise to close this issue, it's effective, but at the same time it's outdated :+1:
