### ISSUE TITLE
Bottom bar comes of the top, both in the app & `info` and `guide_manual.png` is messy.

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/badgeyay#418]
**I'm submitting a ...**
- [x] bug report(s)
- [ ] feature request

**Current behavior:**
* Multiple bugs in bottom bar.
> It floats when `textfield` is manipulated.

![badgeyay_issue](https://user-images.githubusercontent.com/5800726/34042506-0679199c-e1c3-11e7-9f1f-974a1bf1bdd3.gif)

* When we click on `info`, the bar comes in between the screen and stays there.
![image](https://user-images.githubusercontent.com/5800726/34073238-34638984-e2bb-11e7-9cdf-a86676c2eeff.png)

---
* **Image is messy and ill-presented.**
![image](https://user-images.githubusercontent.com/5800726/34073221-cf29699e-e2ba-11e7-899e-27a920452366.png)

**Expected behavior:**
* It should stick to the bottom :+1:  _(for 1 & 2)_
* The image should be re created. :smile: 

**Steps to reproduce:**
See the **GIF**. :wink: 

## WIP

**Comment by sagar-kalra** [comment]
@0x48piraj I want to take this issue.

**Comment by 0x48piraj** [comment]
@sagar-kalra Please don't I still have to update and add some more test cases!
Also, It's rather a small task, so It will not get approved also. :wink:

**Comment by sagar-kalra** [comment]
@0x48piraj Sorry for that
I ll hold this PR and will add commits as soon as you enter more test cases.

**Comment by 0x48piraj** [comment]
I have claimed it my dear :wink:

**Comment by 0x48piraj** [comment]
I asked in the channel, and they said, we should raise independent issues. So I raised one by one.
I too wanted to do and file a single issue, you can see the gitter channel.
BTW, 

> Also, avoid the use of too many emojis.
Duly noted!

**Comment by 0x48piraj** [comment]
@harshit98 I updated my issue and am currently working on a **PR**
And, @sagar-kalra your **PR** was broken, I checked it. The bar was still going up. :smile:
Please close your PR.

**Comment by 0x48piraj** [comment]
Ping @harshit98

## https://github.com/fossasia/badgeyay/pull/421 :smile_cat:
