### ISSUE TITLE
PDF not generating

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#420]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
Badges PDF are not generating.

**Expected behaviour:**
PDF should generate after giving required Input.
![image](https://user-images.githubusercontent.com/24358501/34062858-c7d7463a-e214-11e7-9343-cebef08c6d07.png)

I think this is due to #410. I am checking this.

**Comment by vaibhavsingh97** [comment]
Issue exists 👍

**Comment by gabru-md** [comment]
I did comment on that PR fir a working link. 
It must be made compulsory in any case. It helps ease the review and find potential UI/UX bugs

**Comment by ParthS007** [comment]
I understand @gabru-md 😄

**Comment by yashLadha** [comment]
It has been fixed in #384 . It is due to rename of filename at the flash message. @ParthS007

**Comment by yashLadha** [comment]
Here is the deployed link https://glacial-woodland-76361.herokuapp.com/

**Comment by 0x48piraj** [comment]
I and @yashLadha were working on this, he solved this issue :+1: 
We should close this, check his deploy link  :+1:
