### ISSUE TITLE
Repetition in README.md

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/badgeyay#425]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
There are two times "installation" section in README.md
![badge yay iss](https://user-images.githubusercontent.com/33794760/34081547-36c54758-e374-11e7-8a0c-a110a33c8ac7.JPG)
![badgeyay iss 2](https://user-images.githubusercontent.com/33794760/34081549-382a8afe-e374-11e7-9ba4-dab75f7e90b5.JPG)
 
**Expected behavior:**
In first installation section there are, 
1. Local Installation using Virtual environment
2. Local Installation using Vagrant environment
3. Deployment on Heroku
4. Deployment with Docker

In second installation section there are,
1. Local Installation
2. Deployment on Heroku
3. Deployment with Docker

Remove unwanted section.

**Steps to reproduce:**
Make changes in README.md 

**I am working on this issue**

**Comment by ParthS007** [comment]
@STEdirisuriya Put deploy buttons at top of README.md

**Comment by STEdirisuriya** [comment]
I am working

**Comment by abishekvashok** [comment]
Can we close this, as it was solved.

**Comment by vaibhavsingh97** [comment]
https://github.com/fossasia/badgeyay/commit/ecde056e799c6433686e0f640c63d9a5f7808a08 fixed the issue
