### ISSUE TITLE
Font size and Custom Font selection feature in Badgeyay

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#426]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Selection of some predefined font with a fixed Size

**Expected behavior:**
Selection of predefined and custom fonts with varying sizes.

I am working on this issue.

**Comment by harshit98** [comment]
@yashLadha The issue description is not up to mark. I'm not able to understand what you're trying to do here?

**Comment by yashLadha** [comment]
Sorry my bad @harshit98 . Corrected it.

**Comment by abishekvashok** [comment]
The ore defined fonts can now be selected @yashLadha can you see if we require more changes.

**Comment by yashLadha** [comment]
@abhilash97 can you explain it more? This issue is about regarding custom font sizes for generation of the badge.

**Comment by ParthS007** [comment]
@yashLadha  We are done with it. Closing it in reference to #695
