### ISSUE TITLE
Badgeyay Art Work

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#427]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

There is no artwork for this project, like other projects under organization. It would be great if we also have our own.

**Comment by rupav** [comment]
@yashLadha can you please give reference to which other projects' artwork you are talking about?

**Comment by yashLadha** [comment]
SUSI has his artwork, Loklak has its artwork, So why not badgeyay. @rupav . Hope this answers

**Comment by rupav** [comment]
So basically we want a logo for badgeyay? Isn't it? Are you working on it, or can I take up this ?

**Comment by yashLadha** [comment]
Yes you can take it @rupav . But a logo will represent the project.

**Comment by harshit98** [comment]
Before proceeding with this issue, take opinion from @mariobehling.

**Comment by naveentherocker** [comment]
I like to work on this

**Comment by yashLadha** [comment]
Let @mariobehling Review this first.

**Comment by mariobehling** [comment]
We need an eventyay and badgeyay logo that is associated. Sure, maybe give it a try.

**Comment by yashLadha** [comment]
As @rupav asked first he should get a chance and @naveentherocker you can go for eventyay logo. Just create an issue and GFI.

**Comment by naveentherocker** [comment]
Ok Sure @yashLadha

**Comment by naveentherocker** [comment]
Which Eventyay Repo should I work on with in order to make the logo @yashLadha?

**Comment by yashLadha** [comment]
Just create a basic artwork of Eventyay, not associated to particular repo under the hood. Like we have artwork fo susi and not indivdual art work of susi_android, susi_server , in the same way do it for the Eventyay as well. @naveentherocker

**Comment by naveentherocker** [comment]
@rupav Are you working on this? If not please reply so that I can work on this.

**Comment by rupav** [comment]
@naveentherocker yeah watched some tutorials too, but now as I will not be at home till 1st Jan, you can take this task. And how is your progress with eventyay artwork ?

**Comment by naveentherocker** [comment]
@rupav There is my pending PR in Eventyay. Waiting for that to be approved. As soon as it gets approved, I'll submit the Artwork.

**Comment by rupav** [comment]
@naveentherocker Please provide the link of that PR.

**Comment by fr0der1c** [comment]
If a logo is needed, I can do that:)

**Comment by ParthS007** [comment]
Closing this as of low priority 👍
