### ISSUE TITLE
Generate a python library for the project

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#431]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Generate a python library for the project. So that it can be used from the cli also.

I would be like to work on this. Views @vaibhavsingh97 @djmgit @S2606

**Comment by djmgit** [comment]
@yashLadha Nice idea :+1: Please go ahead :)

**Comment by djmgit** [comment]
@yashLadha  the project started of as a terminal based application ( a script ). After that it was converted to a flask application. So the core part of the project, that is the badge generator and badge merger are completely separate from the web application. The web application calls the required modules to do the job. So I guess all that needs to be done is create a nice terminal interface and command line options (parse switches) and call the necessary modules.

**Comment by yashLadha** [comment]
Yaa I can see the subprocess call in the code. I will make a nice terminal
interface for it.

**Comment by gabru-md** [comment]
@yashLadha great!
I would love to be of any help for this issue.
Please feel free to ping in case of problem
:smile_cat:

**Comment by yashLadha** [comment]
Sure @gabru-md . :+1:
