### ISSUE TITLE
Reference to #432

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#433]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

New changes are registered when preview is pressed
**Expected behavior:**

New changes must show in real time.

**Steps to reproduce:**
Try creating a badge and press Preview and then change the font.

**Comment by gabru-md** [comment]
Ref #432

**Comment by ParthS007** [comment]
I want to work on this 👍

**Comment by vaibhavsingh97** [comment]
claiming

**Comment by abishekvashok** [comment]
@vaibhavsingh97 any updates?

**Comment by abishekvashok** [comment]
Closing in favour of #442 aa it has the same purpose but much more info. @vaibhavsingh97 can you pls update the status there pls?
