### ISSUE TITLE
UI bug: Half visible "Download as PDF button"

### ISSUE THREAD

**Issue by vishwas78** [fossasia/badgeyay#436]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

After generating the badges the download button appears. If I submit a request for another batch of badges and preview them, then the download button and footer overlaps.

**Expected behavior:**

The users should be redirected to another page where they can download the badges.

**Steps to reproduce:**
1. Generate the badges
2. Enter data for another request and then preview it.

![image](https://user-images.githubusercontent.com/23501858/34409257-af9ca888-ebee-11e7-9fc9-30751a4b14da.png)

**Comment by vaibhavsingh97** [comment]
Please feel free to fix this issue. Nice catch 👍

**Comment by vishwas78** [comment]
Sure, working on it. Can expect a patch soon.

**Comment by abishekvashok** [comment]
Note for this, we can make sure that the footer is really below the page by adding margins with css.

**Comment by rupav** [comment]
Claiming because of inactivity.
