### ISSUE TITLE
Add Swagger UI 

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#437]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Swagger UI is not present

**Expected behavior:**
As this PR: https://github.com/fossasia/badgeyay/commit/82d6fcd79b087ba96d6cf4c20c1d075ed50a9c97 merged  
We need to add Swagger UI. Swagger does a simple but very powerful thing: with a bit of additional annotations it generates the REST API descriptions (HTTP methods, path / query / form parameters, responses, HTTP error codes, ...) and even provides a simple web UI to play with REST calls to your APIs (not to mention that all this metadata is available over REST as well).

**Yes, I want to work on the issue**

**Comment by vaibhavsingh97** [comment]
Claiming

**Comment by abishekvashok** [comment]
@vaibhavsingh97 closing this as we prefer a ember js one instead :)

**Comment by vaibhavsingh97** [comment]
@abishekvashok This not relate to frontend, this is for easy documentation of API

**Comment by abishekvashok** [comment]
I am sorry! Reopening

**Comment by S2606** [comment]
@vaibhavsingh97 Are you facing any issue working on this?

**Comment by vaibhavsingh97** [comment]
@S2606 will send PR latest by tomorrow

**Comment by S2606** [comment]
@vaibhavsingh97 If you are not working on this.Can I?

**Comment by vaibhavsingh97** [comment]
I am working on this issue

**Comment by vaibhavsingh97** [comment]
@djmgit I will use [flasgger](https://github.com/rochacbruno/flasgger) for adding Swagger UI. Flasgger also provides validation of the incoming data, using the same specification it can validates if the data received as as a POST, PUT, PATCH is valid against the schema defined using YAML, Python dictionaries or Marshmallow Schemas.

**Comment by vaibhavsingh97** [comment]
We can also use [flask_restplus](https://flask-restplus.readthedocs.io/en/stable/). It  has a feature which automatically generates interactive documentation for your API using Swagger UI.

**Comment by vaibhavsingh97** [comment]
@djmgit @ParthS007 @gabru-md @yashLadha Your opinion please
