### ISSUE TITLE
Preview won't change

### ISSUE THREAD

**Issue by Jay54520** [fossasia/badgeyay#442]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Preview won't change after the `Badge Background` change.

**Expected behavior:**

Preview will change with the `Badge Background` change.

**Steps to reproduce:**
1. `Enter Data Manually`: `Hong Phuc,Dang,@hpdang,FOSSASIA `
1. Choose a color in `Choose Background Color` and click `Preview`
1. Select a template in `Use Background Template` and click `Preview`, the preview won't change

**Codes:**
The code link is https://github.com/fossasia/badgeyay/blob/18027c0f1acb78054a0c260a8e50b75ad36e7ab9/app/static/js/script.js#L85

```javascript
$("#preview-btn").on("click",function(e){
    var imageValue,fontValue;
    if($("#picker").val() !== ""){
        imageValue = $("#picker").val();
        $("#preview").css("background-color",imageValue.toString());
    }
    else if($("input[name=img-default]").val() !== ""){
        imageValue = "/static/uploads/" + $("input[name=img-default]").val();
        $("#preview").css("background","url(" + imageValue + ")");
        $("#preview").css("background-size","cover");
    }
    // ...
});
```
If both the `"#picker").val()` and `$("input[name=img-default]").val()` exist, only get into `   if($("#picker").val() !== "")`. So, may be we should clear all the existed value in `Choose your Badge Background` after user selecting a option in `Choose your Badge Background`.

**Other thoughts:**
Is the logic of preview same as the logic of generating badge? If same, can we generate the badge from server instead of from the browser to avoid the duplicated logic. Because if the logic of generating badge change, the preview codes must change too in current situation.

**Comment by sagar-kalra** [comment]
I want to take on this issue.

**Comment by rupav** [comment]
@Jay54520 I want to take up this issue. @sagar-kalra are you still working on it?

**Comment by sagar-kalra** [comment]
@rupav I am working on it
