### ISSUE TITLE
preview should be changed to an image pop-up

### ISSUE THREAD

**Issue by nityanandagohain** [fossasia/badgeyay#453]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
 Currently the preview appears at the bottom.

**Expected behaviour:**
It should do an image pop-up which will be quite good  

I want to work on this.

**Comment by harshit98** [comment]
@nityanandagohain I'm closing this issue because we wanted the preview should be displayed at the bottom instead of a pop-up.
