### ISSUE TITLE
REST API Enhancement

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#459]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behavior:**
This is the structure for our backend which I had thought of to make the code more maintainable. The following directory tree shows where each part of the logic is located.
```
├── api                         #
│   ├── generate                #
│   │   ├── main.py             #
│   │   ├── endpoints           #  API namespaces and REST methods
│   │   ├── parsers.py          #  Argument parsers
│   │   ├──serializers.py       #  Output serializers
|   |   ├──other files           #
│   └── restplus.py             #  API bootstrap file
├── app.py                      #  Application bootstrap file
├── database                    #
│   └── models.py               #  Definition of SQLAlchemy models
├── tests                       #  Tests for testing of API
├── db.sqlite                   #
└── settings.py                 #  Global app settings

```
Your views please
Cc: @harshit98 @ParthS007 @mariobehling @djmgit @abishekvashok

**Comment by ParthS007** [comment]
Looks good to me @vaibhavsingh97  👍 , Looking forward to working on this

**Comment by vaibhavsingh97** [comment]
Solving this issue also solves #437

**Comment by ParthS007** [comment]
@vaibhavsingh97 Please create a checklist after tree structure so that others can contribute to it also 👍

**Comment by abishekvashok** [comment]
Looks good to me @vaibhavsingh97. Can we have sub issues once someone like
@mariobehling or @djmgit review?

**Comment by gabru-md** [comment]
Yes I suppose. There are many things to be finalized as of now.
It will be broken down into multiple issues to ensure parallel development

**Comment by harshit98** [comment]
Okay, great @vaibhavsingh97. Looks good to me! Can you share, how this issue can be divided into sub-tasks?

**Comment by vaibhavsingh97** [comment]
@harshit98 So I and @ParthS007 will collaborate to make the develop the basic structure of API (Swagger UI will automatically added in this process which also solves this https://github.com/fossasia/badgeyay/pull/460). 

After that to make the generated file persistent we will save in the database,  authenticatoin will be added, make badges distinguishable by providing hashes and delete badges after 10 days or so after authentication and authentication tokens with hashes in the db. I will create one parent issue after solving this issue and link these with sub issues and can be claimable by anyone.

**Comment by harshit98** [comment]
Okay. Please go ahead @vaibhavsingh97.

**Comment by gabru-md** [comment]
I would love to help as well @ParthS007 & @vaibhavsingh97

**Comment by S2606** [comment]
I would also love to help as well @vaibhavsingh97  @ParthS007  @gabru-md

**Comment by abishekvashok** [comment]
Hey, can I help as well?

**Comment by harshit98** [comment]
Sure @abishekvashok you can also help : )

**Comment by abishekvashok** [comment]
Maybe lets have this as a parent issues and achieve this step by step. Adding parent issue label.

**Comment by vaibhavsingh97** [comment]
Thanks @abishekvashok Let me send PR by EOD

**Comment by rupav** [comment]
@vaibhavsingh97 @abishekvashok what's the problem with bootstrap model, why do we need to shift to swagger UI ?

**Comment by rupav** [comment]
Sorry, I mistook this with Semantic UI (was reading about it the other day). So we are adding Swagger UI for documentation purpose of API (similar to open-event-server) ? @vaibhavsingh97 @abishekvashok.

**Comment by abishekvashok** [comment]
Yea

**Comment by ParthS007** [comment]
We are following this in #627 . Hence this can be closed :+1:
