### ISSUE TITLE
Errors should not pass silently

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#47]
**I'm submitting a ...**  (check one with "x")
- [X] bug report

**Current behavior:**

Please see the comment https://github.com/fossasia/badgeyay/pull/46#discussion_r138542555 for a description and context.
A generic error is caught and not printed out.

**Expected behavior:**

Errors should not pass silently.

**Steps to reproduce:**

Please see the comment https://github.com/fossasia/badgeyay/pull/46#discussion_r138542555

**Comment by gabru-md** [comment]
I'll do it! :+1:

**Comment by niccokunzmann** [comment]
@gabru-md Hi, great to have you here. Have fun and don't forget to tell us if you don't :)

**Comment by gabru-md** [comment]
@niccokunzmann i was wondering if we should check for all the errors?
I mean it could be better to log all the errors.

Thanks!

**Comment by niccokunzmann** [comment]
All uncaught errors will be printed automatically.
If you catch a specific error, this is ok, if you know when it happens. Catching and `Exception` is too generic and should not be silent.
So, I would not log all the errors which I know can happen.
If you think, other errors should be printed, you can create a PR.
