### ISSUE TITLE
Testing Failure Responses

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#478]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
#475 Tests for success responses

**Expected behavior:**
Procedure for failure responses too.

**Comment by S2606** [comment]
@djmgit can you please give your inputs??

**Comment by mohdomama** [comment]
@S2606 are you working on this ?

**Comment by S2606** [comment]
@mohdomama Yes.

**Comment by mohdomama** [comment]
@S2606 okay go on :+1:

**Comment by djmgit** [comment]
@S2606 please go on with this. Just make sure you cover most of the input combinations that will cause an error :)

**Comment by S2606** [comment]
@djmgit I can go on after #475 gets merged :)

**Comment by harshit98** [comment]
@S2606 The PR has been merged. You can start working on it. 👍

**Comment by mohdomama** [comment]
@harshit98 please merge #486 before @S2606 stars working on this. Its because after #475, travis was failing which was rectified in #486 .

**Comment by abishekvashok** [comment]
@mohdomama pls make sure that you post your pr to the development branch. We are migrating front-end and back end to seperate folders in the development branch. You can make a pr after the migration is complete.

**Comment by mohdomama** [comment]
@abishekvashok Sure. I would like to provide any possible help in the migration process :smile:

**Comment by abishekvashok** [comment]
@mohdomama it's finished now. If you want, you can solve this issue by editing the file present in the backend folder, although we are still lacking appropriate documentation, ci/cd and deployments.

**Comment by S2606** [comment]
@abishekvashok I do think we can wait for this as first Travis needs to be fixed based on new architecture.

**Comment by abishekvashok** [comment]
We can go either way :) however the issues for those are of higher priority than this.

**Comment by abishekvashok** [comment]
@mohdomama it's fixed now! You can work in parallel.

**Comment by S2606** [comment]
@abishekvashok I am working on this

**Comment by abishekvashok** [comment]
@S2606 ok then sure :)

**Comment by ParthS007** [comment]
closing this as Unit tests will have to be rewritten according to present state of the project :+1:
