### ISSUE TITLE
New Maintainer S2606 to join the team

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#48]
@S2606 is one of the largest contributors in terms of [commits](https://github.com/fossasia/badgeyay/commits?author=S2606) and requests to join the maintainer team.
I will add him.

[Read about becoming a maintainer](https://github.com/fossasia/badgeyay#maintainers)

**Comment by jajodiaraghav** [comment]
Can we close this? S2606 is a maintainer :)
