### ISSUE TITLE
Create Docker Container for web app

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#49]
**I'm submitting a ...**  (check one with "x")
- [X] feature request

**Current behavior:**

I would like to see an automated build of the web app running in a docker container. I have a server so I could host the web app.
There is something similar, #3 but docker is also an option.

**Expected behavior:**

Please
- [ ] Create a docker file which runs the web app
- [ ] deploy this file to a web server (I can do this)

**Comment by S2606** [comment]
@niccokunzmann I would like to create docker file

**Comment by niccokunzmann** [comment]
@S2606 Sure, please go ahaead :)

**Comment by niccokunzmann** [comment]
Dear @fossasia/open-event-core,

I would like to add this as an official docker automated build to the [eventyay dockerhub organization](https://hub.docker.com/u/eventyay/).
Would you like to do this? Should I do it and join the org on dockerhub? 
My dockerhub name is niccokunzmann.

**Comment by jajodiaraghav** [comment]
Can we close this issue or should we wait for fossasia/open-event-core's response?

**Comment by niccokunzmann** [comment]
I think, we had no response... So, I will host it at an other org.

**Comment by niccokunzmann** [comment]
Hm, this is not possible.

**Comment by niccokunzmann** [comment]
Okay, I manually edited the url for adding an automated build and it may work: https://hub.docker.com/r/badgeyay/badgeyay/builds/

**Comment by niccokunzmann** [comment]
That does not work. https://hub.docker.com/r/badgeyay/badgeyay/builds/bubhfi9bpvxbwtkwbvprgzd/

**Comment by niccokunzmann** [comment]
If someone else likes to take on the conversation, it would be fine. If nobody does, we can close it after a while.

**Comment by niccokunzmann** [comment]
I started here: https://gitter.im/fossasia/open-event-orga-server?at=59bf876fc101bc4e3ade536f

**Comment by palnabarun** [comment]
One thing I noticed, the dockerfile builds from Ubuntu base image. Is there any reason for not choosing the `Python3:onbuild` image? @niccokunzmann  @S2606 

I am asking this because if you had used the latter, all the intermediate steps would not have to be done and that would simplify the build.

**Comment by S2606** [comment]
@palnabarun Please try this on your local repo and send a PR regarding it

**Comment by niccokunzmann** [comment]
@palnabarun There are some packages required for PDF creation. I do not know how to install them using e.g. the small alpine image.
