### ISSUE TITLE
Remove redundant files.

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#496]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Lot of redundant files that are not present are present

**Expected behavior:**

They must be removed.

**Steps to reproduce:**

Go to the repository

**Comment by vaibhavsingh97** [comment]
@abishekvashok this is very small issue can be solved by beginners

**Comment by abishekvashok** [comment]
Okay

**Comment by ankurg22** [comment]
Hey I'm new and want to work on this issue. Can you guide me which files need to be removed?

**Comment by vaibhavsingh97** [comment]
@ankurg22 Sure, You can join to FOSSASIA https://orgmanager.miguelpiedrafita.com/join/6295529 and make your membership [public](https://help.github.com/articles/publicizing-or-hiding-organization-membership/). After this, I will assign this issue to you. Happy contributing!!

**Comment by ankurg22** [comment]
@vaibhavsingh97 Thanks. I'm now a member. You can assign the issue now :)
