### ISSUE TITLE
Deploy backend and front-end to heroku.

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#497]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

As the backend and front end were seperate we dont have heroku deployment for both

**Expected behavior:**

Front end and backend should be deploy ee to heroku. They must be two heroku apps.

So we need to:
- [ ] Deploy front-end to gh-pages
- [ ] Deploy backend to heroku
- [ ] Update the form action in the front-end to the heroku deployment url of the backend.

At the end we should get a running app that is alle to generate badges and provide all functionality that v1 supplies. (Code is already there)

Note: Proceed only after an admin like @mariobehling gives you a url for the front-end and backend to be on heroku. After deployment it will be better if the ownership is transferred to him as well.

**Comment by abishekvashok** [comment]
Also it need not to be a single person who does this.

**Comment by S2606** [comment]
I would like to work on this

**Comment by abishekvashok** [comment]
@S2606 sure but can you wait till @mariobehling finalizes a domain?

**Comment by vaibhavsingh97** [comment]
@abishekvashok @S2606 Nice, let's proceed after #459. Your opinion pls

**Comment by ParthS007** [comment]
I also want to help on this 😀

**Comment by abishekvashok** [comment]
@vaibhavsingh97 can have deployments and update it on each commit (includes pr merge commits as well)? Since the backend and front-end is basically functional, we can iterate on it once we deploy right?

**Comment by mariobehling** [comment]
Let's try this:

Please deploy the backend to heroku and the front-end to github pages.

**Comment by ParthS007** [comment]
Ok @mariobehling  👍

**Comment by S2606** [comment]
Ok will deploy the backend..

**Comment by vaibhavsingh97** [comment]
ok, @mariobehling  👍

**Comment by ParthS007** [comment]
I will deploy the front-end 👍

**Comment by abishekvashok** [comment]
Sure

**Comment by abishekvashok** [comment]
@ParthS007 @S2606 can we have any updates on this priority issue. We need to deploy and make sure everything works then reiterate from here using auto deployment :)

**Comment by abishekvashok** [comment]
Backend not yet deployed

**Comment by abishekvashok** [comment]
We need one more step to go. Auto deployment of backend still in progress.

**Comment by S2606** [comment]
I want to work on it @abishekvashok

**Comment by abishekvashok** [comment]
Yea you are assigned in @S2606. Pls proceed as it's priority :)
