### ISSUE TITLE
Rectify Travis ci tests

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#498]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Travis ci runs code intended for the old architecture.

**Expected behavior:**

It should support the uncoupled architecture. It should run tests for the front-end and backend on isolated instances.i.e, by making use of the **isolated** parallel builds.

**Comment by ParthS007** [comment]
working on it 👍
