### ISSUE TITLE
Connecting Backend and Frontend Modules

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#500]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There is no connection between new frontend and backend.

**Expected behavior:**
The frontend should be connected with the backend.

I am working on this.

**Comment by abishekvashok** [comment]
Can you provide some more information such as how you intend to connect them and why to do so pls? :)

**Comment by yashLadha** [comment]
I am planning to use the backend rest api for the generation of the PDF. @abishekvashok  Basically them the project will have an interface that is to use.

**Comment by abishekvashok** [comment]
Are you intending to do the 3rd point of #497 ? I could remove it from there if you prefer a seperate issue.

**Comment by yashLadha** [comment]
In that case there are two separate deploys. If the machine is running on localhost them we can just create a starting script that runs two ports for backend and frontend, but that won't be the case with Heroku deployment.

**Comment by abishekvashok** [comment]
Okay, then pls proceed. It looks great. :)

**Comment by yashLadha** [comment]
Fixes #557
