### ISSUE TITLE
Modify guide.html page.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#503]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

#476 introduces designation field which requires the modification in guide.html too.

**Expected behavior:**

Correct guide.html

**Do you want to work?**
No. A beginner can take up this issue.

**Comment by rupav** [comment]
@abishekvashok please add `new-first issue` label and alike.

**Comment by nityanandagohain** [comment]
can I work on this. I have never contributed to this repo

**Comment by ParthS007** [comment]
Yes @nityanandagohain  Please go ahead 👍

**Comment by nityanandagohain** [comment]
@ParthS007 @rupav  please can you guys provide some  hints.

**Comment by abishekvashok** [comment]
That page isn't present in he front-end you need to add it from v1 and modify it.

**Comment by nityanandagohain** [comment]
which one is v1 please help

**Comment by abishekvashok** [comment]
@nityanandagohain v1 is the one inside the v1 folder pls dont touch it :)

**Comment by rupav** [comment]
@nityanandagohain what's the status of your progress on this issue?

**Comment by nityanandagohain** [comment]
@rupav I tried but I need some help ... Some hints will be really helpful.

**Comment by rupav** [comment]
Yeah sure, first use badgeyay using the heroku app given in the description of this repository. Now when you fill manual csv data, you need to enter 5 entries, but according to guide.html in V1 folder, it says 4 entries need to be entered. Hence you need to make changes in guide.html accordingly for 5 entries. After you have made changes in guide.html, you need to add it in front end folder.

**Comment by nityanandagohain** [comment]
@rupav I need to add guide.html in the templates folder of  frontend?

**Comment by rupav** [comment]
@nityanandagohain I don't know about it, as ember js, requires .hbs files in templates section. You can make changes in the guide.html till then. @abishekvashok your view on this.
