### ISSUE TITLE
Add app.run in api/main.py file

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#505]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**
Currently there is no port number provided for API to start

**Expected behavior:**
I think it is needed for API to start locally

**I am working on this**

**Comment by S2606** [comment]
@abishekvashok what do you think??

**Comment by abishekvashok** [comment]
It starts in 4200 i guess.
