### ISSUE TITLE
Remove GIF file

### ISSUE THREAD

**Issue by ankurg22** [fossasia/badgeyay#506]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There is `working.gif` file in `/backend/app/` which is not required now as we have a youtube video for the demo.

**Expected behavior:**
1. GIF file should be deleted to reduce repo size.
2. Remove usage of the file from Readme file

**Comment by ankurg22** [comment]
@abishekvashok Make it first timer.

**Comment by abishekvashok** [comment]
Here you go. Thank you
