### ISSUE TITLE
Integrate a python linter

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/badgeyay#51]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Comment by niccokunzmann** [comment]
Why is this needed?
Integrating a tool is only a means to achieve something. What would you like to achieve?

**Comment by jajodiaraghav** [comment]
Linting the python code would ensure cleaner code and would prevent potential errors. It would also also eliminate syntactical discrepancies. 

I saw linters integrated to other python projects in fossasia, hence added. We can discuss whether we need a linter for badgeyay or not :)

**Comment by niccokunzmann** [comment]
We can add it. I hope they will not be used to turn away new contributors or make it harder to contribute. We could use them as a means for new contributors to improve the current code.

**Comment by jajodiaraghav** [comment]
I have used the default config for pyflakes which is extremely lenient. It won't make it harder to contribute.
All we have to do is document the usage so that people do not forget to lint before pushing code. 

on a side note, we should also document how to setup the dev env and how to run the app

**Comment by niccokunzmann** [comment]
Sure, you can create an issue for this. I am sure a beginner is better at it than we are if we have set it up.

**Comment by jajodiaraghav** [comment]
I didn't get you. How would a beginner be better at it?

We just have to specify two commands in the Readme.md file:
1. `pip install -r requirements.txt`
2. `python app/main.py`

**Comment by niccokunzmann** [comment]
They would add how to install python and pip on their system, how to use the command line, how to clone, ...

**Comment by S2606** [comment]
I have an idea. How about we use CI for linting purposes?? like Hound CLI?? What do you think??
@niccokunzmann @jajodiaraghav
