### ISSUE TITLE
Designation field is not drawn from csv in back-end.

### ISSUE THREAD

**Issue by mohdomama** [fossasia/badgeyay#513]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

The Badgeyay back-end currently takes only 4 arguments in csv unlike Badgeyay front-end which takes 5 arguments. The missing argument is the designation, e.g- `VIP`, `Speaker`, etc.

**Expected behavior:**

Make Badgeyay back-end draw designation from csv.

I am working on this.

**Comment by ParthS007** [comment]
@mohdomama There is already #481  for this in which I will update it in every place.

**Comment by mohdomama** [comment]
Okay @ParthS007 Thanks :+1:

**Comment by mohdomama** [comment]
Since you are working on #498  can I work on #481 in the meantime ?
