### ISSUE TITLE
Correction in Documentation for install instructions for backend and frontend

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#516]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Currently there are files present in the main directory that are not relevant to the path like `requirements.txt` that contains the information of the files that are present in old structure but not now. Also need in correction in README for consistency and less redundancy.

I am working on this.

**Comment by ParthS007** [comment]
@yashLadha we have #499 already for this and create a checklist there and mention the changes which are to be done . Closing this 👍
