### ISSUE TITLE
Add CNAME in gh-pages deployment

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#540]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behavior:**
Badgeyay Front end will be accessible at that CNAME i.e `badgeyay.com`

Working on it

**Comment by vaibhavsingh97** [comment]
@ParthS007 Still an issue, Please look into it

**Comment by vaibhavsingh97** [comment]
Closing since http://badgeyay.com/ is working
