### ISSUE TITLE
Can't select font color and any background option simultaneously

### ISSUE THREAD

**Issue by ankurg22** [fossasia/badgeyay#543]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
The user should have the option to select font color as well as a background. But only one of them is selectable.

**Expected behavior:**
Both options should work

**Steps to reproduce:**
1. Open badgeyay.com
2. Choose font color radio.
3. Now choose any one of the three background radio. You will notice font color radio gets unchecked.

I'm working on this

**Comment by rupav** [comment]
@ankurg22 is it because a checkbox got introduced in between for custom font option? Because in my PR when all were radio buttons, they all were working correctly. I tested them on V1.
