### ISSUE TITLE
Text color doesn't change in preview

### ISSUE THREAD

**Issue by ankurg22** [fossasia/badgeyay#545]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
When you choose a font color. It doesn't reflect back on the preview.

**Expected behavior:**
Font color should change with respect to selected settings

**Steps to reproduce:**
1. Select any font color. Fill data using enter data manually.
2. Click Preview. 

I'm working on this

**Comment by rupav** [comment]
Yes, @ankurg22 I didn't change the preview in earlier PR because of some problems with Preview option. Now that it has been solved, you can implement it. But Custom font was working that time also.
