### ISSUE TITLE
Enable front end form submission

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#547]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Currently the form action is left blank.

**Expected behavior:**

It should be http://badgeyay-api.herokuapp.com/api/v1.0/generate_badges

**Steps to reproduce:**
Go to the website and fill and submit the form.

**Comment by abishekvashok** [comment]
Tagging as beginner

**Comment by abishekvashok** [comment]
Things to do, edit application.hbs and change the action tag in the form to http://badgeyay-api.herokuapp.com/api/v1.0/generate_badges

**Comment by HarshitNagar** [comment]
i would like to work on this issue. Please guide me.

**Comment by ankurg22** [comment]
@HarshitNagar You need to make changes in `index.hbs` not `application.hbs`. Ignore the error :+1:

**Comment by HarshitNagar** [comment]
@ankurg22 thanks...i added the url : http://badgeyay-api.herokuapp.com/api/v1.0/generate_badges
to the action tag.
