### ISSUE TITLE
behavior of Preview when update enter data

### ISSUE THREAD

**Issue by avsingh999** [fossasia/badgeyay#550]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
when I update enter data then I have to 2-time click on the preview button

**Expected behavior:**
update enter data  and 1-click on preview then update my badge

**Steps to reproduce:**

**Comment by ankurg22** [comment]
Agree with this. Can we ditch Preview button and show a live preview on the right side of the form? It will update every time user updates a field. @ParthS007 @abishekvashok

**Comment by abishekvashok** [comment]
We can do that but first we need to make this thing working out of the box with an ajax request and progress bar and stuff. We will improve the ui when the time arises.

Currently @avsingh99 is reporting that he is forced to click two times to generate a preview instead of one time. But for me it's working even though the preview is not being shown. So can we have more explanations on this pls?

**Comment by avsingh999** [comment]
@abishekvashok it's simple when I enter data then preview button click and then the same badge if I add more data then preview button click the previous badge disappear and then again preview button click then it's show updated badge.

**Comment by abishekvashok** [comment]
> @abishekvashok it's simple when I enter data then preview button click and then the same badge if I add more data then preview button click the previous badge disappear and then again preview button click then it's show updated badge.

Thanks for the info. I don't know if we want this nw, anyway let's wait for others!

**Comment by avsingh999** [comment]
ok

**Comment by gabru-md** [comment]
@avsingh999 this is a known bug. It has to be this way:
You click the preview button to open the preview panel. And once clicked the button text must change to `Close Preview`.  And then we can go with adding Real-Time Preview of badges.

@abishekvashok is someone doing this? Or can I proceed ?

**Comment by abishekvashok** [comment]
@gabru-md you can proceed

**Comment by rupav** [comment]
@gabru-md are you implementing that text change feature to `close preview` or can I take up this ?

**Comment by gabru-md** [comment]
@rupav I am sorry, I was not available due to a wedding.
I'll be sending a PR within 1-2 days.
If I fail to do so, then this can be taken by anyone else. 
:+1:

**Comment by ParthS007** [comment]
closing this as solved in the previous PR :+1:
