### ISSUE TITLE
No link to guide is present.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#558]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Clicking on guide option brings a 404 error, as http://badgeyay.com/guide doesn't exist
**Expected behavior:**

guide.hbs should be rendered.
**Steps to reproduce:**
go to http://badgeyay.com, click on first info icon.

**I am working on it**.

**Comment by ParthS007** [comment]
@rupav  We can leave it for first-timers. What your views?

**Comment by rupav** [comment]
Update:
After Deploying on surge, `/guide` route is working correctly, and guide.hbs is getting rendered, but in original deployed site i.e http://badgeyay.com/, `badgeyay.com/guide` is showing a blank page. I haven't changed anything while deploying on surge. So PR for the same will take some time.
