### ISSUE TITLE
Motivating Documentation

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#56]
**I'm submitting a ...**  (check one with "x")
- [X] feature request

**Current behavior:**

Currently, we have a deployment to heroku.

**Expected behavior:**

To make it motivating for others to contribute, we can tell them how long it takes for their changes to become live.

- [ ] Document how the automatic deployment works, where to find the deployed version
- [ ] Document what to do to get your changes live
- [ ] Document, how long it takes after merge to see your changes inline.

**Comment by meets2tarun** [comment]
- [ ] Document to deploy your app locally, on Heroku and docker.

**Comment by S2606** [comment]
@meets2tarun I am sending a PR regarding that
