### ISSUE TITLE
footer is overlapping guide.hbs.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#565]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

No overlapping.
**Steps to reproduce:**
go to http://badgeyay.com/#/guide and scroll down to the bottom. You will see overlapping of footer on guide.hbs template.
![2018-02-02 1](https://user-images.githubusercontent.com/20624380/35729333-46fb4bec-0834-11e8-938d-e4657a1de0e3.png)

**Do you Want to work on it ?**
No, a beginner can take up this issue.

**Comment by rupav** [comment]
@abishekvashok please tag `new-first-issue` label and alike.

**Comment by abishekvashok** [comment]
Thanks done!

**Comment by avsingh999** [comment]
can I solve this issue??

**Comment by rupav** [comment]
@avsingh999 yeah go ahead.

**Comment by rupav** [comment]
@avsingh999 your progress on this issue?

**Comment by avsingh999** [comment]
sorry i was busy.now i am working on this issue

**Comment by harshyadav9** [comment]
Hi i have fixed the issue shall i give a pull request

**Comment by harshyadav9** [comment]
Kindly let me know

**Comment by rupav** [comment]
@harshyadav9 as you can see @avsingh999 already claimed this issue. If he drops the plan, you can send the PR. You have to claim issue first.
You can claim this one https://github.com/fossasia/badgeyay/issues/585 .

**Comment by harshyadav9** [comment]
any more issues kindly let me know.

**Comment by rupav** [comment]
@harshyadav9 please see issues list, you will find labels to help you decide if to take or not. 👍

**Comment by avsingh999** [comment]
@harshyadav9  i drop this issue

**Comment by avsingh999** [comment]
you can procced

**Comment by avsingh999** [comment]
@harshyadav9  are you sending pr or not?

**Comment by harshyadav9** [comment]
yes

**Comment by harshyadav9** [comment]
actually this is my first time so i am seeing how to send the pr request
