### ISSUE TITLE
guide.hbs 's custom-menu-content not showing up when clicked.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#566]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

custom-content-menu `hidden` property is removed on clicking, similar to its behaviour on home page i.e. badgeyay.com 
**Steps to reproduce:**
go to badgeyay.com/#/guide, custom-content-menu not coming when clicked.
![image](https://user-images.githubusercontent.com/20624380/35740505-0457735c-085b-11e8-8296-35c0065408d9.png)

**I am not working on it**.

**Comment by nityanandagohain** [comment]
i want to work on this.
