### ISSUE TITLE
Background image not specified error

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#571]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

After submitted the form we get an error from backend specifying that background image was not specified.

**Expected behavior:**

It shouldn't happen and badges should be generated.

**Steps to reproduce:**
Go to the website of front-end and submit the form.

**Possible Problem**
The hidden inputs fields where not properly set via javascript.

**Comment by gabru-md** [comment]
Will look into it :+1:

**Comment by rupav** [comment]
claiming.

**Comment by gabru-md** [comment]
@rupav if you don't mind, i commented before you. So can i have this ?

**Comment by rupav** [comment]
@gabru-md go ahead 😅

**Comment by rupav** [comment]
seconds delay XD 😜

**Comment by abishekvashok** [comment]
Maybe the case can be a parenthesis issue in the backend as well!

**Comment by ParthS007** [comment]
closing it as not relevant to present state of the project :+1:
