### ISSUE TITLE
Preview image is not centre aligned

### ISSUE THREAD

**Issue by sagar-kalra** [fossasia/badgeyay#572]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
 Preview is not correctly aligned on smaller screens.

**Expected behavior:**
Preview should be centre aligned.

**Can anyone else work on this issue?**
*Yes*
![screenshot from 2018-02-03 19-05-17](https://user-images.githubusercontent.com/31239108/35781711-968b4816-0a13-11e8-8c16-611a80d22425.png)

**Comment by rupav** [comment]
@sagar-kalra , claiming this.
