### ISSUE TITLE
Generate Badges taking time, so some indicator of loading/generating should be present.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#574]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

After clicking on `Generate Badges`, there is no response for few seconds until badges are created message comes up.
**Expected behavior:**

Some indication of `loading ` in this time period.

**I am working on it **

**Comment by gabru-md** [comment]
You can add an overlay that covers the whole screenand says `Wait`
And once badges are done just remove it ?
What say ?

**Comment by rupav** [comment]
Great, that's nice idea, I was thinking for a simpler one, mouse cursor wait property to use in between. What do you suggest ?
@abishekvashok @vaibhavsingh97  your opinion on this.

**Comment by gabru-md** [comment]
If you are considering the visibility factor of the loading process you can go with the overlay instead.

**Comment by abishekvashok** [comment]
@ruova maybe take a look at open-event-webapp

**Comment by rupav** [comment]
@abishekvashok that's the best option, I will see their codebase to explore this more, will send a PR soon.

**Comment by abishekvashok** [comment]
Okay!

**Comment by rupav** [comment]
@abishekvashok I am afraid, we can't implement that progress bar feature similar to open-event webapp generator because it uses webSocket( Socket.IO ) and there is a parameter data.donePercent through which one can know the progress Value. In badgeyay we are using only REST to interact with backend, so don't have any such parameter. 
I can try making progress bar but , its animations will be random, and finishes once badges are created successfully. Or should I switch to overlay then ?

**Comment by abishekvashok** [comment]
It's entierly your choice!
