### ISSUE TITLE
Remove stale files from backend

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#577]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Stale files are present, they are unwanted and should be removed.

**Expected behavior:**

They are removed

**List of files (listing the directories, remove them!)**
These folders are present in `/backend/app/static/`. Please remove:
- [x] css
- [x] images
- [ ] js
- [ ] svgs

**Steps to reproduce:**
Go to the repository and see :)

**Comment by abishekvashok** [comment]
First timers only please

**Comment by sanketsingh24** [comment]
I would like to work on this issue if it's still available.

**Comment by prateekj117** [comment]
I would like to work on this issue.

**Comment by abishekvashok** [comment]
Who's gonna do this now since you both are up for it, can you to do half?

**Comment by sanketsingh24** [comment]
Ok, I can remove css and images directory and @prateekj117  can remove js and svgs. Is this Ok?

**Comment by abishekvashok** [comment]
It's completely fine

**Comment by ajomadlabs** [comment]
Can I take up this issue

**Comment by vaibhavsingh97** [comment]
@ajomadlabs Yes, Please check https://github.com/fossasia/badgeyay/blob/development/backend/app/static/css/style.css and remove unused classes.

**Comment by vaibhavsingh97** [comment]
@abishekvashok This issue can be closed after @ajomadlabs PR

**Comment by ajomadlabs** [comment]
@abishekvashok is this done ?

**Comment by vaibhavsingh97** [comment]
@abishekvashok I think, you should wait for @ajomadlabs PR before closing this 😅 . Please see https://github.com/fossasia/badgeyay/issues/577#issuecomment-373268886. 
Reopening and will close this issue with his PR

**Comment by ParthS007** [comment]
Working on this :+1:
