### ISSUE TITLE
Rename uploads in backend to something meaningfull

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#578]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

`backend/app/static/uploads` contains the badge background templates, the directory name is confusing to have for background templates.

**Expected behavior:**

`backend/app/static/uploads` renamed to something like `backend/app/static/badge_backgrounds`

**Special note**
All occurrences of `/uploads/` should be changed to the new name in backend files which list them so as to ensure current functionality is not disabled.

**Steps to reproduce:**
Go to the backend folder

**Comment by abishekvashok** [comment]
First timers only please

**Comment by ajomadlabs** [comment]
@abishekvashok Can I take up this issue

**Comment by abishekvashok** [comment]
@ajomadlabs this was solved!
