### ISSUE TITLE
500 error on /upload - badges folder missing

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#58]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**

Raises a 500 error on /upload
![ere](https://user-images.githubusercontent.com/25414121/30419725-52931936-992f-11e7-936d-e0aa5965fda9.png)
^^
This is the error log.

**Expected behavior:**

should not throw an error.
/app/static/badges folder is missing and must be added. 

**Steps to reproduce:**

create a folder named badges inside ../app/static.
or 
```python
import os
os.chdir('../app/static')
os.mkdir('badges')
```
this line would also do! :D

I would like to work on this.
Thanks

**Comment by niccokunzmann** [comment]
@gabru-md This is a great first-timer issue. Clearly formulated with hints on how to go further.
