### ISSUE TITLE
badgeyay site not working/showing up on android's chrome browser.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#580]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

actually site is not secured (https instead of http) and thus gets manipulated by `data saver` option on chrome in mobile device.
**Expected behavior:**

Working web app on mobile device.
**Steps to reproduce:**
open badgeyay.com on google chrome, on a mobile device.

**Comment by rupav** [comment]
@abishekvashok should I add the solution in readme front-end and back-end to disable data server option on mobile device?

**Comment by abishekvashok** [comment]
Yes please!
