### ISSUE TITLE
csv and manual data link redirecting to main page, version not showing up as well

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#585]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

- go to http://badgeyay.com/#/guide, click on `csv` or `manual data`. It should move you to the content headings/(corresponding content) in the same page. Instead, its redirecting you to main page.
- Also `version` in the footer not showing up. Include the required script like in main page to make it work in `index.hbs` as well.

**A beginner can take up this issue**

**Comment by rupav** [comment]
@abishekvashok please add required label. And I think, we can even remove those 2 links `csv` and `manual data` from guide.hbs completely because we don't have much of a content on the page.

**Comment by abishekvashok** [comment]
Documentation always helps! Should we really remove it?

**Comment by rupav** [comment]
I am not saying to remove content, I am saying to remove the 2 anchor links on the top. @abishekvashok . @abishekvashok please add new-comer label too.

**Comment by rupav** [comment]
@abishekvashok There is another problem in index.hbs as well 😫. Added here only 2 tasks then.

**Comment by abishekvashok** [comment]
Sure!

**Comment by nityanandagohain** [comment]
can I work on this.

**Comment by abishekvashok** [comment]
Sure!

**Comment by nityanandagohain** [comment]
can some one help me with how to use anchor for an Id in ember I could't find a helpful search result.

**Comment by devshiva619** [comment]
@rupav  can I take up this one?

**Comment by rupav** [comment]
Yes sure, it's been stale for quite a time. Go ahead 👍

**Comment by devshiva619** [comment]
![two_diff_for_same_url](https://user-images.githubusercontent.com/20336672/38639425-c7c24308-3dee-11e8-927a-05742387b676.png)

for the same url I am getting a different page than the once shown in http://badgeyay.com/#/guide

**Comment by ParthS007** [comment]
Working on this :+1:
