### ISSUE TITLE
Images for background templates not rendering

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#591]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**
![image](https://user-images.githubusercontent.com/18497513/36631358-798d80e2-199c-11e8-984e-284dc71d12fd.png)

**Expected behavior:**
Rendering should happen properly

**Comment by abishekvashok** [comment]
Not experiencing the error on miui inbuilt browser.

**Comment by abishekvashok** [comment]
But facing the same the bug on chrome

**Comment by S2606** [comment]
I m facing this on firefox

**Comment by abishekvashok** [comment]
Yea it's an issue. I am waiting for someone to claim this.

**Comment by S2606** [comment]
I would love to claim this but i am kinda new to emberjs

**Comment by sagar-kalra** [comment]
Claiming @abishekvashok

**Comment by abishekvashok** [comment]
Issue still exists

**Comment by sagar-kalra** [comment]
https://pr-592-fossasia-badgeyay.surge.sh/ this is the deploy link for my PR and its is working fine

**Comment by rupav** [comment]
![screenshot 2018-03-09 21 25 31](https://user-images.githubusercontent.com/20624380/37216300-7465417e-23e0-11e8-856d-1dea4ba44e14.png)
@sagar-kalra its not working.

**Comment by sagar-kalra** [comment]
@rupav the possible error is that there the current badgeyay,com server is not in proper sync with github repo.
