### ISSUE TITLE
Add missing css in Backend for template index.html page to show up correctly.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#597]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

![screenshot 2018-03-15 00 34 22](https://user-images.githubusercontent.com/20624380/37426333-15d0ebda-27ec-11e8-8a6a-49b054728712.png)

**Expected behavior:**
![screenshot 2018-03-15 00 28 48](https://user-images.githubusercontent.com/20624380/37426347-24afb640-27ec-11e8-8208-f5b8dd2c7522.png)

**Comment by vaibhavsingh97** [comment]
Claiming 👍
