### ISSUE TITLE
GH-Pages Build Failing 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#599]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
![image](https://user-images.githubusercontent.com/24358501/37485320-1a30b9b0-28b1-11e8-9956-dbd1566c7fc3.png)

**Expected behavior:**
`uglifyWriter` don't support es6 so we have to make changes so that build will pass.

**Steps to reproduce:**
Please go through this https://travis-ci.org/fossasia/badgeyay/jobs/349978329

**Comment by gabru-md** [comment]
Claiming!
Found a fix, Sending PR in a few minutes.
I'll be updating the dependencies as well

**Comment by gabru-md** [comment]
I want to know that is minifying necessary?
since the error is caused by non minification of es6 code, so should we remove the minification process or should I start looking for an alternative?
