### ISSUE TITLE
badges not previewing for predefined images

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#607]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

After the current changes preview for predefined badges are not generated

**Expected behavior:**

Preview must appear

**Yes** I am on it. Will provide a PR for the same

**Comment by gabru-md** [comment]
It shows a 404 request now when accessing badges png files

**Comment by gabru-md** [comment]
Please open the developer console and make sure there is no error.
If there is an error regarding minicolors then please refresh the page. It happens because of the cdn service that is used for the JS. Nothing else

**Comment by vaibhavsingh97** [comment]
@gabru-md There is a problem, as I can't see any error related to js
Ref:
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/8705386/37602556-9894cd9c-2bb2-11e8-978c-2a88ae81f57d.png">

**Comment by vaibhavsingh97** [comment]
@gabru-md Thanks a lot! yes, the error was pretty much the same 👍

**Comment by gabru-md** [comment]
welcome @vaibhavsingh97 . I've encountered that error several times. and many times it happens in my surge deployment. and after researching a lot I saw that all I needed to do was refresh the page :P
