### ISSUE TITLE
For reviewing of the PR

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/badgeyay#61]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

While submitting a PR, now we don't have a way to review the PR.
Ways to review a PR, in increasing order of quality check

The person who made PR should give a Heroku deployment link to that branch to test the changes
or app.json file should make a temporary automatic deployment of that PR on pushing each and every commit every time.

**Comment by harshit98** [comment]
@meets2tarun The Heroku deployment link can be only given by those who have repository rights. Maybe we can turn automatic deployment whenever a PR is made. Should I set up Heroku deployment?

**Comment by gabru-md** [comment]
@harshit98 
I didn't get your point. 

> The Heroku deployment link can be only given by those who have repository rights.

The member who initiated a PR can always set up a Heroku App from their own forked repository. I did it myself. All i had to do was just 
```sh
$ mkdir mydir && cd mydir
$ git init
// copy files into dir
$ git add .
$ git commit -m "message"
$ heroku create
$ git push heroku master
```

and it worked. :)
please correct me if i'm still not getting your point .

**Comment by meets2tarun** [comment]
@gabru-md Yes, this is possible.
And the best idea is to make auto deployment on every PR.

**Comment by ParthS007** [comment]
I think we should close the issue as travis is working . Your views @meets2tarun

**Comment by meets2tarun** [comment]
The task is to temporarily auto-deploy the changes of the PR, which still needs to get implement.

**Comment by mariobehling** [comment]
Specifics of this task are unclear. This seems to be a general discussion and not a specific coding task. Thanks. Closing it.
