### ISSUE TITLE
Link not working on backend webpage

### ISSUE THREAD

**Issue by Dipesh-Budhiraja** [fossasia/badgeyay#612]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

On http://badgeyay-api.herokuapp.com/  page when we click documentation button then it redirects to 404 GitHub page

On this page when we click documentation button we are redirected to 404 page
![screenshot from 2018-03-21 11-01-26](https://user-images.githubusercontent.com/29384452/37728825-7f356068-2cf8-11e8-8078-ea69f0569241.png)

![screenshot from 2018-03-21 11-02-09](https://user-images.githubusercontent.com/29384452/37728841-857edf80-2cf8-11e8-993b-a4fa6f795c49.png)

**Comment by sagar-kalra** [comment]
Thats because documentation of Badgeyay is not ready yet. There is an issue for it https://github.com/fossasia/badgeyay/issues/554 .

**Comment by abishekvashok** [comment]
Closing as duplicate
