### ISSUE TITLE
Nature of Preview button changing on clicking generate badge button

### ISSUE THREAD

**Issue by Dipesh-Budhiraja** [fossasia/badgeyay#613]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

When I preview a badge, then preview button is working as expected but when I click generate badge in this state then the preview disappears and button shows "Close Preview". So nature of button is getting swapped.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29384452/37783558-caa32066-2e1b-11e8-97fa-faa6c88b06b2.gif)

**Expected behavior:**

Nature of preview button must remain intact

**Comment by rupav** [comment]
Nice catch @Dipesh-Budhiraja, are you working on this, or can I take up this?

**Comment by Dipesh-Budhiraja** [comment]
Let me give it a try. In case, if I face any problem I will contact you.

**Comment by rupav** [comment]
yeah sure 👍
