### ISSUE TITLE
add test cases to compare generated png and expected png.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#614]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

In reference to the discussion: https://github.com/fossasia/badgeyay/pull/615

**Comment by parassharma1612** [comment]
I want to work on this issue. This is my first time contributing. Please guide me.

**Comment by ParthS007** [comment]
Not relevant to current progress of the project :+1: 
closing this :+1:
