### ISSUE TITLE
Add cut-lines/dashed lines to facilitate badges folding/cutting after generation.

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#616]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Current badges layout has margins, but not cut lines. Having them will facilitate user's experience to cut/fold the badges after printing them.
**Expected behavior:**

Cutlines / dashed lines at midway between two badges.

** I am working on it **

**Comment by rupav** [comment]
Will send a PR along with #595 ASAP.

**Comment by rupav** [comment]
![screenshot 2018-03-29 00 01 09](https://user-images.githubusercontent.com/20624380/38048940-795a1ffc-32e4-11e8-98e4-54c17b206bd2.png)
This will be the layout, I have hidden the badges.

**Comment by abishekvashok** [comment]
@rupav looks good.

**Comment by rupav** [comment]
@ParthS007 @vaibhavsingh97 @gabru-md @yashLadha guys I have done this using INKSCAPE, I can send the copy of this layout. Let me know if one of you want it. To view the badge layout, you may open the file in the browser or through INKSCAPE(preferred method).

**Comment by ParthS007** [comment]
Yes @rupav, Please share it with me. :+1

**Comment by rupav** [comment]
[8BadgesOnA3.zip](https://github.com/fossasia/badgeyay/files/1949515/8BadgesOnA3.zip)
I cant upload an svg file on github, you need to extract it. 😃

**Comment by YogeshSharma0201** [comment]
@rupav @ParthS007 I would like to work on this issue.

**Comment by rupav** [comment]
yes you can @YogeshSharma0201 .
