### ISSUE TITLE
Version not showing up in http://badgeyay-api.herokuapp.com/

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#619]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

`Version` is not showing up in the backend. Might be due to missing files.
**Expected behavior:**

The `version` showing on the website.

**Any newcomer can take up this**

**Comment by abishekvashok** [comment]
Please wait for it to load. It occurs irregularly

**Comment by rupav** [comment]
I tried many times before posting this. Do share a screenshot if version is showing up. Will close it then.

**Comment by abishekvashok** [comment]
![screenshot_2018-04-04-13-17-07-706_com android chrome](https://user-images.githubusercontent.com/8947010/38295098-8991d1a0-380a-11e8-95bf-f06504e5bf56.png)

**Comment by ParthS007** [comment]
Closing this as working fine :+1

**Comment by rupav** [comment]
@ParthS007 @abishekvashok  please see the link provided, I posted this for backend flask server, where version in not showing up. 
Reopen this issue, as I don't have rights .

**Comment by rupav** [comment]
And you guys posted  front-end link.

**Comment by vaibhavsingh97** [comment]
Claiming
