### ISSUE TITLE
Create a demo video for badgeyay

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/badgeyay#62]
https://www.youtube.com/channel/UCQprMsG-raCIMlBudm20iLQ

Badgeyay doesn't have a demo video on Fossasia Youtube channel. Creating a demo and uploading in to the Fossasia channel would help us attract new contributors.

I would like to know what other people think about it :)

**Comment by Pk13055** [comment]
Can I create one? Or are you handling this @jajodiaraghav ?

**Comment by jajodiaraghav** [comment]
@Pk13055 I am working on this one. But we can definitely make space for more videos.
Once we have the JSON config setup, you can make a demo video showing how to create a sample JSON file and upload it to get desired results. Sounds good?

**Comment by Pk13055** [comment]
Sounds good! Tell me when you're done

**Comment by jajodiaraghav** [comment]
Waiting for #63 to close

**Comment by meets2tarun** [comment]
@jajodiaraghav 
Do you have the permission to upload the video on FOSSASIA youtube page?
If yes, go for it otherwise I can help you out.

**Comment by jajodiaraghav** [comment]
@meets2tarun No I don't, but in codeheat.org, it is mentioned that we will be given access if we submit the video :)

**Comment by niccokunzmann** [comment]
- If you put the video under cc license, not youtube license, others can take the video and remix it.
- Also, before you close this, please paste the link to the video here. I would like to watch it and I guess, other would like it, too. 
- We can also add it to the README, so people new to the repository get a video introduction.

**Comment by Pk13055** [comment]
What's the status on this?

**Comment by niccokunzmann** [comment]
I think jajodiaraghav is woking on it: https://gitter.im/fossasia/badgeyay?at=59be59ca614889d4750adfe9

**Comment by jajodiaraghav** [comment]
Hi all, I haven't made the video yet due to the design bug present in the app. #63 must be closed in order to make the video.

**Comment by jajodiaraghav** [comment]
I have created a video. Link: https://vimeo.com/235126495

Feedback and criticism welcome :)
We will definitely need one more demo video showing the use of JSON config file. That can be done once this is closed.

@niccokunzmann @gabru-md @S2606 @meets2tarun @Pk13055

**Comment by gabru-md** [comment]
@jajodiaraghav great work! 
Cheers !

**Comment by S2606** [comment]
@jajodiaraghav  can i make that other video??

**Comment by jajodiaraghav** [comment]
@S2606 I think you should consult @Pk13055 as he wanted to work on JSON config part.
Also, you might create a video on some other use case like manual data input instead of CSV, or selecting PNG from dropdown.
What do you think?

**Comment by meets2tarun** [comment]
@jajodiaraghav 
Nice one!

**Comment by meets2tarun** [comment]
@S2606 You can go for the other video too.

**Comment by jajodiaraghav** [comment]
Hi Tarun, I have seen a few videos of FOSSASIA's Youtube channel and found several demo videos without any audio. I don't think audio is compulsion for FOSSASIA. Besides, the primary goal of demonstration of BadgeYAY app is addressed.
We can definitely create more videos with audio in case it's necessary.

>  It's better as soon as you shift to LINUX

I use linux for development and Open Source. I just created the video on windows :)

Thanks for the feedback.

**Comment by jajodiaraghav** [comment]
Closed using https://www.youtube.com/watch?v=Gh8j_01LIoQ
