### ISSUE TITLE
Failure message show not good

### ISSUE THREAD

**Issue by avsingh999** [fossasia/badgeyay#621]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**
when we generate a wrong badge then Error show but then footer overlaping and if we again and again click on generate wrong badge then Error message below in image
![erro3](https://user-images.githubusercontent.com/25536022/38429698-c745bec0-39dc-11e8-932c-9824f0ed478d.PNG)
if you click  generate badges Button then the Error message  show "CSV data was given in incorrect formatCSV data was given in incorrect format"  then we again click generate button then Error message "CSV data was given in incorrect formatCSV data was given in incorrect formatCSV data was given in incorrect formatCSV data was given in incorrect format" 

**Expected behavior:**

if you click  generate badges Button then the Error message  show "CSV data was given in incorrect formatCSV data was given in incorrect format"  then we again click generate button then Error message "CSV data was given in incorrect formatCSV data was given in incorrect format" 
**Steps to reproduce:**

**Comment by sagar-kalra** [comment]
Claiming :+1:
