### ISSUE TITLE
Convert merge_badges.py into a class

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#628]
Presently os.system is used to execute merge_badges because merge_badges does have a proper interface/api to use it from another file. It is a standalone script. This was alright when badgeyay was a command line tool to create badges. However now, using os.system to run the script seems quite hacky and limits its use. Instead, merge_badges.py should be converted to a proper module containing a class
which can be imported to main.py and used. I guess this is the proper workflow rather than executing it as a stand alone script.

**Comment by djmgit** [comment]
@vaibhavsingh97 @gabru-md @ParthS007 your views?

**Comment by gabru-md** [comment]
Definitely,
I do understand that your point is very accurate. To put up simply, We are following a `hackathon` approach for badgeyay, by simply getting it worked.
We need to make it stable and do not rely on `bash` for executing the scripts. To design it into a full product we need to modify the files so that they can be compatible to each other and help in maintaining a proper workflow.

**Comment by djmgit** [comment]
@gabru-md  yes

**Comment by ParthS007** [comment]
@djmgit  Totally agree with you and we need to follow a modularized approach as you have proposed in the previous issue. :+1:

**Comment by yashLadha** [comment]
Why not create a Library and do changes into that and import that library into project. This approach i have seen in many org's that they create a package for their project and uses the higher level api's designed in the package. This way code will be modularized as well as easy to read and extendible. Views @djmgit @vaibhavsingh97 @gabru-md @ParthS007

**Comment by gabru-md** [comment]
Agreed !

**Comment by vaibhavsingh97** [comment]
Agreed 👍

**Comment by ParthS007** [comment]
Agreed :+1:

**Comment by djmgit** [comment]
@yashLadha nice idea, yes we can definitely move merge_badges.py and generate_badges.py into a folder(perhaps badgeyay_utils or badgeyay_core) and convert it into a library. From the library we can import our required classes, methods etc. In that way, the core logic part will also remain separated from the web server part.

**Comment by djmgit** [comment]
Any updates?

**Comment by gabru-md** [comment]
I guess if no one is working on it at this moment I would like to claim this task then.

**Comment by yashLadha** [comment]
before proceeding @gabru-md  we need to properly document this and layout the structure.

**Comment by yashLadha** [comment]
As already there is a cli present and we can extend the cli for the conversion of the class and the project. Views @gabru-md @djmgit

**Comment by gabru-md** [comment]
I can start with a new file and then maybe collaborate onto making it better ? 
And once that is fully functioning and has proper docs we can replace it with the current file?

**Comment by yashLadha** [comment]
I would like to work on this @gabru-md . We can divide the work, If you want?

**Comment by gabru-md** [comment]
Okay! 
I'll create a new file with proper usage of class and functions. And then we both can improve it. :+1: 
Like making it better and adding docstrings

**Comment by djmgit** [comment]
@gabru-md @yashLadha great! @yashLadha yes you can surely extend the cli, just make sure nothing is breaking before making the replacement.

**Comment by yashLadha** [comment]
Ok So you proceed with converting the file into the Class and i will working on including the class into the library and docstrings. @gabru-md

**Comment by yashLadha** [comment]
Is this fine @gabru-md @djmgit ??

**Comment by gabru-md** [comment]
Sure ! I'll send a PR soon.
And meanwhile I'll discuss it with Yash on proceeding further
