### ISSUE TITLE
Disable `Add CSV` from UI

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#632]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

We should disable `Add CSV` from UI till the time we work on a fix for the same since it is not working as of now.

CC : @ParthS007 @djmgit

**Comment by gabru-md** [comment]
I will take it up if you allow @djmgit @ParthS007

**Comment by ParthS007** [comment]
Agreed with you @gabru-md  :+1:

**Comment by djmgit** [comment]
@gabru-md go for it, after this we need to get our hands on fixing the csv upload part and bring this feature back :)

**Comment by gabru-md** [comment]
sure
