### ISSUE TITLE
Review for installation setup steps

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#64]
Check the installation steps on the docs folder and report any changes to be made .

**Comment by nemaniarjun** [comment]
Local Installation: Since we are using python3, the pip command should be 
`sudo -H pip3 install -r requirements.txt`

**Comment by S2606** [comment]
Hey @nemaniarjun thats a good point . What do you think @jajodiaraghav @niccokunzmann ?

**Comment by jajodiaraghav** [comment]
@nemaniarjun @S2606 
I was thinking of setting up virtualenv for our app. This would make it easier.

**Comment by S2606** [comment]
@jajodiaraghav Ok i will create Vagrantfile then.

**Comment by jajodiaraghav** [comment]
I was talking about this: https://pypi.python.org/pypi/virtualenv
http://www.pythonforbeginners.com/basics/how-to-use-python-virtualenv

We do not need vagrant at the moment (not sure). But we should add instructions of using virtualenv in docs.

**Comment by nemaniarjun** [comment]
I can take this up, do we want to add a venv to the repo? or Just add instructions on how to make it locally?

**Comment by niccokunzmann** [comment]
@nemaniarjun You can add a venv. Sounds good. You can create a PR with the changes you would make to the tutorial.

**Comment by palnabarun** [comment]
@niccokunzmann  @jajodiaraghav  One question, why do you need to have a venv in the repo? A simple development setup instruction will suffice in letting the contributors know how to get started. What are your views?

**Comment by niccokunzmann** [comment]
@palnabarun I would go with your decision. As a new contributor, you know best what new contributors need.

**Comment by jajodiaraghav** [comment]
I agree with @palnabarun
The issue was opened for discussing the best approach. I think a dev setup instructions doc would do :)

**Comment by palnabarun** [comment]
So, should I add Dev setup instructions [here](https://github.com/fossasia/badgeyay/blob/development/.github/CONTRIBUTING.md) ?

**Comment by jajodiaraghav** [comment]
No. Please add it inside the doc/installation folder. and put the link in Readme.md later

**Comment by palnabarun** [comment]
A dev setup document is already there [here](https://github.com/fossasia/badgeyay/blob/development/docs/installation/local.md). This can be edited to add the virtualenv parts in between Point 1 and Point 2 in between the `Steps` section.

**Comment by palnabarun** [comment]
One more thing, the local setup doc says to clone it from `fossasia/badgeyay` which I feel is not the right way. The contributor should first fork the repo, clone their fork and then add `fossasia/badgeyay` as an upstream repo. What are your views? @niccokunzmann  @jajodiaraghav

**Comment by niccokunzmann** [comment]
This sounds good: It will remove the extra steps for adding a remote for their fork once they have a patch.

**Comment by jajodiaraghav** [comment]
>  the local setup doc says to clone it from fossasia/badgeyay which I feel is not the right way.

You are right! We must have overlooked this part while merging. It would be great if you could fix this as well :)
