### ISSUE TITLE
rename directory 'uploads' in v1 folder 

### ISSUE THREAD

**Issue by vddesai1998** [fossasia/badgeyay#640]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

When we run the server locally we get the file not found error
**Expected behavior:**

**Steps to reproduce:**
Run server in v1 folder

In this [commit](https://github.com/fossasia/badgeyay/commit/07185ad22949b8a09eaf693b342c92739f1c86f9) inside all files directory's name is changed but it is not renamed actually in folder `app/static`.

**Comment by gabru-md** [comment]
The v1 server is not in use as of now i suppose :sweat_smile:

**Comment by vddesai1998** [comment]
Yes, I asked about it on gitter but no one replied.. 😅. 
So should I close this issue....?

**Comment by gabru-md** [comment]
yes please :D
