### ISSUE TITLE
Create a artwork of Badgeyay like other Open event services.

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#644]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behavior:**
There is a need of artwork just like other open event services

**Steps to reproduce:**

working on this.

**Comment by gabru-md** [comment]
I guess it will be awesome. Please go ahead

**Comment by ParthS007** [comment]
![badge](https://user-images.githubusercontent.com/24358501/39328165-138cedf4-49b8-11e8-8572-23b47d7f8890.png)

**Comment by ParthS007** [comment]
![badge1](https://user-images.githubusercontent.com/24358501/39328194-330d119a-49b8-11e8-8a4e-d6dc0793ee53.png)
