### ISSUE TITLE
Seperating Config from Code base

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#647]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Parent Issue**: https://github.com/fossasia/badgeyay/issues/627

**Current behavior:**
Currently all the configs are present in one single file

**Expected behavior:**
`config.py` should be present in the codebase where all the config should be managed.

**Yes, i want to work on this issue**

**Comment by vaibhavsingh97** [comment]
Cc @djmgit

**Comment by ParthS007** [comment]
closing this in reference to #704
