### ISSUE TITLE
Clicking outside the Menu in Header should close it.

### ISSUE THREAD

**Issue by nemaniarjun** [fossasia/badgeyay#65]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

Right now to close the Menu (Dropbox?) one needs to click on the link again.
Clicking anywhere outside it, should close it.

**Comment by S2606** [comment]
Hey @nemaniarjun  feel free for PR

**Comment by S2606** [comment]
And describe your problem as current behavior and expected behavior in future.

**Comment by nemaniarjun** [comment]
Sorry, will keep that in mind :)
