### ISSUE TITLE
Discussion on Database Service addition to Badgeyay

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#651]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Currently, there is no Database integrated with the Badgeyay for storing the data of the users, history, etc.

**Expected behavior:**
There should be a database service integrated with the Badgeyay in order to add further features like login/signup, user history, and badges generated by the user.
In our proposal, we have proposed to use `MONGO DB` as Database service due to its flexibility and easy-of-scaling. But Open Event Server uses `PostgreSQL`.

To finalize the Database service, we should have a discussion which we will be using finally for Badgeyay.

@djmgit  Please give your views and help us in proceeding with this issue.

cc : @gabru-md @yashLadha @vaibhavsingh97

**Comment by gabru-md** [comment]
I support MongoDB.
The points are same as that written in my proposal. :)

**Comment by gabru-md** [comment]
PostgreSQL it is :)

**Comment by gabru-md** [comment]
Can be closed

**Comment by yashLadha** [comment]
I will go with PSQL :+1: as said by @gabru-md .

**Comment by ParthS007** [comment]
Closing this as PSQL was finalized.
