### ISSUE TITLE
Remove Version files to separate branch

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#657]
As currently in the development branch `v1` is present and all the released versions should either be present in the master branch or in the respective version branch. What i am proposing is to remove the version folder from the development branch and shift it to either the master branch or version branch. So that the extra code gets cleaned and the code that is present in the branch will only get developed. Views @djmgit ?

Example: 

![image](https://user-images.githubusercontent.com/18033231/39398774-6cb11abc-4b30-11e8-8bc0-4a6d119d4d04.png)

CC: @ParthS007 @vaibhavsingh97 @gabru-md

**Comment by gabru-md** [comment]
Cool, I would like to claim this task. :D

**Comment by yashLadha** [comment]
Cool, but let's it first approve by @djmgit

**Comment by gabru-md** [comment]
Ping @djmgit

**Comment by gabru-md** [comment]
@djmgit please create a new branch for the same.
`version-1` will do. I have the PR ready, just need a new branch for the same. :D

**Comment by gabru-md** [comment]
or should I send a PR for `master` instead?

**Comment by yashLadha** [comment]
Also @gabru-md Please remove the code from the development branch. That will need an another PR. Thanks

**Comment by ParthS007** [comment]
I will remove it from development :+1

**Comment by gabru-md** [comment]
sure @ParthS007,
Let my PR get merged first, then you can get along with it :)

**Comment by djmgit** [comment]
@gabru-md I have created a new branch named ```version-1.0```

**Comment by yashLadha** [comment]
Already PR merged : https://github.com/fossasia/badgeyay/pull/665
