### ISSUE TITLE
Create PDF / ZIP only if the User asks for it

### ISSUE THREAD

**Issue by nemaniarjun** [fossasia/badgeyay#66]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

Right now if a user uploads a CSV - we are making SVGs, PDFs and ZIP - and then giving the user the option to download one. This will waste time for large number of badges.

Maybe ask the user before-hand what all formats they want the badges in,

**Comment by gabru-md** [comment]
I will work on it :+1:

**Comment by nemaniarjun** [comment]
@gabru-md lets wait for the maintainers to discuss on this?

**Comment by nemaniarjun** [comment]
Also this is a significant change, we can break it down into parts.

**Comment by S2606** [comment]
@nemaniarjun  how do you propose to break it into parts??

**Comment by nemaniarjun** [comment]
After going throught the code, I no longer thing its should be broken down. Instead while the rewriting of the shell script as a python3 script these changes can be incorporated.
(#19)

**Comment by gabru-md** [comment]
I believe we will have to make different shell scripts for the very purpose.
These shell scripts can be activated as and when it is necessary. 
Any thoughts @S2606 @nemaniarjun

**Comment by nemaniarjun** [comment]
@gabru-md That was my point, we are going to convert the shell script into a python3 script (See issues #19)
So instead of going ahead and writing multiple shell scripts, wait for #19 to be completed and then do this issue.

**Comment by gabru-md** [comment]
Can i work on it ? I'll add some argparse arguments which will determine which of the steps to carry. This will help us to maintain a single python file for all the purposes. 
What do you suggest ?

**Comment by gabru-md** [comment]
@nemaniarjun If you merge #71 then I have made the necessary changes for asking the user to create either PDF or ZIP. Ping here whenever you merge #71 then I'll make a PR for this issue as well.
Thanks!
