### ISSUE TITLE
Add VirtualEnv folder to .gitignore

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#670]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

Currently after doing some changes and typing `git status` the Virtual Environment folder shows up in it.

**Expected behavior:**

Virtual Environment folder must not show up in `git status` and it must be put up in .gitignore.
Currently as per the local setup guidelines the virtualenv folder is `badgeyay` .

**Steps to reproduce:**

Add `badgeyay/`  to `.gitignore` should solve this.

**Comment by gabru-md** [comment]
CC : @djmgit

**Comment by ParthS007** [comment]
sending PR for the same :+1:

**Comment by gabru-md** [comment]
okay :)
