### ISSUE TITLE
Sanitize URL in Response class

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#685]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

The url that is generated will be of the localhost and not the domain name. So the url has to be refactored in the backend side and not in the frontend as not the same is happening currently. This issue is mainly towards refactoring the generated url for making it available for download. Sanitize url to act as a download link.  Sent PR after https://github.com/fossasia/badgeyay/pull/678 got merged.

__I am working on this__

**Comment by ParthS007** [comment]
@yashLadha Can you please explain a bit about this issue? :smiley:

**Comment by yashLadha** [comment]
@ParthS007  Updated
