### ISSUE TITLE
Optimizing the flask app

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#69]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

This is regarding optimizing the web app

**Comment by S2606** [comment]
what do you think about this?? @niccokunzmann @jajodiaraghav

**Comment by gabru-md** [comment]
How exactly do you wish to optimize the web application ? 
I would love to help but only if you could provide me with some insights 
:D

**Comment by jajodiaraghav** [comment]
@S2606 Can you please explain what exactly are you looking for. The issue title is not clear to me.
Thanks :)

**Comment by S2606** [comment]
@jajodiaraghav Flask-compress is a module which acts just like gzip in nodejs. This helps in increasing speed of the website. I would ass this module in my next PR

**Comment by gabru-md** [comment]
That is a brilliant idea. 
:+1:

**Comment by jajodiaraghav** [comment]
Godd idea :)
Looking forward to the PR

**Comment by jajodiaraghav** [comment]
@S2606 Any update?

**Comment by S2606** [comment]
@jajodiaraghav Sorry for late reply.Was a bit busy. Regarding PR will send by tonight
