### ISSUE TITLE
REST API Adapter to Request from frontend to backend api

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#698]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Currently an AJAX request is made.

**Expected behavior:**
As the frontend is in Ember then we should proceed with the suite provided by Ember for the REST Api calls.

__I am working on this__

**Comment by yashLadha** [comment]
CC: @djmgit

**Comment by ParthS007** [comment]
closing this as now we have started using JSON API Adapter for entertaining requests and same is followed in the backend. :+1:
