### ISSUE TITLE
Adding Login/Signup in REST API (Using Firebase)

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#707]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Currently, login/signup is present and implemented using the traditional approach. Username and password are dumped in the database

**Expected behavior:**

Signup/Login should be added using Firebase

**I want to work on this issue**

**Comment by yashLadha** [comment]
Firebase will offload most of the work and also provides a great set of
tools for OAuth, also the functionalities like cloud functions will greatly
enhance the experience as the flask libraries will not be able to create
such functionalities. For the case when a user is register, automatically a
cloud functions will get triggered and will send a greeting message with
the note to confirm the mail. If we go with creating these functionalities
then it will take us lot of time. So I think it would be better to go with
firebase for user management and certain cloud functions.

**Comment by ParthS007** [comment]
Yes, we should go for it but when we have time to develop the traditional API endpoints for these features, then we should follow the traditional one as followed in Open event server but as said by @yashLadha  we can ease down the process of logging in and all the OAuth  handling then we should 
use this :+1:

**Comment by yashLadha** [comment]
As @ParthS007 first we need to create the basic API Endpoints first and then we can change it to fit with the firebase python sdk, because not a lot of code will change will change and it will just insert some functions from the sdk.

**Comment by vaibhavsingh97** [comment]
I am working on it

**Comment by ParthS007** [comment]
Yes @vaibhavsingh97 , Please go ahead :+1:

**Comment by ParthS007** [comment]
Closing as completed :+1:
