### ISSUE TITLE
Project Management tool needed for Badgeyay

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#708]
With the help of Project management tools, we can organize, manage, and track your project with tools that build on top of issues and pull requests

**Current behavior:**
There are no Project management tools integrated with badgeyay, there are lots of conflicts due to that. Also, one can get a better insight of the project like team progress, number of contributions, number of issues assigned to a member

**Expected behavior:**
The project should have Project management tools.

**Available Project management Tools**
- ZenHub
- issue.sh
- DeepAffects
- Waffle
- Zube 

1. **ZebHub**
ZenHub is the project management tool that integrates natively within GitHub’s user interface.
![image](https://user-images.githubusercontent.com/8705386/39743166-b48b9756-52bd-11e8-9ddc-a8054e5fcc97.png)

2. **issue.sh**
issue.sh is a tool for agile software development powered by live GitHub data.
\* Only work with Chrome Extension
![image](https://user-images.githubusercontent.com/8705386/39743230-e8aebcca-52bd-11e8-9403-5d472712d000.png)

3. **DeepAffects**
DeepAffects analyzes emotions and tones in issue description and comments to provide actionable insights to identify the high-resolution time issues, disagreements in the team.
![image](https://user-images.githubusercontent.com/8705386/39743530-c6f4f3be-52be-11e8-9518-d544f576cac3.png)

4. **Waffle**
Automated project management powered by GitHub issues & pull requests. One can get insights and track developer progress.
![image](https://user-images.githubusercontent.com/8705386/39743333-2d81e200-52be-11e8-8178-0a9d545d2285.png)

5. **Zube**
Zube is an Agile project management platform that allows everyone on your team to communicate with the developers.
![image](https://user-images.githubusercontent.com/8705386/39743364-49594932-52be-11e8-8da7-f16f4c25377f.png)
Limitations:
![image](https://user-images.githubusercontent.com/8705386/39743376-57331eb6-52be-11e8-88b9-b90c5991de89.png)

---

**Waffle/Zenhub is more preferred as we need to manage the project and doesn't need any extension and integrate with seamlessly with GitHub** 

Cc @djmgit

**Comment by djmgit** [comment]
Waffle and issue.sh looks good.
@ParthS007 @gabru-md @yashLadha please check the list and share your views :)

**Comment by yashLadha** [comment]
Waffle :+1:

**Comment by djmgit** [comment]
@vaibhavsingh97 @yashLadha @gabru-md @ParthS007 so is waffle confirmed?

**Comment by ParthS007** [comment]
I don't think we need this as we have to also invest our time to maintain this and we already have a backlog and comparison sheet which have all the things like the responsible person for the specified task.

If someone agrees to maintain this regularly, I am open to it. We can maintain it when we have some stabilization in the project and we have very long-term goals or we can use directly the `Github Projects` and `Milestones` features.

If we only use these services for checking the no of assigned issues and progress then it is only dividing our development time with something, not of that use.
This is my personal view and if everyone agrees to use that then I will also go for it.   :smiley:

**Comment by vaibhavsingh97** [comment]
@ParthS007 The best thing is you don't have to maintain it, It automatically syncs with Github and helps maintainers to resolve conflicts and get better insights of the project. Also, maintaining excel sheet is the hard thing.  It's Trello for GitHub, correct me if I'm wrong.

**Comment by ParthS007** [comment]
Closing this as it is not needed :+1:
