### ISSUE TITLE
Add Password strength check

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#714]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
There is no Password validation for the strength check

**Expected behaviour:**
There should be password strength check validation

**Will work on it after #629 closes*

**Comment by yashLadha** [comment]
What approach you are proposing as already we are storing the hash of password in the database and as per the primary attack in hashing it is difficult to recover the password from the hash. So what are you proposing here @vaibhavsingh97

**Comment by yashLadha** [comment]
Even if the password is small the hash generated will not be easy to decrypt even with a lot of computational resources attacker have. Views on it? @ParthS007 @djmgit @gabru-md

**Comment by gabru-md** [comment]
This is more of a frontend issue and should be handled at Ember side.
@yashLadha what are your views? It can be easily done using Ember JS frontend I suppose

**Comment by ParthS007** [comment]
@vaibhavsingh97  You have already claimed 3 issues
1. https://github.com/fossasia/badgeyay/issues/707
2. https://github.com/fossasia/badgeyay/issues/647
3. https://github.com/fossasia/badgeyay/issues/437

Please follow best practices as now you have 4 claimed issues including 1 WIP PR. Please work on already claimed issues and then you are open to claim other open issues or you can open issue to be claimed by others. In this way, we can maintain the development pace.

Yes, we can handle it on the frontend side or if you have any other approach as it is difficult to recover the password from the hash.
Your views @vaibhavsingh97 @yashLadha @gabru-md @djmgit

**Comment by yashLadha** [comment]
As said it is hard to recover the password from the hash and it has to be handled in the frontend as we can't increase the load of requests in backend.  Once the frontend is separated into components we can work on issue regarding frontend like REST Api adapter, but it would give us better idea if you propose you approach.

**Comment by vaibhavsingh97** [comment]
@yashLadha @ParthS007 @gabru-md 
Let me explain the use case of this issue, you guys are right that we are storing the hash of the password in the database and as per the primary attack in hashing it is difficult to recover the password from the hash. Let's say
1. If the user uses password same as the username and email address (This should not be the case)
2. It checks for too many character repetitions and the number of character classes used (Like QweQwe)
There are lot's of issues like this, so to protect these, I am adding issues and wish to solve them.

Also, as @ParthS007 mentioned that I claimed too many issues than for Firebase and SwaggerUI, I haven't received confirmation from the mentor that I should move forward or not that's why I haven't sent PR for them. Also, for Firebase issue, only @yashLadha shared his views and others views are missing. And the same case with the Swagger UI issue. I am waiting for confirmation of all the fellow developers before moving forward.
For the case of WIP PR, It was complete, due to my health issues, I sent the update but forget to remove `WIP` from the PR title. I am sorry for this, and I assure you guys that this mistake will not be repeated this in future.

**Comment by yashLadha** [comment]
@vaibhavsingh97 Them we can drop a hint in frontend and that can be handled using key up event in frontend.

**Comment by vaibhavsingh97** [comment]
@gabru-md @yashLadha Cool, then we can have this feature front-end side, Will work on it, after #629 closes
