### ISSUE TITLE
Fix imports in the codebase

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#725]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
Currently there are imports like as api.* which should not be there

**Expected behaviour:**

Please correct the imports

**Comment by gabru-md** [comment]
Claiming

**Comment by yashLadha** [comment]
GFI :+1:

**Comment by yashLadha** [comment]
It seems the error is the way we run the code. If we go with the standard way
```sh
export FLASK_APP=run.py
flask run
```
Them it considers the API as the whole package. But if we run in the way as follows
```sh
python run.py
```
Them it considers the package after `run.py`.

**Comment by yashLadha** [comment]
But still @gabru-md  you can work on correcting the mail config import if you want?

**Comment by gabru-md** [comment]
Okay ! 
Sure I will

**Comment by vaibhavsingh97** [comment]
@yashLadha we should go by standard way and include this in `Readme` to. 
@gabru-md @ParthS007 your opinion?

**Comment by yashLadha** [comment]
Fixed in #728 @gabru-md 
Yes @vaibhavsingh97 we can add this but we haven't completed the api so may be this can be done in the documentation phase later.
