### ISSUE TITLE
Change Error Page for 500 Error

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#75]
**I'm submitting a ...**  (check one with "x")
- [X] feature request

**Current behavior:**

Currently, as shown in #73, nothing is really displayed on an error page.

**Expected behavior:**

I would like to have the following displayed, all with as much explanation as possible:

- [ ] (1) traceback #74 
- [ ] (2) installation information
  - [ ] (2.1) git commit/version number
  - [ ] (2.2) Python version number
  - [ ] (2.3) If required packages are installed and which are installed
- [ ] (3) some explanatory text that this is unexpected and what it means: the service can not be performed as expected
- [ ] (4) a link to the issues page,  inviting to pose the problem
  - [ ] (4.1) A started description which can be copied and pasted into the issue
- [ ] (5) a link to gitter with an inviting text to get started and contribute

I believe, once people come from eventyay, this will help them get to report the error.

If you like to work on the issue, please create a separate PR for each point with the point number e.g. 4.1 mentioned in the heading and referring to this issue with #75 in the description, so it turns up in the discussion.

**Comment by S2606** [comment]
@niccokunzmann I would like to work on this one

**Comment by niccokunzmann** [comment]
@S2606 Sure, which point?

**Comment by vaibhavsingh97** [comment]
@niccokunzmann can I work on pont 1 and point 5?

**Comment by niccokunzmann** [comment]
@vaibhavsingh97 Welcome! Sure, you can. If you like, share your progress as soon as you have some, so that others can learn and build on it even if it is not in the development branch.

**Comment by vaibhavsingh97** [comment]
@niccokunzmann  i resolved point 1 😄

**Comment by jajodiaraghav** [comment]
Once we have the 500 page merged, we can split this talk into multiple sub-tasks so that we can close this issue fast. @vaibhavsingh97 is working on creating a 500 page :)

**Comment by jajodiaraghav** [comment]
@vaibhavsingh97 Any update?

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav I will send PR by tomorrow. I had my exam today 😅
