### ISSUE TITLE
Integrate Firebase SDK Python

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#753]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Need to integrate Firebase SDK functionality so for that we need SDK.

**Comment by ParthS007** [comment]
Claiming

**Comment by vaibhavsingh97** [comment]
@ParthS007 Can I work with you? As I had shown interest in https://github.com/fossasia/badgeyay/issues/707
