### ISSUE TITLE
Firebase Config Initialization

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#754]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

There is no firebase config present.

**Expected behaviour:**

There should be a common firebase config accessible to all.

@mariobehling Can you please create badgeyay firebase app and give us access so that we can deploy cloud functions and integrate the SDK.

**Comment by ParthS007** [comment]
Closing as completed :+1:
