### ISSUE TITLE
ERD for Badgeyay

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#757]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

ERD for Badgeyay as on May 13, 2018

**Comment by gabru-md** [comment]
Here is the ERD diagram as proposed in the meeting
![untitled diagram](https://user-images.githubusercontent.com/25414121/39970089-2db76a58-5703-11e8-8dd2-4b54ce86bdf5.png)

**Comment by ParthS007** [comment]
@vaibhavsingh97  You can have a discussion here :+1:

**Comment by vaibhavsingh97** [comment]
@gabru-md Can you please update this issue with the ERD Diagram you made and add me as an collaborator

**Comment by gabru-md** [comment]
I've given everyone the permission to edit the erd

**Comment by ParthS007** [comment]
closing this :+1:
