### ISSUE TITLE
Port the UI to semantic

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#759]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Due to the addition of semantic UI, it is clashing with the bootstrap.
**Expected behaviour:**

There should only be semantic UI as discussed in the meeting yesterday.

**Steps to reproduce:**
Just code any example with the Semantic UI.

__Working on Fix__

**Comment by ParthS007** [comment]
closing this :+1:
