### ISSUE TITLE
Make merge_badges.py independent of linux commands

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#76]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**
merge_badges.py contains linux commands being executed from python code, this makes the app dependent on os.

**Expected behavior:**
Remove the linux commands and use corresponding python code

**Comment by djmgit** [comment]
I am working on it.

**Comment by jajodiaraghav** [comment]
@djmgit Please do it in a separate file (do not delete current merge_badges.py). I still think we should have both the files in our system.

**Comment by djmgit** [comment]
@jajodiaraghav ok, so should I modify the present python script or should I create a separate version?

**Comment by jajodiaraghav** [comment]
Create a separate one! :)

**Comment by djmgit** [comment]
@jajodiaraghav ok :)

**Comment by niccokunzmann** [comment]
There are several commands shell commands used. Th most parallel workflow would be to list each command/create an issue for each command and replacing each command in a separate pull-request. This way, your work can be taken on in case you sleep/pause.

**Comment by gabru-md** [comment]
@djmgit please share you progress

**Comment by jajodiaraghav** [comment]
@djmgit Are you working on this PR?
Please share your progress in case you are.
