### ISSUE TITLE
Page not responsive

### ISSUE THREAD

**Issue by sounak98** [fossasia/badgeyay#77]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**
The page is not responsive, gets distorted for smaller screen sizes.

**Expected behavior:**
The page should be responsive.

**Steps to reproduce:**
![screen shot 2017-09-17 at 11 40 37 am](https://user-images.githubusercontent.com/22390515/30518504-5bc3d818-9b9d-11e7-8f52-31c0f448f5d1.png)

**Comment by sounak98** [comment]
I would like to work on this.

**Comment by S2606** [comment]
@sounak98 Feel free to send a PR :)

**Comment by sounak98** [comment]
@S2606 I've sent a PR. Please review.
