### ISSUE TITLE
merge_badge link is wrong 

### ISSUE THREAD

**Issue by prateekiiest** [fossasia/badgeyay#775]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Leads to 404 error

**Expected behaviour:**

Should point to the code

**Steps to reproduce:**
Replace the link with correct one

**Comment by prateekiiest** [comment]
Working on it

**Comment by gabru-md** [comment]
please elaborate onto the issue ?
