### ISSUE TITLE
Error message not showing up

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/badgeyay#78]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Comment by jajodiaraghav** [comment]
Claiming

**Comment by gabru-md** [comment]
What exactly is the issue ? Can you please explain ?

**Comment by jajodiaraghav** [comment]
Clicking the upload button without uploading any file shows an error showing a CSV fil is required. Now it doesn't.
