### ISSUE TITLE
Trigger Flake8 in Travis

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#783]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Currently, Flake8 is run by Hound bot. 
We can directly use the flake8 config to check linting and errors in Travis itself.

Open to claim

**Comment by yashLadha** [comment]
Claiming :+1:

**Comment by ParthS007** [comment]
Sure @yashLadha  Please go ahead :+1:
