### ISSUE TITLE
Not selecting any of the download types still generates PDF 

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/badgeyay#79]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

The best way to fix this is to make it a required field, so that one should be selected.

**Comment by jajodiaraghav** [comment]
Claiming 🎢

**Comment by gabru-md** [comment]
It is because of an `else` command.
Replacing it with `elif` with a condition will solve this problem.
Cheers  :+1:
