### ISSUE TITLE
Provide an option to select a PNG from default images

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/badgeyay#8]
Provide an option to choose from a set of default images (in /uploads folder) so that user can create badges without the need to upload images themselves. The user should be able to select one (multiple?) image from the set of images and upload a CSV to generate badges.

**Comment by jajodiaraghav** [comment]
I am a little confused regarding how this should be implemented.
Can we just add an optional `select-dropdown-input` containing the names of the default PNG files to choose from?

I would like to know what other people think about this.

**Comment by niccokunzmann** [comment]
1) I would like to see a list of all png files to choose from - they are very small but recognizable, like 30px wide.

**Comment by jajodiaraghav** [comment]
Okay. Working on it :)
