### ISSUE TITLE
Validation error on entering data manually

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#80]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**
Entering anything generates badges
![image](https://user-images.githubusercontent.com/18497513/30518653-cbf300ec-9ba1-11e7-818b-eddd5fcf0db3.png)
![image](https://user-images.githubusercontent.com/18497513/30518658-ebe25812-9ba1-11e7-9dae-218291efcd96.png)

**Expected behavior:**
If we know the type of data to be entered,then we can validate it as per the needs

**Steps to reproduce:**

**Comment by S2606** [comment]
@jajodiaraghav @gabru-md @niccokunzmann I need your point of view in this

**Comment by gabru-md** [comment]
I went through the sample CSVs to have an idea of what format should the manual data be.
But there were many samples and every sample had different arrangement of data( different number of rows etc) .
So we can normalise a format to be entered into the manual format. 
This needs to be discussed. What do you say ?

**Comment by S2606** [comment]
@gabru-md Yeah i think we need to sort of define a protocol sort of stuff for this.Lets others give their opinion on this

**Comment by jajodiaraghav** [comment]
I think this can be simply done in main.py file, and if the data entered is in incorrect format, we can just show them the error.

**Comment by S2606** [comment]
@jajodiaraghav Do we currently have a format of writing data manually?

**Comment by jajodiaraghav** [comment]
The format can be specified as 4 comma separated words, in a line. Each line would generate one badge.
We can easily check this using the split() function and the len() function in Python

**Comment by S2606** [comment]
@jajodiaraghav Thank you and i will send PR for this

**Comment by jajodiaraghav** [comment]
@S2606 Are you working on this, or can I claim this?

**Comment by S2606** [comment]
@jajodiaraghav  I am working on this

**Comment by niccokunzmann** [comment]
@S2606 Could you share your progress?

**Comment by niccokunzmann** [comment]
You can collaborate, e.g. on the same branch.

**Comment by S2606** [comment]
@niccokunzmann I will surely send the PR in few hours.
