### ISSUE TITLE
Storing badge data in database

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#800]
Now that, the badge generating logic has been integrated into the backend service, we can start with storing the badge data in database. So this issue requires creating any extra necessary models required and storing details in the db.

**Comment by vaibhavsingh97** [comment]
I want to work on this issue

**Comment by djmgit** [comment]
@vaibhavsingh97 great, please go ahead. Assigned it to you.

**Comment by ParthS007** [comment]
This is already done @djmgit . 
Please have a look here ; https://github.com/fossasia/badgeyay/blob/development/backend/blueprint/api/models/badges.py

Hence, this issue can be closed :+1:

**Comment by djmgit** [comment]
@vaibhavsingh97 @ParthS007 @gabru-md badges and files are related to user. Thats good. Badges.py represents a class of badges created from a given csv. So I guess there should be a relation between badges and file. Also badges should have some extra fields like time and date of creation, font, font size, color etc.
Also the badge data is not being store currently in database in generate badges api.
All these can be addressed in this issue.

**Comment by djmgit** [comment]
Since @vaibhavsingh97 has shown interest in this issue, I guess he can address all these requirements here.

**Comment by vaibhavsingh97** [comment]
@djmgit will send PR soon

**Comment by gabru-md** [comment]
Same case here.
This issue has been waiting a PR for over 3 days now. So I can work on this issue.
@ParthS007 @yashLadha @djmgit @harshit98 please provide views.
This has been stalling as well. Should I go ahead and work on it ?

**Comment by ParthS007** [comment]
@vaibhavsingh97  What's the status of this issue? 
@gabru-md  I think you should go ahead as there are connectivity issues with @vaibhavsingh97 :+1:

**Comment by vaibhavsingh97** [comment]
Can you guys wait for a day please, as I will send PR.

**Comment by gabru-md** [comment]
It has been 3 days and you have issues claimed and in case you are not able to devote time then it is our duty to continue the project. As mentioned in another issue you've claimed, 'the progress of the project must not be stalled'.@yashLadha @ParthS007 @djmgit views please

**Comment by ParthS007** [comment]
Yes, go ahead @gabru-md  as we all abide by best practices and this issue has to be resolved according to the previous week goal. What 's your say on this @gabru-md @yashLadha?

**Comment by yashLadha** [comment]
Completely agree with you @ParthS007 :+1:

**Comment by ParthS007** [comment]
cool @gabru-md  :+1:

**Comment by vaibhavsingh97** [comment]
@gabru-md Can you please wait, as I am on the verge of completion and will send PR shortly
