### ISSUE TITLE
Adding Support for A5/A6 size badges

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#812]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

Adding Badge support for A4 size.
Currently badge generation only has A3 support unlike the previous API, where we had A4 as well in the backend. I will add the A4 support here.

**Yes, I am working on it**

**Comment by gabru-md** [comment]
Okay! I will add A5/A6 support

**Comment by ParthS007** [comment]
cool @gabru-md  :+1:

**Comment by gabru-md** [comment]
A7 will be very small and is therefore not added.
Cheers!
