### ISSUE TITLE
Guidelines for user

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#82]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**

**Expected behavior:**

There should be guidelines for user as well for the requested format of json or csv that user uploads. 
**Steps to reproduce:**

Creating a route -> /guidlines with proper documentation should do.

**Comment by gabru-md** [comment]
@jajodiaraghav @S2606 what do you say ?

**Comment by jajodiaraghav** [comment]
Instead of route, we could create a modal or a tooltip popover. What do other people think?

**Comment by jajodiaraghav** [comment]
Instead of route, we could create a modal or a tooltip popover. What do other people think?

**Comment by niccokunzmann** [comment]
I think, as a user, I will not read the text but just paste any data I have and see what comes out.

**Comment by S2606** [comment]
@niccokunzmann if user paste any data they should recieve an error that they cant paste any data.

**Comment by niccokunzmann** [comment]
Okay, cool. Then I like to idea of the guidelines as a page and I would like to see them, when I paste useless data.

**Comment by gabru-md** [comment]
I would work on this! 
Any valuable suggestions?

**Comment by gabru-md** [comment]
I'll be working on this now,
@niccokunzmann @jajodiaraghav 
please give me the format of files so that i can add them in guidelines.
thanks!

**Comment by niccokunzmann** [comment]
csv with max. four lines
example JSON here, please include most important attributes, see the code:
[speakers.json-anonymous.zip](https://github.com/fossasia/badgeyay/files/1311587/speakers.json-anonymous.zip)

**Comment by jajodiaraghav** [comment]
Any update @gabru-md ?

**Comment by gabru-md** [comment]
yes! @jajodiaraghav
I have started working on it. Will be submitting a PR very soon, hopefully within some hours.
:D
