### ISSUE TITLE
Modify GenerateBadges class 

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#820]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request

**Current behaviour:**
currently, Generate Badges only consider image and csv

**Expected behaviour:**
It should consider event logo, font, font-size, font-color, etc

we can use [ReportLab](https://www.reportlab.com/documentation/tutorial/) library to genrate badges.

**Yes, I am interested in working on this issue**

Views @djmgit @ParthS007 @gabru-md @yashLadha

**Comment by gabru-md** [comment]
This task is way ahead of what we are doing currently

**Comment by ParthS007** [comment]
@vaibhavsingh97 This issue is related to badge enhancement and I don't understand why you are opening such issues when we have similar issues already opened for these features. Please follow best practices.
Closing this in reference to #354 , #595 & #343 
Avoid opening duplicate issues in future :+1: 
Closing this :+1:

**Comment by gabru-md** [comment]
yes

**Comment by vaibhavsingh97** [comment]
@ParthS007 this issue is for  enhancement of current system. `ReportsLab` can do what badgeyay needs. Also, you can ask me to close the issue 😞

**Comment by gabru-md** [comment]
I am sorry, I guess he closed it by himself.

Can you please close the issue @vaibhavsingh97 ? :smile:

**Comment by ParthS007** [comment]
Yes , Please discuss these features in the referenced Issues. No need of creating duplicate issues and mention the use of ReportsLab in the respective issue itself. Please follow best practices by not opening duplicate issues.
cheers !!
Hence, I request you to please close the issue. :+1:

**Comment by yashLadha** [comment]
Currently lxml and caurosvg is there to do the work which report lab is
doing. I think there is no need to move to other system. Can you provide
some cases where it will benefit as I can't see any use case to switch the
code for sake of one library. The approach which we are following currently
will give us advantage in extending functionalities, as previously we have
made. Cheers

**Comment by vaibhavsingh97** [comment]
@djmgit @gabru-md @ParthS007 @yashLadha 
To generate badges we need 
- csv or manual data entry
- Different fonts, font sizes, font-colors, etc
- Different Size of images (logo of the event)
- Different Size of the background images
- Different Badge size

## Current Scenario
We are writing code for doing small things like changing font, changing font size, etc. 

##After integrating ReportLab
It will help in creating customized PDFs for different users or different pieces of content
It has an inbuilt function to change page layout, typography, Drawing Operations, will ease if we deal with layers. So basically you can say that what we are doing with `PyPDF, CairoSVG, and other libraries`, we can use ReportLab to generate badges with lot fewer lines of codes and it will do an amazing job.

For the sample please refer to https://www.reportlab.com/documentation/tutorial/product-catalogue/

**Comment by yashLadha** [comment]
Writing code for such things like font size and weight gives us advantage as we know how to implement them and extend them for lated badge designs. The problem with this is same as we are constraint to have a definitte structure and justt merely change the value of variable. Whereas conference badge has a dynamic svg editor in place which works on the same philosophy as we are doing generatign badges from svg. They have placed position pointers in the svg as well and create a js code to manipulate the pointers to dynamically resize the content. This things enable dynamic generation of badges whereas relying on ReportLab will constraint us as we can only change the images and text in the ste of defined config which we can do currently as well and the system currently is working preety fine. If we go with creatign a dynamic config for reportlab them it will be a tedious task and it is much easier to manipulate svg realtime them the config for reportlab which cannot prevew in realtime as well. For reference and more insight visit this link : [Link](http://conferencebadge.com/demo)

**Comment by ParthS007** [comment]
Yes, We already have a discussion on this and as @yashLadha  said relying on ReportLab will constraint us as we can only change the images and text in the set of defined config which we can do currently as well.

**Comment by ParthS007** [comment]
closing this in reference to chat on gitter channel :+1:
