### ISSUE TITLE
updating readme

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#822]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

please make the suggested changes to readme

**Comment by ParthS007** [comment]
claiming

**Comment by gabru-md** [comment]
okay

**Comment by abhi40308** [comment]
I would like to work on the issue, if you have no problem with it @ParthS007 @gabru-md

**Comment by ParthS007** [comment]
Yes, You can go ahead @abhi40308 :+1:
