### ISSUE TITLE
gabu-md as maintainer

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#84]
@gabru-md has proven commitment by commits, see [here](https://github.com/fossasia/badgeyay/commits?author=gabru-md) I add him as a miantainer. If you have any concerns, please state them here.
Otehrwise, we can close this after some time and if somthing comes up, we can have a discussion.

@gabru-md please read the [CCCC guide](https://rfc.zeromq.org/spec:42/C4) and the README file if you like to take on this responsibility.

**Comment by gabru-md** [comment]
Yes i would definitely love to. Meanwhile I'll just read the guide . :+1:
Thank you!

**Comment by S2606** [comment]
@niccokunzmann Can we close this issue since gabru-md is a maintainer :)
