### ISSUE TITLE
Modify Response Class

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#846]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
In https://github.com/fossasia/badgeyay/blob/development/backend/blueprint/api/utils/response.py#L12:L16, If I want to pass general response like "User created successfully", other fields will also appear like id, attributes which are not needed. 

**Expected behaviour:**
Response method should respond to the type of messages like for general message it should only include a message and status

**I want to work on this issue**

**Comment by yashLadha** [comment]
@vaibhavsingh97 This is needed as we are going to follow JSON API Convention [Link](http://jsonapi.org/) and the same is being the convention in ember. So i think this issue is redundant @djmgit  and can be closed. Thanks

**Comment by ParthS007** [comment]
closing this as not needed :+1:
