### ISSUE TITLE
Footer element overlapping!

### ISSUE THREAD

**Issue by jishnujayakumar** [fossasia/badgeyay#88]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**
On submitting the input file to generate the output, the UI becomes like the one shown in the attached figure.[screenshot from 2017-09-17 17 28 32](https://user-images.githubusercontent.com/10737835/30520611-f9a9e33e-9bce-11e7-9453-f75bc9c37ba6.png)

**Expected behavior:**
The overlapping of the form and footer element shouldn't take place. Once the download button becomes visible, the footer element should adjust itself and stay at the bottom of the page without overlapping with the form element.

**Steps to reproduce:**
A slight change in the UI code will be sufficient.

**Comment by jishnujayakumar** [comment]
I want to work on it.

**Comment by jajodiaraghav** [comment]
@jishnujayakumar This is a duplicate bug. Please see #63 
You can claim this issue if Pk13055 doesn't reply within a day :)
This is a priority bug.

**Comment by gabru-md** [comment]
There is already an issue of this sort and is already assigned. Have a look through the issues.
:+1:

**Comment by jishnujayakumar** [comment]
#63 #88 Solved by @Pk13055
