### ISSUE TITLE
Make travis run again

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#89]
**I'm submitting a ...**  (check one with "x")
- [X] bug report

**Current behavior:**

The current build of travis fails.
This is because the package selenium is not installed.

**Expected behavior:**

Create a

- `test-requirements.txt` file
- add the missing packages to it
- make travsi run

**Steps to reproduce:**

https://travis-ci.org/fossasia/badgeyay/builds/276493606

**Comment by S2606** [comment]
@niccokunzmann  I would like to work on this one

**Comment by niccokunzmann** [comment]
Hi @S2606 great. Please add a PR for us to track progress and give input.

**Comment by niccokunzmann** [comment]
https://github.com/fossasia/badgeyay/blob/development/app/tests/test.py#L9 - uses firefox as a driver.
You might need to install phantomjs - a browser without a user interface - to make it runnable on travis.
