### ISSUE TITLE
Allow downloading of badges in multiple formats

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/badgeyay#9]
Allow downloading of badges in multiple formats:

- [ ] ZIP file containing all SVGs and PDFs
- [ ] SVG
- [ ] PDF of individual set

**Comment by yashhere** [comment]
working on it.

**Comment by jajodiaraghav** [comment]
Hi @yashhere How is it going?
Feel free to ask for help in case you need any :)

**Comment by niccokunzmann** [comment]
If you share a link to your progress on github, this is useful for others.

**Comment by yashhere** [comment]
@jajodiaraghav, Sorry I was busy with some other work. I understand that the zip file will contain all the PNGs and SVGs. But when a user uploads another CSV file, the older data and CSV file is also there. So all-badges.pdf will contain images from both CSV files. So the zip should contain all the images generated till now? What about the second and third point? SVG and PNG of the latest files uploaded and should it be zipped or individual?

**Comment by jajodiaraghav** [comment]
The zip file will contain:
1. all-badges.pdf
2. Individual pdf files generated
3. Individual svg files generated

> But when a user uploads another CSV file, the older data and CSV file is also there. 
The older data will be removed before uploading new files. Do not worry about them.
See #35
