### ISSUE TITLE
Swagger UI is not working

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#916]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

Swagger UI is not working. It can be reverted as the PR might have been wrong.
**I will send a new PR, reverting the previous one and adding the same, if needed**
@djmgit your views?

**Comment by djmgit** [comment]
@vaibhavsingh97 what is the problem with swagger UI. Please have a look.

**Comment by ParthS007** [comment]
Yes, I have checked it. As it's not working. So you can go ahead :+1:

**Comment by gabru-md** [comment]
This issue can be closed as the reverting has been done

**Comment by vaibhavsingh97** [comment]
@gabru-md which api-end points you are hitting? you have to hit `/apidocs/`

**Comment by vaibhavsingh97** [comment]
@djmgit in https://github.com/fossasia/badgeyay/pull/749, i mentioned : Documentation serves at: http://127.0.0.1:5000/apidocs/

**Comment by vaibhavsingh97** [comment]
![image](https://user-images.githubusercontent.com/8705386/40884298-85b33dbe-672e-11e8-8517-d8e21bd8bbb0.png)

**Comment by djmgit** [comment]
@vaibhavsingh97 we tried this link : https://badgeyay-api.herokuapp.com/apidocs
how ever no docs were working. All of us tried, and it worked for none of us

**Comment by djmgit** [comment]
Please let us know where we went wrong. You can always reopen this issue, make your changes, with your PR, please provide a test link of the app deployed on heroku so that we can all make sure that swagger is working.

**Comment by djmgit** [comment]
@vaibhavsingh97 btw, endpoint wrong which we tried?

**Comment by vaibhavsingh97** [comment]
@djmgit No idea about Heroku, but yes, I can provide test link for this.

**Comment by djmgit** [comment]
@vaibhavsingh97 alright, please send a tested PR.
