### ISSUE TITLE
Create one-click docker deployment button

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#92]
**I'm submitting a ...**  (check one with "x")
- [X] feature request

**Current behavior:**

Currently, I can only see a deploy to heroku button.

**Expected behavior:**

Please also create a deploy to docker button. You can find one here: https://hub.docker.com/_/wordpress/

"Try in PWD"

**Comment by S2606** [comment]
@niccokunzmann I would like to work on this

**Comment by niccokunzmann** [comment]
@S2606 Sure :)
