### ISSUE TITLE
Link of previously created badges are still visible on revisiting the page or after new login

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#986]
**Steps to produce**
- login to bageyay.com
- Enter the required information and create badges.
- Create the badges
- Download link is available after some time.
- Refresh the page, or logout and login again, go to the badge creation page, the link is still visible.
- Also when I create badges for the second time, the link of the previously created badges is still there.
  This is a bit confusing as, user might think the previous link to be the new link and press on that in order
  to download and find the old badges downloaded!

The link of the previous/old/past badges should not appear on fresh login. Apparently it might seem lucrative as the users are able to instantly download their most recently created badges, but there is a difference between latest badges and most recently created badges. If we want we can later create a section providing the feature for downloading the most recently created badges.

Also, in the same session after creating badges once, if I create badges for the second time, the moment I press on **create badges** the link to old badges should disappear.

**Comment by ParthS007** [comment]
Looking into it :+1:

**Comment by ParthS007** [comment]
@yashLadha @gabru-md  I tried to provide the link in notification popup but the link was not working there. Link only disappears when there is a refresh of the page.
Can you please help me with this?
If you want to work on this issue, you can also go ahead with this :+1:  :smiley:

**Comment by yashLadha** [comment]
Is an html can't be shown in the popup. May be we can hide the link component aftre some time. Create a timeout and toggle the variable that shows the visibilty in the component.

**Comment by yashLadha** [comment]
Also make that component avaiable only if the badge is generated.
