### ISSUE TITLE
Change administrative branch policy?

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#99]
Currently, we have these options enabled:

![grafik](https://user-images.githubusercontent.com/564768/30523706-4b620762-9be6-11e7-926e-ef1d190bd675.png)

I ask myself the following:
- is having the branch up-to-date is required? Usally, it works even when one merges if the tests pass. If we scale up, it also means that for each open pull-request, all other people have to merge the master again. Once we have four or more open pull-requests, this could slow down the progress of new people contributing.
- Do we need mandatory reviews? If someone merges, we can agree, that this counts as a review. Sometimes, it is just more time to approve and merge. Also, if someone requests changes, the changes are addressed and not a review done again by the same person, this counts as rejection. Only an administrator can merge then. I think, noone should be able to block a pull-request by being absent if an other maintainer can trust it.

Conclusion: I would like to disable these two options for some time. We can act as before and have a look how we like it. After a some days, we evaluate.

What do you think?

**Comment by Pk13055** [comment]
@niccokunzmann  Could the same consideration be thought of for query-server? A large number of PRs are hindered by not being up to date.

**Comment by niccokunzmann** [comment]
@Pk13055 Sure, you can create an issue there andreference this one, if you like. As a maintainer, I like to have the code flowing and the people spending their time coding&collaborating and not waiting/doing formal stuff.

**Comment by niccokunzmann** [comment]
I will now switch it off. We can use it for 5 days and evaluate.
